redhat-openshift-ecosystem/operator-pipelines-test

operators/test-e2e-operator/0.0.7-a8e27af/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-a8e27af/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-a8e27af/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-a8e27af/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-a8e27af/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-a8e27af/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-a8e27af)

operators/test-e2e-operator/0.0.7-a01d19f/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-a01d19f/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-a01d19f/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-a01d19f/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-a01d19f/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-a01d19f/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-a01d19f)

operators/test-e2e-operator/0.0.7-d82c20a/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-d82c20a/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-d82c20a/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-d82c20a/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-d82c20a/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-d82c20a/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-d82c20a)

operators/test-e2e-operator/0.0.7-6d72cde/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-6d72cde/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-6d72cde/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-6d72cde/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-6d72cde/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-6d72cde/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-6d72cde)

operators/test-e2e-operator/0.0.7-92a6243/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-92a6243/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-92a6243/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-92a6243/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-92a6243/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-92a6243/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-92a6243)

operators/test-e2e-operator/0.0.7-8a0e612/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-8a0e612/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-8a0e612/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-8a0e612/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-8a0e612/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-8a0e612/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-8a0e612)

operators/test-e2e-operator/0.0.7-f9d8067/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-f9d8067/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-f9d8067/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-f9d8067/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-f9d8067/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-f9d8067/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-f9d8067)

operators/test-e2e-operator/0.0.7-61af43f/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-61af43f/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-61af43f/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-61af43f/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-61af43f/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-61af43f/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-61af43f)

operators/test-e2e-operator/0.0.7-a3d73d2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-a3d73d2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-a3d73d2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-a3d73d2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-a3d73d2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-a3d73d2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-a3d73d2)

operators/test-e2e-operator/0.0.7-ea4e10a/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-ea4e10a/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-ea4e10a/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-ea4e10a/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-ea4e10a/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-ea4e10a/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-ea4e10a)

operators/test-e2e-operator/0.0.7-9cd5315/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-9cd5315/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-9cd5315/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-9cd5315/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-9cd5315/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-9cd5315/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-9cd5315)

operators/test-e2e-operator/0.0.7-9884534/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-9884534/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-9884534/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-9884534/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-9884534/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-9884534/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-9884534)

operators/test-e2e-operator/0.0.7-ba7c1fe/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-ba7c1fe/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-ba7c1fe/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-ba7c1fe/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-ba7c1fe/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-ba7c1fe/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-ba7c1fe)

operators/test-e2e-operator/0.0.7-056be99/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-056be99/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-056be99/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-056be99/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-056be99/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-056be99/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-056be99)

operators/test-e2e-operator/0.0.7-c76d5ea/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-c76d5ea/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-c76d5ea/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-c76d5ea/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-c76d5ea/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-c76d5ea/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-c76d5ea)

operators/test-e2e-operator/0.0.7-169f685/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-169f685/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-169f685/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-169f685/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-169f685/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-169f685/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-169f685)

operators/test-e2e-operator/0.0.7-05bb98c/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-05bb98c/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-05bb98c/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-05bb98c/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-05bb98c/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-05bb98c/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-05bb98c)

operators/test-e2e-operator/0.0.7-2d3ed32/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-2d3ed32/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-2d3ed32/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-2d3ed32/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-2d3ed32/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-2d3ed32/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-2d3ed32)

operators/test-e2e-operator/0.0.7-8018eb2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-8018eb2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-8018eb2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-8018eb2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-8018eb2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-8018eb2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-8018eb2)

operators/test-e2e-operator/0.0.7-b96ae98/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-b96ae98/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-b96ae98/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-b96ae98/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-b96ae98/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-b96ae98/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-b96ae98)

operators/test-e2e-operator/0.0.7-f17b383/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-f17b383/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-f17b383/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-f17b383/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-f17b383/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-f17b383/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-f17b383)

operators/test-e2e-operator/0.0.7-0bafae7/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-0bafae7/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-0bafae7/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-0bafae7/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-0bafae7/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-0bafae7/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-0bafae7)

operators/test-e2e-operator/0.0.7-adc13dc/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-adc13dc/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-adc13dc/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-adc13dc/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-adc13dc/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-adc13dc/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-adc13dc)

operators/test-e2e-operator/0.0.7-4ce25c3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-4ce25c3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-4ce25c3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-4ce25c3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-4ce25c3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-4ce25c3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-4ce25c3)

operators/test-e2e-operator/0.0.7-ea563b8/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-ea563b8/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-ea563b8/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-ea563b8/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-ea563b8/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-ea563b8/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-ea563b8)

operators/test-e2e-operator/0.0.7-4ef9af3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-4ef9af3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-4ef9af3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-4ef9af3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-4ef9af3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-4ef9af3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-4ef9af3)

operators/test-e2e-operator/0.0.7-4c35ce9/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-4c35ce9/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-4c35ce9/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-4c35ce9/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-4c35ce9/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-4c35ce9/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-4c35ce9)

operators/test-e2e-operator/0.0.7-18a2835/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-18a2835/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-18a2835/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-18a2835/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-18a2835/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-18a2835/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-18a2835)

operators/test-e2e-operator/0.0.7-aa0a63d/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-aa0a63d/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-aa0a63d/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-aa0a63d/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-aa0a63d/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-aa0a63d/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-aa0a63d)

operators/test-e2e-operator/0.0.7-a06376b/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-a06376b/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-a06376b/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-a06376b/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-a06376b/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-a06376b/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-a06376b)

operators/test-e2e-operator/0.0.7-f845320/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-f845320/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-f845320/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-f845320/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-f845320/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-f845320/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-f845320)

operators/test-e2e-operator/0.0.7-44d983d/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-44d983d/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-44d983d/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-44d983d/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-44d983d/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-44d983d/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-44d983d)

operators/test-e2e-operator/0.0.7-f0c8c36/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-f0c8c36/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-f0c8c36/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-f0c8c36/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-f0c8c36/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-f0c8c36/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-f0c8c36)

operators/test-e2e-operator/0.0.7-bcce7fc/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-bcce7fc/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-bcce7fc/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-bcce7fc/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-bcce7fc/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-bcce7fc/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-bcce7fc)

operators/test-e2e-operator/0.0.7-ce8d5c8/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-ce8d5c8/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-ce8d5c8/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-ce8d5c8/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-ce8d5c8/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-ce8d5c8/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-ce8d5c8)

operators/test-e2e-operator/0.0.7-cf5fa29/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.7-cf5fa29/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.7-cf5fa29/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.7-cf5fa29/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.7-cf5fa29/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.7-cf5fa29/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.7-cf5fa29)

operators/test-e2e-operator/0.0.8-448/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.8-448/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.8-448/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.8-448/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.8-448/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.8-448/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.8-448)

operators/test-e2e-operator/0.0.8-450/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.8-450/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.8-450/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.8-450/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.8-450/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.8-450/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.8-450)

operators/test-e2e-operator/0.0.8-4511/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.8-4511/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.8-4511/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.8-4511/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.8-4511/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.8-4511/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.8-4511)

operators/test-e2e-operator/0.0.8-4512/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.8-4512/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.8-4512/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.8-4512/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.8-4512/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.8-4512/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.8-4512)

operators/test-e2e-operator/0.0.8-4621/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.8-4621/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.8-4621/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.8-4621/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.8-4621/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.8-4621/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.8-4621)

operators/test-e2e-operator/0.0.466-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.466-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.466-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.466-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.466-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.466-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.466-1)

operators/test-e2e-operator/0.0.466-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.466-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.466-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.466-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.466-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.466-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.466-2)

operators/test-e2e-operator/0.0.467-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.467-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.467-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.467-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.467-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.467-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.467-2)

operators/test-e2e-operator/0.0.468-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.468-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.468-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.468-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.468-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.468-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.468-2)

operators/test-e2e-operator/0.0.469-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.469-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.469-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.469-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.469-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.469-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.469-1)

operators/test-e2e-operator/0.0.473-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.473-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.473-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.473-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.473-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.473-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.473-3)

operators/test-e2e-operator/0.0.475-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.475-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.475-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.475-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.475-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.475-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.475-1)

operators/test-e2e-operator/0.0.475-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.475-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.475-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.475-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.475-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.475-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.475-3)

operators/test-e2e-operator/0.0.480-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.480-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.480-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.480-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.480-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.480-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.480-2)

operators/test-e2e-operator/0.0.481-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.481-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.481-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.481-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.481-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.481-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.481-1)

operators/test-e2e-operator/0.0.484-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.484-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.484-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.484-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.484-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.484-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.484-1)

operators/test-e2e-operator/0.0.485-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.485-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.485-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.485-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.485-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.485-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.485-3)

operators/test-e2e-operator/0.0.486-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.486-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.486-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.486-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.486-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.486-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.486-1)

operators/test-e2e-operator/0.0.487-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.487-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.487-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.487-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.487-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.487-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.487-1)

operators/test-e2e-operator/0.0.490-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.490-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.490-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.490-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.490-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.490-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.490-1)

operators/test-e2e-operator/0.0.491-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.491-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.491-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.491-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.491-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.491-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.491-1)

operators/test-e2e-operator/0.0.492-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.492-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.492-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.492-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.492-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.492-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.492-1)

operators/test-e2e-operator/0.0.494-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.494-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.494-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.494-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.494-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.494-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.494-1)

operators/test-e2e-operator/0.0.495-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.495-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.495-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.495-4/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.495-4/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.495-4/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.495-4)

operators/test-e2e-operator/0.0.497-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.497-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.497-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.497-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.497-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.497-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.497-1)

operators/test-e2e-operator/0.0.499-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.499-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.499-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.499-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.499-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.499-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.499-3)

operators/test-e2e-operator/0.0.524-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.524-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.524-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.524-4/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.524-4/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.524-4/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.524-4)

operators/test-e2e-operator/0.0.525-5/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.525-5/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.525-5/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.525-5/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.525-5/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.525-5/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.525-5)

operators/test-e2e-operator/0.0.527-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.527-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.527-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.527-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.527-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.527-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.527-1)

operators/test-e2e-operator/0.0.532-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.532-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.532-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.532-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.532-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.532-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.0.532-1)

operators/test-e2e-operator/0.0.1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.0.1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63168fb5762967d9f56441f1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63168fb1762967d9f56441ef
=> operator test-e2e-operator (0.0.1)

operators/test-e2e-operator/0.0.44-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.44-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.44-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.44-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.44-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.44-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.0.44-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6317a537b21c22da4d685f87
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6317a535b21c22da4d685f85
=> operator test-e2e-operator (0.0.44-1)

operators/test-e2e-operator/0.0.46-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.46-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.46-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.46-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.46-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.46-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.0.46-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6317b0d904bd94a65435d062
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6317b0d5762967d9f5644296
=> operator test-e2e-operator (0.0.46-1)

operators/test-e2e-operator/0.0.48-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.48-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.48-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.48-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.48-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.48-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.0.48-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6317bbe2762967d9f56442a7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6317bbde762967d9f56442a5
=> operator test-e2e-operator (0.0.48-1)

operators/test-e2e-operator/0.1.5-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.5-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.5-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.5-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.5-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.5-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.5-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/631f3d37f3fb9ab5a277c7a2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/631f3d359484f3059ce23248
=> operator test-e2e-operator (0.1.5-1)

operators/test-e2e-operator/0.1.6-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.6-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.6-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.6-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.6-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.6-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.6-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6321f7cfec901c16d9da948f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6321f7cdec901c16d9da948d
=> operator test-e2e-operator (0.1.6-1)

operators/test-e2e-operator/0.1.7-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.7-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.7-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.7-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.7-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.7-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.7-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6322198b3cf1e6d72d1c83e2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6322198aec901c16d9da949c
=> operator test-e2e-operator (0.1.7-1)

operators/test-e2e-operator/0.1.7-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.7-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.7-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.7-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.7-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.7-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.7-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/632220743cf1e6d72d1c83ec
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/632220723cf1e6d72d1c83ea
=> operator test-e2e-operator (0.1.7-2)

operators/test-e2e-operator/0.1.7-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.7-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.7-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.7-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.7-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.7-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.7-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/632249393cf1e6d72d1c8403
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63224937ec901c16d9da94bb
=> operator test-e2e-operator (0.1.7-3)

operators/test-e2e-operator/0.1.10-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.10-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.10-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.10-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.10-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.10-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.10-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6323374428719e952391badd
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6323374028719e952391badb
=> operator test-e2e-operator (0.1.10-1)

operators/test-e2e-operator/0.1.11-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.11-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.11-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.11-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.11-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.11-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.11-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63234e555087abe683ab7dc0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63234e53e8812ebea1cf9c32
=> operator test-e2e-operator (0.1.11-1)

operators/test-e2e-operator/0.1.13-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.13-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.13-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.13-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.13-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.13-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.13-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6324388371807269e8c8f534
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/632438827fbfe71ece869eb1
=> operator test-e2e-operator (0.1.13-1)

operators/test-e2e-operator/0.1.13-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.13-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.13-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.13-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.13-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.13-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.13-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/632870bb637f8ee067489fb0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/632870b9637f8ee067489fae
=> operator test-e2e-operator (0.1.13-2)

operators/test-e2e-operator/0.1.13-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.13-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.13-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.13-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.13-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.13-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.13-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63296c8ee66867e1d271a77f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63296c8c0cd32d1e221519df
=> operator test-e2e-operator (0.1.13-3)

operators/test-e2e-operator/0.1.14-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.14-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.14-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.14-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.14-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.14-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.14-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/632a2d79f5fcd2a97d81a3b2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/632a2d78f5fcd2a97d81a3b0
=> operator test-e2e-operator (0.1.14-2)

operators/test-e2e-operator/0.1.14-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.14-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.14-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.14-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.14-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.14-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.14-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/632b25727d938df94659e4ee
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/632b25717d938df94659e4ec
=> operator test-e2e-operator (0.1.14-3)

operators/test-operator-amisstea/0.0.3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-operator-amisstea/0.0.3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-operator-amisstea/0.0.3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-operator-amisstea/0.0.3/manifests/test-operator-amisstea.clusterserviceversion.yaml, operators/test-operator-amisstea/0.0.3/manifests/tools.opdev.io_demoresources.yaml, operators/test-operator-amisstea/0.0.3/metadata/annotations.yaml, operators/test-operator-amisstea/ci.yaml
Name: **test-operator-amisstea**
Version: **0.0.3**
Certification project: 6217bc4dc6e33467ea6c8b5c
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/632c6c877750be72a5be99f8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/632c6c85c9926368d2b5e2e5
=> operator test-operator-amisstea (0.0.3)

operators/test-e2e-operator/0.1.15-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.15-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.15-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.15-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.15-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.15-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.15-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/632d12e450ede303bbf5a381
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/632d12e2c9926368d2b5e319
=> operator test-e2e-operator (0.1.15-1)

operators/test-e2e-operator/0.1.16-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.16-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.16-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.16-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.16-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.16-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.16-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6331de58a04fd6cc86cbdaea
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6331de5605b56b8a90c2a974
=> operator test-e2e-operator (0.1.16-1)

operators/test-e2e-operator/0.1.18-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.18-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.18-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.18-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.18-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.18-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.18-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/633292b605b56b8a90c2a9bb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/633292b41e64e3275b1d1f3b
=> operator test-e2e-operator (0.1.18-1)

operators/test-e2e-operator/0.1.19-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.19-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.19-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.19-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.19-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.19-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.19-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63349d750735088c02cbd841
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63349d73a9eb2d055e1d1c61
=> operator test-e2e-operator (0.1.19-1)

operators/test-e2e-operator/0.1.20-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.20-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.20-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.20-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.20-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.20-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.20-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6334adb06d0cd65b8595bf05
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6334adae6d0cd65b8595bf03
=> operator test-e2e-operator (0.1.20-1)

operators/test-e2e-operator/0.1.21-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.21-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.21-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.21-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.21-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.21-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.21-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6334b8f871c19bdc606921e6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6334b8f7087bb830305c35ba
=> operator test-e2e-operator (0.1.21-1)

operators/test-e2e-operator/0.1.22-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.22-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.22-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.22-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.22-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.22-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.22-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6334bc3271c19bdc606921e9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6334bc306d0cd65b8595bf15
=> operator test-e2e-operator (0.1.22-1)

operators/test-e2e-operator/0.1.22-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.22-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.22-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.22-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.22-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.22-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.22-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6334d8e3087bb830305c35ce
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6334d8e26d0cd65b8595bf23
=> operator test-e2e-operator (0.1.22-2)

operators/test-e2e-operator/0.1.22-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.22-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.22-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.22-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.22-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.22-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.22-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63355854087bb830305c3617
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/633558526d0cd65b8595bf6f
=> operator test-e2e-operator (0.1.22-3)

operators/test-e2e-operator/0.1.22-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.22-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.22-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.22-4/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.22-4/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.22-4/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.22-4**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/633563db087bb830305c3625
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/633563d91a9491be47439eca
=> operator test-e2e-operator (0.1.22-4)

operators/test-e2e-operator/0.1.21-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.21-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.21-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.21-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.21-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.21-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.21-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6335949c087bb830305c38be
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6335949a6d0cd65b8595c228
=> operator test-e2e-operator (0.1.21-2)

operators/test-e2e-operator/0.1.22-5/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.22-5/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.22-5/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.22-5/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.22-5/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.22-5/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.22-5**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6335ab611a9491be4743a17f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6335ab5f087bb830305c38ca
=> operator test-e2e-operator (0.1.22-5)

operators/test-e2e-operator/0.1.23-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.23-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.23-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.23-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.23-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.23-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.23-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6335e3ca71c19bdc606924e6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6335e3c86d0cd65b8595c24d
=> operator test-e2e-operator (0.1.23-1)

operators/test-e2e-operator/0.1.23-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.23-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.23-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.23-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.23-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.23-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.23-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6335ebd61a9491be4743a190
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6335ebd41a9491be4743a18e
=> operator test-e2e-operator (0.1.23-2)

operators/test-e2e-operator/0.1.25-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.25-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.25-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.25-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.25-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.25-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.25-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/633721676d0cd65b8595c64d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63372165087bb830305c3cb2
=> operator test-e2e-operator (0.1.25-1)

operators/test-e2e-operator/0.1.26-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.26-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.26-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.26-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.26-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.26-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.26-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/633b3c97cd9667532c28b225
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/633b3c9625f4cf919e57afe7
=> operator test-e2e-operator (0.1.26-1)

operators/test-e2e-operator/0.1.28-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.28-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.28-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.28-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.28-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.28-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.28-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/633e7970cf880087bd4a1cb0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/633e796ef4ce8e652f12a02c
=> operator test-e2e-operator (0.1.28-1)

operators/test-e2e-operator/0.1.32-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.32-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.32-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.32-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.32-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.32-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.32-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/633f6adbef2658ae652e9ddb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/633f6adaff30cf9b1d71141b
=> operator test-e2e-operator (0.1.32-1)

operators/test-e2e-operator/0.1.33-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.33-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.33-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.33-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.33-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.33-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.33-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/633fd8ddff30cf9b1d7114ac
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/633fd8dbe9e959632f574ab5
=> operator test-e2e-operator (0.1.33-1)

operators/test-e2e-operator/0.1.34-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.34-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.34-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.34-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.34-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.34-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.34-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63401e56ff30cf9b1d711666
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63401e55e9e959632f574c53
=> operator test-e2e-operator (0.1.34-1)

operators/test-e2e-operator/0.1.35-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.35-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.35-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.35-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.35-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.35-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.35-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/634047e0f2ad8996e6377edb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/634047deff30cf9b1d7116ba
=> operator test-e2e-operator (0.1.35-1)

operators/test-e2e-operator/0.1.36-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.36-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.36-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.36-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.36-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.36-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.36-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63404e00e9e959632f574c97
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63404dfeef2658ae652ea06c
=> operator test-e2e-operator (0.1.36-1)

operators/test-e2e-operator/0.1.36-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.36-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.36-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.36-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.36-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.36-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.36-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6340592eef2658ae652ea076
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6340592cef2658ae652ea074
=> operator test-e2e-operator (0.1.36-2)

operators/test-e2e-operator/0.1.36-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.36-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.36-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.36-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.36-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.36-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.36-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/634088c2f2ad8996e6377f13
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/634088c1ff30cf9b1d7116de
=> operator test-e2e-operator (0.1.36-3)

operators/test-e2e-operator/0.1.37-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.37-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.37-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.37-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.37-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.37-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.37-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63408dc9ef2658ae652ea0a7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63408dc8ff30cf9b1d7116e7
=> operator test-e2e-operator (0.1.37-1)

operators/test-e2e-operator/0.1.37-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.37-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.37-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.37-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.37-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.37-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.37-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63409614f2ad8996e6377f35
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63409612e9e959632f574ceb
=> operator test-e2e-operator (0.1.37-2)

operators/test-e2e-operator/0.1.39-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.39-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.39-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.39-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.39-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.39-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.39-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6340afc8f2ad8996e6377f54
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6340afc7ef2658ae652ea0e0
=> operator test-e2e-operator (0.1.39-1)

operators/test-e2e-operator/0.1.40-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.40-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.40-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.40-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.40-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.40-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.40-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6346ea0ee9e959632f5753eb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6346ea0cf2ad8996e63785f0
=> operator test-e2e-operator (0.1.40-1)

operators/test-e2e-operator/0.1.41-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.41-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.41-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.41-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.41-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.41-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.41-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6348049ef2ad8996e63791bf
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6348049ce9e959632f57601c
=> operator test-e2e-operator (0.1.41-1)

operators/test-e2e-operator/0.1.43-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.43-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.43-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.43-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.43-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.43-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.43-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/634d308eff30cf9b1d7136b6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/634d308cef2658ae652ec012
=> operator test-e2e-operator (0.1.43-1)

operators/test-e2e-operator/0.1.44-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.44-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.44-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.44-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.44-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.44-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.44-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/634faa903b044cbfeb0fdcc4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/634faa8e3b044cbfeb0fdcc2
=> operator test-e2e-operator (0.1.44-1)

operators/test-e2e-operator/0.1.45-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.45-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.45-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.45-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.45-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.45-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.45-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6357b4bee0c8e8c0b399d423
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6357b4b8189bfd34e1195e7a
=> operator test-e2e-operator (0.1.45-1)

operators/test-e2e-operator/0.1.46-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.46-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.46-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.46-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.46-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.46-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.46-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6357f80c59cb9b7bceeb0ac9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6357f80b59cb9b7bceeb0ac7
=> operator test-e2e-operator (0.1.46-1)

operators/test-e2e-operator/0.1.47-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.47-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.47-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.47-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.47-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.47-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.47-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63580f5b71bb75297533344f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63580f5a71bb75297533344d
=> operator test-e2e-operator (0.1.47-2)

operators/test-e2e-operator/0.1.47-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.47-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.47-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.47-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.47-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.47-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.47-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/637f8370a6da87acfc035167
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/637f836ea14a72e8400e85a6
=> operator test-e2e-operator (0.1.47-3)

operators/test-e2e-operator/0.1.47-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.47-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.47-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.47-4/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.47-4/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.47-4/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.47-4**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/637f967ea6da87acfc03518f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/637f967ca14a72e8400e85cd
=> operator test-e2e-operator (0.1.47-4)

operators/test-e2e-operator/0.1.62-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.62-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.62-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.62-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.62-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.62-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.62-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/638088b426a92eb5bfdb1001
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/638088b326a92eb5bfdb0fff
=> operator test-e2e-operator (0.1.62-1)

operators/test-e2e-operator/0.1.65-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.65-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.65-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.65-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.65-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.65-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.65-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63888fb04618509f23795322
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63888fae63c70231be519b7f
=> operator test-e2e-operator (0.1.65-1)

operators/test-e2e-operator/0.1.66-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.66-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.66-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.66-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.66-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.66-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.66-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6390798763c70231be5214df
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63907985ffbca00bd70fdc0d
=> operator test-e2e-operator (0.1.66-1)

operators/test-e2e-operator/0.1.67-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.67-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.67-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.67-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.67-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.67-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.67-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/639b2c9d38e2506c26a1ab53
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/639b2c9c854c54bb953d373e
=> operator test-e2e-operator (0.1.67-2)

operators/test-e2e-operator/0.1.68-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.68-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.68-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.68-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.68-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.68-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.68-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63a2f07148ccb74587cecd51
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63a2f06f19c5604966607154
=> operator test-e2e-operator (0.1.68-1)

operators/test-e2e-operator/0.1.73-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.73-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.73-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.73-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.73-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.73-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.73-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63c56d53b95a460990719b57
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63c56d51574549c1c63499bc
=> operator test-e2e-operator (0.1.73-1)

operators/test-e2e-operator/0.1.74-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.74-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.74-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.74-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.74-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.74-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.74-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63c5816aa91746cc452b6085
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63c58168a91746cc452b6080
=> operator test-e2e-operator (0.1.74-1)

operators/test-e2e-operator/0.1.74-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.74-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.74-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.74-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.74-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.74-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.74-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63c5c6e4a91746cc452b6160
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63c5c6e2b95a460990719cc9
=> operator test-e2e-operator (0.1.74-2)

operators/test-e2e-operator/0.1.75-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.75-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.75-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.75-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.75-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.75-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.75-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63c69a3eb95a46099071a54b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63c69a3c574549c1c634a2fb
=> operator test-e2e-operator (0.1.75-1)

operators/test-e2e-operator/0.1.76-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.76-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.76-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.76-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.76-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.76-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.76-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63c69dc9574549c1c634a30a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63c69dc7a91746cc452b6a71
=> operator test-e2e-operator (0.1.76-1)

operators/test-e2e-operator/0.1.77-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.77-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.77-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.77-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.77-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.77-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.77-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63c7fb59574549c1c634b2a9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63c7fb57a91746cc452b7a33
=> operator test-e2e-operator (0.1.77-1)

operators/test-e2e-operator/0.1.79-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.79-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.79-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.79-4/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.79-4/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.79-4/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.79-4**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63c93a3693a5eb200e643c49
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63c93a346bc0785f055cc9c5
=> operator test-e2e-operator (0.1.79-4)

operators/test-e2e-operator/0.1.80-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.80-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.80-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.80-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.80-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.80-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.80-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63cead79158b95ea4807d605
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63cead78158b95ea4807d600
=> operator test-e2e-operator (0.1.80-1)

operators/test-e2e-operator/0.1.81-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.81-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.81-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.81-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.81-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.81-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.81-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63d15689499bb0b91e83430b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63d15687bd200c2943330cc5
=> operator test-e2e-operator (0.1.81-1)

operators/test-e2e-operator/0.1.82-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.82-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.82-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.82-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.82-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.82-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.82-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63d19250bd200c2943330e04
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63d1924f499bb0b91e834473
=> operator test-e2e-operator (0.1.82-2)

operators/test-e2e-operator/0.1.83-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.83-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.83-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.83-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.83-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.83-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.83-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63d389811dea9f0b14d6c80f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63d3897f499bb0b91e835436
=> operator test-e2e-operator (0.1.83-1)

operators/test-e2e-operator/0.1.84-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.84-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.84-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.84-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.84-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.84-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.84-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63d76db11dea9f0b14d6e13a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63d76daf1dea9f0b14d6e109
=> operator test-e2e-operator (0.1.84-1)

operators/test-e2e-operator/0.1.106-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.106-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.106-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.106-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.106-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.106-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.106-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63eb9ca193ac048cedab1942
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63eb9c9f968f81a369f7e36d
=> operator test-e2e-operator (0.1.106-1)

operators/test-e2e-operator/0.1.107-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.107-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.107-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.107-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.107-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.107-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.107-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63ec97f8968f81a369f7e85a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63ec97f6373db64c98f8a3e4
=> operator test-e2e-operator (0.1.107-1)

operators/test-e2e-operator/0.1.109-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.109-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.109-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.109-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.109-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.109-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.109-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63eca481968f81a369f7e8c4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63eca48093ac048cedab1eb4
=> operator test-e2e-operator (0.1.109-1)

operators/test-e2e-operator/0.1.109-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.109-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.109-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.109-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.109-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.109-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.109-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63ecfa76968f81a369f7eb70
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63ecfa7493ac048cedab2153
=> operator test-e2e-operator (0.1.109-3)

operators/test-e2e-operator/0.1.114-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.114-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.114-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.114-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.114-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.114-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.114-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63fdb19c2080d287f7196e86
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63fdb19b2080d287f7196e81
=> operator test-e2e-operator (0.1.114-1)

operators/test-e2e-operator/0.1.110-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.110-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.110-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.110-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.110-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.110-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.110-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63ff2908b0a4327d5b6d770f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63ff2906b0a4327d5b6d770a
=> operator test-e2e-operator (0.1.110-1)

operators/test-e2e-operator/0.1.116-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.116-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.116-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.116-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.116-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.116-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.116-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/63ff2b86d88d67c3cd3d1654
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/63ff2b84d88d67c3cd3d164b
=> operator test-e2e-operator (0.1.116-1)

operators/test-e2e-operator/0.1.1-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64005cd5b0a4327d5b6d7f48
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64005cd3d88d67c3cd3d1ef9
=> operator test-e2e-operator (0.1.1-1)

operators/test-e2e-operator/0.1.117-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.117-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.117-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.117-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.117-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.117-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.117-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6400614271e6e33df067341b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6400614071e6e33df0673416
=> operator test-e2e-operator (0.1.117-1)

operators/test-e2e-operator/0.1.118-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.118-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.118-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.118-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.118-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.118-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.118-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6400cc2ed88d67c3cd3d22c6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6400cc2cb0a4327d5b6d8309
=> operator test-e2e-operator (0.1.118-1)

operators/test-e2e-operator/0.1.119-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.119-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.119-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.119-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.119-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.119-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.119-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/640207e471e6e33df067441b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/640207e3d88d67c3cd3d2fe4
=> operator test-e2e-operator (0.1.119-1)

operators/test-e2e-operator/0.1.120-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.120-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.120-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.120-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.120-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.120-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.120-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6407aa5a797b05a58aafdff2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6407aa5895a2afe3006a7098
=> operator test-e2e-operator (0.1.120-1)

operators/test-e2e-operator/0.1.120-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.120-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.120-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.120-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.120-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.120-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.120-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64083f91797b05a58aafe4b7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64083f8f797b05a58aafe4b2
=> operator test-e2e-operator (0.1.120-2)

operators/test-e2e-operator/0.1.122-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.122-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.122-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.122-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.122-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.122-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.122-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/640b782566d5fbafaf481e9c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/640b7823459884b62331e2da
=> operator test-e2e-operator (0.1.122-1)

operators/test-e2e-operator/0.1.122-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.122-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.122-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.122-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.122-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.122-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.122-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/640b95a766d5fbafaf481f15
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/640b95a666d5fbafaf481f0c
=> operator test-e2e-operator (0.1.122-2)

operators/test-e2e-operator/0.1.122-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.122-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.122-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.122-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.122-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.122-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.122-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/640bbfc0c0fb0ebe3c87a942
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/640bbfbf459884b62331e3af
=> operator test-e2e-operator (0.1.122-3)

operators/test-e2e-operator/0.1.124-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.124-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.124-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.124-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.124-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.124-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.124-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/641db390ca39ea9fee5f555c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/641db38e4079f34ac0d42840
=> operator test-e2e-operator (0.1.124-1)

operators/test-e2e-operator/0.1.125-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.125-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.125-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.125-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.125-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.125-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.125-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64219f4aca39ea9fee5f7dec
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64219f487b069458934c94ab
=> operator test-e2e-operator (0.1.125-1)

operators/test-e2e-operator/0.1.125-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.125-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.125-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.125-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.125-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.125-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.125-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6421ad89ca39ea9fee5f7e57
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6421ad884079f34ac0d44fb1
=> operator test-e2e-operator (0.1.125-2)

operators/test-e2e-operator/0.1.132-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.132-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.132-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.132-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.132-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.132-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.132-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6439524cab54f0b627e7f954
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6439524b33ee344a0970b6a3
=> operator test-e2e-operator (0.1.132-1)

operators/test-e2e-operator/0.1.128-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.128-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.128-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.128-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.128-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.128-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.128-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64395b2733ee344a0970b6e2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64395b2672b57039d7cd856d
=> operator test-e2e-operator (0.1.128-2)

operators/test-e2e-operator/0.1.134-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.134-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.134-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.134-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.134-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.134-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.134-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/643eb46422cc2f0200054901
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/643eb46222cc2f02000548f8
=> operator test-e2e-operator (0.1.134-1)

operators/test-e2e-operator/0.1.135-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.135-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.135-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.135-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.135-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.135-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.135-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/643ec3c31eeec62b550424d4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/643ec3c108705bc59a0048a2
=> operator test-e2e-operator (0.1.135-1)

operators/test-e2e-operator/0.1.136-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.136-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.136-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.136-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.136-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.136-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.136-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6440047a1eeec62b55042d51
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6440047808705bc59a00516c
=> operator test-e2e-operator (0.1.136-1)

operators/test-e2e-operator/0.1.137-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.137-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.137-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.137-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.137-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.137-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.137-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/644020af08705bc59a00522e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/644020ad22cc2f0200055319
=> operator test-e2e-operator (0.1.137-1)

operators/test-e2e-operator/0.1.138-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.138-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.138-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.138-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.138-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.138-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.138-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/644a1d9e972d4662befa9f16
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/644a1d9c972d4662befa9f11
=> operator test-e2e-operator (0.1.138-1)

operators/test-e2e-operator/0.1.139-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.139-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.139-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.139-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.139-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.139-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.139-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/644a43b985fa3aabc9153b49
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/644a43b8ea1dcf43982311c9
=> operator test-e2e-operator (0.1.139-1)

operators/test-e2e-operator/0.1.137-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.137-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.137-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.137-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.137-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.137-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.137-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/644a4cd985fa3aabc9153bd4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/644a4cd7972d4662befaa147
=> operator test-e2e-operator (0.1.137-2)

operators/test-e2e-operator/0.1.134-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.134-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.134-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.134-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.134-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.134-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.134-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/646323b745e6b1d4c73bafd5
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/646323b545e6b1d4c73bafd0
=> operator test-e2e-operator (0.1.134-2)

operators/test-e2e-operator/0.1.144-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.144-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.144-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.144-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.144-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.144-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.144-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6465e8b246d748e7377bda59
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6465e8b0f990856d3674d2c0
=> operator test-e2e-operator (0.1.144-1)

operators/test-e2e-operator/0.1.151-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.151-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.151-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.151-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.151-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.151-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.151-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6479c119cfec682a0d33ab22
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6479c117321d355e31dc1697
=> operator test-e2e-operator (0.1.151-1)

operators/test-e2e-operator/0.1.153-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.153-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.153-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.153-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.153-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.153-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.153-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64877519dd298d02d7a38b1b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64877517dd298d02d7a38b12
=> operator test-e2e-operator (0.1.153-1)

operators/test-e2e-operator/0.1.153-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.153-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.153-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.153-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.153-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.153-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.153-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64878ab899e397c5c2785e6c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64878ab799e397c5c2785e67
=> operator test-e2e-operator (0.1.153-2)

operators/test-e2e-operator/0.1.154-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.154-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.154-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.154-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.154-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.154-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.154-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/649162bb5ccef92a6059727d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/649162b941eb2474a8218304
=> operator test-e2e-operator (0.1.154-1)

operators/test-e2e-operator/0.1.163-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.163-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.163-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.163-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.163-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.163-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.163-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/649c0a5385cc4cd9edfc5a88
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/649c0a519bea82accd2da417
=> operator test-e2e-operator (0.1.163-1)

operators/test-e2e-operator/0.1.164-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.164-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.164-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.164-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.164-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.164-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.164-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64ad6d23315fbbfa7e47728e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64ad6d2148aceb7f1fe11156
=> operator test-e2e-operator (0.1.164-1)

operators/test-e2e-operator/0.1.165-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.165-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.165-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.165-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.165-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.165-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.165-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64b93d2988ed1c56719696c4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64b93d2788ed1c56719696bb
=> operator test-e2e-operator (0.1.165-2)

operators/test-e2e-operator/0.1.166-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.166-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.166-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.166-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.166-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.166-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.166-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64ba4f8c1953f3e8e08a1616
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64ba4f8688ed1c567196a280
=> operator test-e2e-operator (0.1.166-1)

operators/test-e2e-operator/0.1.167-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.167-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.167-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.167-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.167-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.167-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.167-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64ba56d288ed1c567196a313
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64ba56d088ed1c567196a30a
=> operator test-e2e-operator (0.1.167-1)

operators/test-e2e-operator/0.1.168-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.168-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.168-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.168-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.168-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.168-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.168-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64c289c2f3444e4e8cededfc
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64c289c04cf72b50c283f296
=> operator test-e2e-operator (0.1.168-1)

operators/test-e2e-operator/0.1.169-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.169-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.169-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.169-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.169-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.169-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.169-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64c2e0e5f3444e4e8cedef30
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64c2e0e24cf72b50c283f422
=> operator test-e2e-operator (0.1.169-1)

operators/test-e2e-operator/0.1.171-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.171-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.171-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.171-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.171-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.171-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.171-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64c7736b4cf72b50c284218a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64c77369f3444e4e8cee1eef
=> operator test-e2e-operator (0.1.171-2)

operators/test-e2e-operator/0.1.172-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.172-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.172-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.172-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.172-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.172-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.172-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64c94914230d2a7816cbbc86
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64c94912230d2a7816cbbc81
=> operator test-e2e-operator (0.1.172-1)

operators/test-e2e-operator/0.1.173-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.173-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.173-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.173-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.173-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.173-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.173-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64cb5ad725240c9228aef2a9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64cb5ad525240c9228aef2a0
=> operator test-e2e-operator (0.1.173-1)

operators/test-e2e-operator/0.1.176-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.176-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.176-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.176-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.176-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.176-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.176-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64d33f7d8d7dc4c83c2df949
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64d33f7c39abbc1add1006f1
=> operator test-e2e-operator (0.1.176-1)

operators/test-e2e-operator/0.1.178-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.178-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.178-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.178-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.178-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.178-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.178-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64e32c44dc2e9ed99159b466
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64e32c41dc2e9ed99159b45d
=> operator test-e2e-operator (0.1.178-2)

operators/test-e2e-operator/0.1.178-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.178-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.178-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.178-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.178-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.178-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.178-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64e338fcdc2e9ed99159b523
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64e338fa1807837944c28e25
=> operator test-e2e-operator (0.1.178-3)

operators/test-e2e-operator/0.1.1-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64e495476dff709dccecbf1d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64e495446dff709dccecbf14
=> operator test-e2e-operator (0.1.1-2)

operators/test-e2e-operator/0.1.179-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.179-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.179-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.179-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.179-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.179-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.179-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64e4a8a96dff709dccecbfcf
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64e4a8a76dff709dccecbfca
=> operator test-e2e-operator (0.1.179-1)

operators/test-e2e-operator/0.1.181-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.181-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.181-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.181-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.181-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.181-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.181-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64e6227181e63b9a273fb1f5
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64e6226e81e63b9a273fb1ec
=> operator test-e2e-operator (0.1.181-1)

operators/test-e2e-operator/0.1.182-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.182-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.182-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.182-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.182-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.182-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.182-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64e87de11da77c47245fdfa1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64e87ddfed6c5e0ef9d7016f
=> operator test-e2e-operator (0.1.182-1)

operators/test-e2e-operator/0.1.183-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.183-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.183-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.183-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.183-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.183-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.183-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64e888671da77c47245fe02a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64e888651da77c47245fe021
=> operator test-e2e-operator (0.1.183-1)

operators/test-e2e-operator/0.1.184-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.184-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.184-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.184-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.184-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.184-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.184-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64ec47c0ed6c5e0ef9d71673
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64ec47be1da77c47245ff3b8
=> operator test-e2e-operator (0.1.184-1)

operators/test-e2e-operator/0.1.185-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.185-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.185-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.185-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.185-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.185-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.185-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64ee2c1a304f46c24ffb6956
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64ee2c17a158bd44fdee868d
=> operator test-e2e-operator (0.1.185-1)

operators/test-e2e-operator/0.1.193-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.193-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.193-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.193-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.193-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.193-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.193-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64f776d950b6240c3998cc31
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64f776d61ef7de81afb2172d
=> operator test-e2e-operator (0.1.193-1)

operators/test-e2e-operator/0.1.194-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.194-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.194-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.194-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.194-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.194-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.194-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64f829b81ef7de81afb21f5f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64f829b650b6240c3998d4b3
=> operator test-e2e-operator (0.1.194-1)

operators/test-e2e-operator/0.1.196-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.196-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.196-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.196-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.196-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.196-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.196-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64fa2f83e00a7a6eb036a002
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64fa2f80e00a7a6eb0369ffd
=> operator test-e2e-operator (0.1.196-1)

operators/test-e2e-operator/0.1.197-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.197-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.197-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.197-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.197-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.197-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.197-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/64fae56de00a7a6eb036a8d0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/64fae56be00a7a6eb036a8c7
=> operator test-e2e-operator (0.1.197-1)

operators/test-e2e-operator/0.1.198-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.198-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.198-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.198-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.198-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.198-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.198-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65017bd5b3b65ffa89b77470
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65017bd3b3b65ffa89b7746b
=> operator test-e2e-operator (0.1.198-1)

operators/test-e2e-operator/0.1.199-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.199-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.199-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.199-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.199-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.199-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.199-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6501cf6bb3b65ffa89b77749
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6501cf68b3b65ffa89b77744
=> operator test-e2e-operator (0.1.199-2)

operators/test-e2e-operator/0.1.200-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.200-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.200-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.200-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.200-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.200-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.200-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6502f59b792a58fe088d88d9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6502f59a8992f829a89ef0c2
=> operator test-e2e-operator (0.1.200-2)

operators/test-e2e-operator/0.1.201-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.201-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.201-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.201-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.201-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.201-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.201-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/650322388992f829a89ef15d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65032235792a58fe088d897e
=> operator test-e2e-operator (0.1.201-1)

operators/test-e2e-operator/0.1.202-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.202-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.202-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.202-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.202-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.202-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.202-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/650436ea792a58fe088d9ac1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/650436e88992f829a89f0379
=> operator test-e2e-operator (0.1.202-1)

operators/test-e2e-operator/0.1.203-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.203-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.203-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.203-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.203-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.203-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.203-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/650829e6792a58fe088dcfb1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/650829e48992f829a89f3976
=> operator test-e2e-operator (0.1.203-1)

operators/test-e2e-operator/0.1.205-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.205-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.205-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.205-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.205-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.205-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.205-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/650d7643079d864917b343ce
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/650d7641079d864917b343c5
=> operator test-e2e-operator (0.1.205-1)

operators/test-e2e-operator/0.1.206-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.206-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.206-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.206-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.206-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.206-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.206-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65128c07044e60292068d67b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65128c04940a02bf6dc140bb
=> operator test-e2e-operator (0.1.206-1)

operators/test-e2e-operator/0.1.207-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.207-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.207-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.207-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.207-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.207-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.207-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65132c5f940a02bf6dc146d0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65132c5c940a02bf6dc146cb
=> operator test-e2e-operator (0.1.207-1)

operators/test-e2e-operator/0.1.208-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.208-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.208-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.208-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.208-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.208-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.208-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6513d27a044e60292068e49b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6513d278940a02bf6dc14e52
=> operator test-e2e-operator (0.1.208-1)

operators/test-e2e-operator/0.1.209-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.209-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.209-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.209-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.209-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.209-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.209-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6513e89e940a02bf6dc1529a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6513e89d940a02bf6dc15291
=> operator test-e2e-operator (0.1.209-1)

operators/test-e2e-operator/0.1.210-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.210-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.210-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.210-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.210-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.210-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.210-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65167df9044e60292069042b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65167df8940a02bf6dc16e1c
=> operator test-e2e-operator (0.1.210-1)

operators/test-e2e-operator/0.1.214-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.214-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.214-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.214-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.214-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.214-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.214-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/651beab727568458ec2e4bc9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/651beab5ee76fad04218094d
=> operator test-e2e-operator (0.1.214-1)

operators/test-e2e-operator/0.1.215-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.215-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.215-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.215-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.215-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.215-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.215-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/651f12a0921d480edd07505a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/651f129e921d480edd075051
=> operator test-e2e-operator (0.1.215-1)

operators/test-e2e-operator/0.1.216-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.216-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.216-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.216-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.216-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.216-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.216-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/652413b1921d480edd0779cd
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/652413af921d480edd0779c8
=> operator test-e2e-operator (0.1.216-1)

operators/test-e2e-operator/0.1.219-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.219-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.219-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.219-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.219-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.219-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.219-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65253053b30d911a0a676cc3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65253051b30d911a0a676cbe
=> operator test-e2e-operator (0.1.219-1)

operators/test-e2e-operator/0.1.222-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.222-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.222-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.222-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.222-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.222-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.222-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6526b425dc07a7d20ee4b5d0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6526b422dc07a7d20ee4b5c7
=> operator test-e2e-operator (0.1.222-1)

operators/test-e2e-operator/0.1.223-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.223-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.223-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.223-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.223-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.223-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.223-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65292abad62e5dec6abd52f8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65292ab798a3d760b6cf89ca
=> operator test-e2e-operator (0.1.223-1)

operators/test-e2e-operator/0.1.224-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.224-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.224-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.224-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.224-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.224-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.224-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6529390d98a3d760b6cf8a3c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6529390b98a3d760b6cf8a37
=> operator test-e2e-operator (0.1.224-2)

operators/test-e2e-operator/0.1.235-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.235-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.235-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.235-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.235-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.235-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.235-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/652cf68d98a3d760b6cfa460
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/652cf68b98a3d760b6cfa457
=> operator test-e2e-operator (0.1.235-1)

operators/test-e2e-operator/0.1.239-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.239-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.239-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.239-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.239-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.239-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.239-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/652d01a798a3d760b6cfa4ef
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/652d01a5d62e5dec6abd6d83
=> operator test-e2e-operator (0.1.239-1)

operators/test-e2e-operator/0.1.240-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.240-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.240-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.240-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.240-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.240-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.240-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/652d070698a3d760b6cfa524
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/652d0704d62e5dec6abd6dd2
=> operator test-e2e-operator (0.1.240-1)

operators/test-e2e-operator/0.1.250-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.250-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.250-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.250-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.250-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.250-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.250-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/652e73db1bac01987f177ffc
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/652e73d91bac01987f177ff7
=> operator test-e2e-operator (0.1.250-1)

operators/test-e2e-operator/0.1.252-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.252-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.252-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.252-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.252-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.252-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.252-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/652e89361bac01987f1780b5
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/652e8933b8228287e68b8edf
=> operator test-e2e-operator (0.1.252-1)

operators/test-e2e-operator/0.1.253-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.253-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.253-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.253-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.253-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.253-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.253-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/652e9f0ab8228287e68b91f7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/652e9f081bac01987f1783f3
=> operator test-e2e-operator (0.1.253-1)

operators/test-e2e-operator/0.1.254-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.254-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.254-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.254-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.254-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.254-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.254-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/652ea3c31bac01987f17841c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/652ea3c11bac01987f178413
=> operator test-e2e-operator (0.1.254-1)

operators/test-e2e-operator/0.1.255-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.255-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.255-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.255-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.255-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.255-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.255-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/652ea93bb8228287e68b92aa
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/652ea9391bac01987f17844c
=> operator test-e2e-operator (0.1.255-1)

operators/test-e2e-operator/0.1.256-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.256-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.256-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.256-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.256-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.256-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.256-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/652fb6ea1bac01987f178f6c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/652fb6e81bac01987f178f67
=> operator test-e2e-operator (0.1.256-1)

operators/test-e2e-operator/0.1.256-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.256-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.256-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.256-4/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.256-4/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.256-4/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.256-4**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/652fc545b8228287e68b9fdd
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/652fc543b8228287e68b9fd8
=> operator test-e2e-operator (0.1.256-4)

operators/test-e2e-operator/0.1.258-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.258-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.258-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.258-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.258-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.258-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.258-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/652ff91fb8228287e68ba27f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/652ff91e1bac01987f179355
=> operator test-e2e-operator (0.1.258-1)

operators/test-e2e-operator/0.1.258-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.258-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.258-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.258-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.258-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.258-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.258-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65300c451bac01987f1793c7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65300c42b8228287e68ba2fa
=> operator test-e2e-operator (0.1.258-2)

operators/test-e2e-operator/0.1.259-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.259-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.259-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.259-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.259-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.259-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.259-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6530f9301bac01987f1799e4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6530f92db8228287e68ba8dd
=> operator test-e2e-operator (0.1.259-1)

operators/test-e2e-operator/0.1.260-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.260-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.260-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.260-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.260-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.260-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.260-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6530fe7eb8228287e68ba90d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6530fe7d1bac01987f179a28
=> operator test-e2e-operator (0.1.260-1)

operators/test-e2e-operator/0.0.8/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.0.8/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.0.8/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.0.8/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.0.8/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.0.8/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
=> operator test-e2e-operator (0.1.266-2)

operators/test-e2e-community-operator/0.0.8/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.0.8/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.0.8/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.0.8/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.0.8/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.0.8/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.268-1)

operators/test-e2e-operator/0.1.270-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.270-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.270-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.270-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.270-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.270-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.270-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6532482bb8228287e68bb4e3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/653248281bac01987f17a5f7
=> operator test-e2e-operator (0.1.270-1)

operators/test-e2e-community-operator/0.1.270-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.270-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.270-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.270-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.270-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.270-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.270-1)

operators/test-e2e-operator/0.1.273-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.273-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.273-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.273-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.273-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.273-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.273-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65326fe41bac01987f17a8c6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65326fe21bac01987f17a8c1
=> operator test-e2e-operator (0.1.273-1)

operators/test-e2e-community-operator/0.1.273-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.273-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.273-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.273-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.273-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.273-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.273-1)

operators/test-e2e-operator/0.1.274-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.274-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.274-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.274-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.274-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.274-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.274-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65328712b8228287e68bb8a9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6532870fb8228287e68bb8a0
=> operator test-e2e-operator (0.1.274-1)

operators/test-e2e-community-operator/0.1.274-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.274-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.274-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.274-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.274-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.274-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.274-1)

operators/test-e2e-operator/0.1.275-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.275-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.275-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.275-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.275-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.275-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.275-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65363925b8228287e68bd4bc
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/653639231bac01987f17c726
=> operator test-e2e-operator (0.1.275-1)

operators/test-e2e-community-operator/0.1.275-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.275-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.275-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.275-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.275-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.275-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.275-1)

operators/test-e2e-operator/0.1.278-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.278-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.278-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.278-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.278-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.278-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.278-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/653690d9b8228287e68be8fd
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/653690d71bac01987f17dc23
=> operator test-e2e-operator (0.1.278-1)

operators/test-e2e-operator/0.1.280-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.280-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.280-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.280-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.280-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.280-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.280-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6536ae971bac01987f17dcbd
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6536ae95b8228287e68be9bf
=> operator test-e2e-operator (0.1.280-1)

operators/test-e2e-operator/0.1.282-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.282-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.282-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.282-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.282-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.282-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.282-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6536b4ef21a8c0f54afeea17
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6536b4ec21a8c0f54afeea0e
=> operator test-e2e-operator (0.1.282-1)

operators/test-e2e-operator/0.1.282-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.282-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.282-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.282-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.282-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.282-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.282-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65377c3b14ec135b3f8f8822
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65377c3821a8c0f54afef0e8
=> operator test-e2e-operator (0.1.282-2)

operators/test-e2e-operator/0.1.283-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.283-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.283-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.283-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.283-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.283-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.283-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/653784812d372953d10286fe
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6537847f2d372953d10286f9
=> operator test-e2e-operator (0.1.283-1)

operators/test-e2e-operator/0.1.284-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.284-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.284-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.284-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.284-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.284-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.284-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65378b3b14ec135b3f8f93af
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65378b3721a8c0f54afefc85
=> operator test-e2e-operator (0.1.284-1)

operators/test-e2e-operator/0.1.284-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.284-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.284-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.284-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.284-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.284-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.284-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65378e0721a8c0f54afefee1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65378e0521a8c0f54afefedc
=> operator test-e2e-operator (0.1.284-2)

operators/test-e2e-operator/0.1.284-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.284-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.284-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.284-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.284-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.284-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.284-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/653790d021a8c0f54afeff40
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/653790cd21a8c0f54afeff3b
=> operator test-e2e-operator (0.1.284-3)

operators/test-e2e-operator/0.1.285-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.285-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.285-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.285-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.285-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.285-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.285-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/653795a921a8c0f54aff01d0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/653795a614ec135b3f8f9964
=> operator test-e2e-operator (0.1.285-1)

operators/test-e2e-community-operator/0.1.285-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.285-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.285-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.285-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.285-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.285-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.285-2)

operators/test-e2e-operator/0.1.286-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.286-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.286-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.286-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.286-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.286-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.286-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65379d7a14ec135b3f8f9a36
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65379d7821a8c0f54aff02d4
=> operator test-e2e-operator (0.1.286-1)

operators/test-e2e-operator/0.1.289-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.289-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.289-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.289-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.289-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.289-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.289-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6537a6d121a8c0f54aff0cf2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6537a6cf21a8c0f54aff0ced
=> operator test-e2e-operator (0.1.289-1)

operators/test-e2e-operator/0.1.293-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.293-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.293-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.293-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.293-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.293-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.293-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6537f36814ec135b3f8fb23d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6537f36614ec135b3f8fb238
=> operator test-e2e-operator (0.1.293-1)

operators/test-e2e-community-operator/0.1.294-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.294-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.294-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.294-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.294-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.294-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.294-1)

operators/test-e2e-community-operator/0.1.294-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.294-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.294-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.294-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.294-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.294-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.294-2)

operators/test-e2e-operator/0.1.295-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.295-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.295-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.295-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.295-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.295-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.295-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6538cdd914ec135b3f8fbc98
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6538cdd814ec135b3f8fbc8f
=> operator test-e2e-operator (0.1.295-1)

operators/test-e2e-operator/0.1.295-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.295-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.295-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.295-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.295-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.295-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.295-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6538fc1a21a8c0f54aff3629
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6538fc1821a8c0f54aff3624
=> operator test-e2e-operator (0.1.295-2)

operators/test-e2e-operator/0.1.298-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.298-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.298-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.298-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.298-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.298-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.298-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65390e1a21a8c0f54aff3705
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65390e1821a8c0f54aff36fc
=> operator test-e2e-operator (0.1.298-1)

operators/test-e2e-operator/0.1.300-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.300-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.300-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.300-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.300-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.300-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.300-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65391aac21a8c0f54aff3786
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65391aaa21a8c0f54aff377d
=> operator test-e2e-operator (0.1.300-1)

operators/test-e2e-operator/0.1.301-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.301-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.301-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.301-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.301-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.301-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.301-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/653920e221a8c0f54aff37bb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/653920e014ec135b3f8fced4
=> operator test-e2e-operator (0.1.301-1)

operators/test-e2e-operator/0.1.302-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.302-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.302-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.302-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.302-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.302-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.302-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6539286214ec135b3f8fcf27
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6539286021a8c0f54aff3804
=> operator test-e2e-operator (0.1.302-1)

operators/test-e2e-operator/0.1.302-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.302-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.302-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.302-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.302-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.302-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.302-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/653930fc14ec135b3f8fcf5e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/653930fa21a8c0f54aff385d
=> operator test-e2e-operator (0.1.302-2)

operators/test-e2e-community-operator/0.1.302-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.302-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.302-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.302-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.302-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.302-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.302-2)

operators/test-e2e-operator/0.1.303-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.303-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.303-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.303-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.303-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.303-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.303-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/653940b721a8c0f54aff38d4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/653940b614ec135b3f8fcfc7
=> operator test-e2e-operator (0.1.303-1)

operators/test-e2e-operator/0.1.304-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.304-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.304-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.304-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.304-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.304-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.304-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6539461014ec135b3f8fcfe7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6539460d21a8c0f54aff3904
=> operator test-e2e-operator (0.1.304-1)

operators/test-e2e-community-operator/0.1.304-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.304-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.304-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.304-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.304-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.304-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.304-1)

operators/test-e2e-community-operator/0.1.304-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.304-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.304-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.304-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.304-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.304-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.304-2)

operators/test-e2e-operator/0.1.304-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.304-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.304-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.304-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.304-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.304-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.304-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/653a0b34c19532c442f214c2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/653a0b32c19532c442f214b9
=> operator test-e2e-operator (0.1.304-2)

operators/test-e2e-operator/0.1.305-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.305-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.305-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.305-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.305-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.305-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.305-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/653a31fa57ec9bc2ed1eb578
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/653a31f857ec9bc2ed1eb573
=> operator test-e2e-operator (0.1.305-1)

operators/test-e2e-community-operator/0.1.305-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.305-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.305-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.305-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.305-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.305-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.305-1)

operators/test-e2e-community-operator/0.1.307-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.307-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.307-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.307-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.307-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.307-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.307-1)

operators/test-e2e-community-operator/0.1.308-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.308-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.308-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.308-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.308-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.308-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.308-1)

operators/test-e2e-community-operator/0.1.309-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.309-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.309-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.309-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.309-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.309-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.309-1)

operators/test-e2e-operator/0.1.309-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.309-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.309-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.309-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.309-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.309-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.309-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/653a61fcc19532c442f21afd
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/653a61fbc19532c442f21af4
=> operator test-e2e-operator (0.1.309-2)

operators/test-e2e-operator/0.1.309-9871/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.309-9871/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.309-9871/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.309-9871/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.309-9871/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.309-9871/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.309-9871**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/653b99b957ec9bc2ed1ec36b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/653b99b757ec9bc2ed1ec366
=> operator test-e2e-operator (0.1.309-9871)

operators/test-e2e-community-operator/0.1.310-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.310-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.310-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.310-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.310-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.310-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.310-1)

operators/test-e2e-community-operator/0.1.310-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.310-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.310-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.310-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.310-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.310-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.310-2)

operators/test-e2e-community-operator/0.1.310-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.310-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.310-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.310-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.310-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.310-3/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.310-3)

operators/test-e2e-community-operator/0.1.310-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.310-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.310-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.310-4/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.310-4/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.310-4/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.310-4)

operators/test-e2e-community-operator/0.1.310-5/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.310-5/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.310-5/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.310-5/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.310-5/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.310-5/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.310-5)

operators/test-e2e-operator/0.1.309-22905/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.309-22905/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.309-22905/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.309-22905/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.309-22905/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.309-22905/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.309-22905**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/654112bfc19532c442f269b3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/654112bcc19532c442f269ae
=> operator test-e2e-operator (0.1.309-22905)

operators/test-e2e-operator/0.1.311-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.311-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.311-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.311-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.311-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.311-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.311-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65411cf36d4bd915050d2ed3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65411cf16d4bd915050d2ece
=> operator test-e2e-operator (0.1.311-1)

operators/test-e2e-community-operator/0.1.311-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.311-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.311-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.311-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.311-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.311-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.311-1)

operators/test-e2e-operator/0.1.312-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.312-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.312-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.312-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.312-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.312-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.312-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65426a7126ff1c158fcfbf8f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65426a7089cc3a4aa5aec19e
=> operator test-e2e-operator (0.1.312-1)

operators/test-e2e-community-operator/0.1.312-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.312-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.312-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.312-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.312-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.312-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.312-1)

operators/test-e2e-operator/0.1.313-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.313-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.313-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.313-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.313-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.313-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.313-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/654359b626ff1c158fcfc762
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/654359b526ff1c158fcfc759
=> operator test-e2e-operator (0.1.313-1)

operators/test-e2e-community-operator/0.1.313-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.313-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.313-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.313-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.313-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.313-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.313-1)

operators/test-e2e-operator/0.1.313-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.313-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.313-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.313-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.313-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.313-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.313-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6543936526ff1c158fcfcb0d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6543936289cc3a4aa5aecc16
=> operator test-e2e-operator (0.1.313-2)

operators/test-e2e-community-operator/0.1.313-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.313-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.313-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.313-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.313-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.313-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.313-2)

operators/test-e2e-community-operator/0.1.314-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.314-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.314-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.314-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.314-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.314-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.314-1)

operators/test-e2e-community-operator/0.1.315-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.315-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.315-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.315-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.315-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.315-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.315-1)

operators/test-e2e-community-operator/0.1.316-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.316-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.316-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.316-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.316-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.316-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.316-1)

operators/test-e2e-community-operator/0.1.317-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.317-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.317-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.317-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.317-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.317-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.317-1)

operators/test-e2e-community-operator/0.1.318-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.318-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.318-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.318-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.318-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.318-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.318-1)

operators/test-e2e-community-operator/0.1.319-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.319-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.319-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.319-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.319-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.319-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.319-1)

operators/test-e2e-operator/0.1.313-21306/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.313-21306/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.313-21306/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.313-21306/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.313-21306/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.313-21306/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.313-21306**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/654bbe1389cc3a4aa5af18cc
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/654bbe11fbb458d9b0ec5052
=> operator test-e2e-operator (0.1.313-21306)

operators/test-e2e-community-operator/0.1.320-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.320-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.320-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.320-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.320-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.320-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.320-1)

operators/test-e2e-community-operator/0.1.322-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.322-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.322-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.322-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.322-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.322-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.322-1)

operators/test-e2e-operator/0.1.323-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.323-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.323-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.323-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.323-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.323-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.323-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/654e08cafbb458d9b0ec6653
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/654e08c989cc3a4aa5af2e88
=> operator test-e2e-operator (0.1.323-1)

operators/test-e2e-community-operator/0.1.323-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.323-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.323-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.323-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.323-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.323-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.323-1)

operators/test-e2e-community-operator/0.1.324-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.324-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.324-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.324-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.324-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.324-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.324-1)

operators/test-e2e-operator/0.1.325-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.325-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.325-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.325-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.325-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.325-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.325-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/655c988dec661feff73f3a27
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/655c988b28b306a34cc4dcbd
=> operator test-e2e-operator (0.1.325-1)

operators/test-e2e-community-operator/0.1.325-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.325-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.325-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.325-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.325-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.325-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.325-1)

operators/test-e2e-operator/0.1.326-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.326-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.326-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.326-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.326-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.326-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.326-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/655e00e7ec661feff73f471a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/655e00e5ec661feff73f4711
=> operator test-e2e-operator (0.1.326-1)

operators/test-e2e-community-operator/0.1.326-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.326-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.326-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.326-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.326-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.326-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.326-1)

operators/test-e2e-community-operator/0.1.327-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.327-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.327-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.327-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.327-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.327-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.327-1)

operators/test-e2e-operator/0.1.327-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.327-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.327-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.327-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.327-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.327-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.327-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6560961928b306a34cc50791
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6560961728b306a34cc5078c
=> operator test-e2e-operator (0.1.327-1)

operators/test-e2e-operator/0.1.330-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.330-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.330-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.330-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.330-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.330-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.330-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6565bda3b70890eb8b66da99
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6565bda1b70890eb8b66da94
=> operator test-e2e-operator (0.1.330-1)

operators/test-e2e-community-operator/0.1.330-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.330-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.330-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.330-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.330-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.330-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.330-1)

operators/test-e2e-community-operator/0.1.331-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.331-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.331-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.331-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.331-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.331-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.331-1)

operators/test-e2e-operator/0.1.331-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.331-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.331-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.331-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.331-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.331-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.331-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65677126b70890eb8b66f382
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65677124e8542ad288670f5d
=> operator test-e2e-operator (0.1.331-1)

operators/test-e2e-operator/0.1.332-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.332-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.332-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.332-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.332-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.332-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.332-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6569a99203c29356c054635a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6569a990d65a14850fd75b4c
=> operator test-e2e-operator (0.1.332-1)

operators/test-e2e-community-operator/0.1.332-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.332-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.332-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.332-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.332-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.332-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.332-1)

operators/test-e2e-operator/0.1.333-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.333-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.333-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.333-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.333-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.333-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.333-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6569ac7f03c29356c0546394
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6569ac7c03c29356c054638b
=> operator test-e2e-operator (0.1.333-1)

operators/test-e2e-community-operator/0.1.333-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.333-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.333-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.333-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.333-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.333-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.333-1)

operators/test-e2e-community-operator/0.1.334-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.334-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.334-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.334-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.334-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.334-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.334-1)

operators/test-e2e-operator/0.1.334-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.334-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.334-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.334-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.334-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.334-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.334-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6569c6abd65a14850fd75d51
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6569c6a803c29356c0546556
=> operator test-e2e-operator (0.1.334-1)

operators/test-e2e-operator/0.1.335-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.335-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.335-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.335-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.335-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.335-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.335-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6569d04e03c29356c0546601
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6569d04cd65a14850fd75db6
=> operator test-e2e-operator (0.1.335-1)

operators/test-e2e-community-operator/0.1.335-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.335-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.335-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.335-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.335-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.335-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.335-1)

operators/test-e2e-community-operator/0.1.336-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.336-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.336-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.336-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.336-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.336-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.336-1)

operators/test-e2e-community-operator/0.1.337-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.337-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.337-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.337-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.337-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.337-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.337-1)

operators/test-e2e-operator/0.1.338-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.338-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.338-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.338-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.338-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.338-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.338-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/657885346be5fb88bed230ae
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6578853229dd4014d614bb41
=> operator test-e2e-operator (0.1.338-1)

operators/test-e2e-community-operator/0.1.338-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.338-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.338-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.338-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.338-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.338-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.338-1)

operators/test-e2e-operator/0.1.339-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.339-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.339-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.339-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.339-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.339-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.339-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/657c163618a3c46d47614f57
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/657c16337fbadd06e8656940
=> operator test-e2e-operator (0.1.339-1)

operators/test-e2e-community-operator/0.1.339-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.339-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.339-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.339-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.339-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.339-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.339-1)

operators/test-e2e-operator/0.1.339-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.339-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.339-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.339-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.339-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.339-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.339-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/657c249618a3c46d47615056
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/657c249418a3c46d4761504d
=> operator test-e2e-operator (0.1.339-2)

operators/test-e2e-community-operator/0.1.339-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.339-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.339-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.339-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.339-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.339-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.339-2)

operators/test-e2e-operator/0.1.339-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.339-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.339-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.339-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.339-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.339-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.339-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/657c2b6818a3c46d47615107
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/657c2b667fbadd06e8656ade
=> operator test-e2e-operator (0.1.339-3)

operators/test-e2e-community-operator/0.1.339-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.339-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.339-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.339-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.339-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.339-3/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.339-3)

operators/test-e2e-operator/0.1.340-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.340-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.340-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.340-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.340-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.340-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.340-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/657c6c287fbadd06e8656c95
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/657c6c267fbadd06e8656c8c
=> operator test-e2e-operator (0.1.340-1)

operators/test-e2e-community-operator/0.1.340-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.340-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.340-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.340-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.340-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.340-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.340-1)

operators/test-e2e-operator/0.1.341-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.341-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.341-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.341-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.341-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.341-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.341-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65806ab318a3c46d47616e4d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65806ab17fbadd06e8658931
=> operator test-e2e-operator (0.1.341-1)

operators/test-e2e-community-operator/0.1.341-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.341-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.341-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.341-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.341-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.341-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.341-1)

operators/test-e2e-operator/0.1.342-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.342-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.342-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.342-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.342-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.342-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.342-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6582b8147fbadd06e865990c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6582b81018a3c46d47617d75
=> operator test-e2e-operator (0.1.342-1)

operators/test-e2e-community-operator/0.1.342-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.342-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.342-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.342-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.342-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.342-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.342-1)

operators/test-e2e-community-operator/0.1.343-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.343-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.343-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.343-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.343-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.343-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.343-1)

operators/test-e2e-community-operator/0.1.344-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.344-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.344-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.344-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.344-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.344-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.344-1)

operators/test-e2e-operator/0.1.345-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.345-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.345-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.345-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.345-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.345-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.345-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65a00827459ceaaeece9c483
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65a00825459ceaaeece9c47e
=> operator test-e2e-operator (0.1.345-1)

operators/test-e2e-community-operator/0.1.345-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.345-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.345-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.345-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.345-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.345-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.345-2)

operators/test-e2e-operator/0.1.346-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.346-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.346-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.346-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.346-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.346-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.346-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65a5012a0dfbffba495d978d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65a501270dfbffba495d9784
=> operator test-e2e-operator (0.1.346-1)

operators/test-e2e-operator/0.1.347-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.347-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.347-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.347-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.347-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.347-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.347-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65a52419202656d09ab5547e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65a52417202656d09ab55479
=> operator test-e2e-operator (0.1.347-1)

operators/test-e2e-community-operator/0.1.347-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.347-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.347-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.347-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.347-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.347-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.347-1)

operators/test-e2e-operator/0.1.348-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.348-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.348-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.348-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.348-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.348-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.348-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65a6952b99edd6d3c20f62b0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65a6952999edd6d3c20f62a7
=> operator test-e2e-operator (0.1.348-1)

operators/test-e2e-community-operator/0.1.348-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.348-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.348-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.348-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.348-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.348-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.348-1)

operators/test-e2e-community-operator/0.1.348-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.348-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.348-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.348-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.348-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.348-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.348-2)

operators/test-e2e-operator/0.1.349-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.349-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.349-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.349-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.349-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.349-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.349-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65a9226cd7c11715e006281d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65a9226ad7c11715e0062810
=> operator test-e2e-operator (0.1.349-1)

operators/test-e2e-community-operator/0.1.349-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.349-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.349-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.349-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.349-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.349-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.349-1)

operators/test-e2e-operator/0.1.350-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.350-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.350-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.350-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.350-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.350-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.350-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65ae2c14d7c11715e0064e83
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65ae2c1253275522df171b0e
=> operator test-e2e-operator (0.1.350-1)

operators/test-e2e-community-operator/0.1.350-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.350-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.350-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.350-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.350-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.350-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.350-1)

operators/test-e2e-operator/0.1.350-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.350-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.350-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.350-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.350-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.350-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.350-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65ae4683d7c11715e0065068
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65ae4681d7c11715e006505f
=> operator test-e2e-operator (0.1.350-2)

operators/test-e2e-community-operator/0.1.350-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.350-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.350-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.350-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.350-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.350-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.350-2)

operators/test-e2e-operator/0.1.352-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.352-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.352-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.352-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.352-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.352-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.352-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65ae805453275522df171e29
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65ae805153275522df171e24
=> operator test-e2e-operator (0.1.352-1)

operators/test-e2e-community-operator/0.1.352-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.352-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.352-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.352-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.352-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.352-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.352-1)

operators/test-e2e-operator/0.1.353-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.353-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.353-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.353-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.353-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.353-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.353-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65b033ca003dd7b267eb485d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65b033c74d53b6303a4ced30
=> operator test-e2e-operator (0.1.353-1)

operators/test-e2e-community-operator/0.1.353-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.353-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.353-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.353-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.353-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.353-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.353-1)

operators/test-e2e-operator/0.1.353-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.353-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.353-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.353-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.353-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.353-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.353-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65b11f9c4d53b6303a4cf6d1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65b11f9a4d53b6303a4cf6c8
=> operator test-e2e-operator (0.1.353-2)

operators/test-e2e-operator/0.1.353-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.353-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.353-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.353-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.353-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.353-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.353-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65b128f5003dd7b267eb5393
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65b128f34d53b6303a4cf733
=> operator test-e2e-operator (0.1.353-3)

operators/test-e2e-community-operator/0.1.354-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.354-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.354-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.354-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.354-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.354-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.354-1)

operators/test-e2e-operator/0.1.355-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.355-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.355-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.355-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.355-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.355-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.355-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65b3b530003dd7b267eb6cfa
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65b3b52d003dd7b267eb6cf5
=> operator test-e2e-operator (0.1.355-1)

operators/test-e2e-operator/0.1.356-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.356-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.356-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.356-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.356-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.356-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.356-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65b784c6003dd7b267eb89b6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65b784c34d53b6303a4d2edc
=> operator test-e2e-operator (0.1.356-1)

operators/test-e2e-operator/0.1.357-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.357-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.357-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.357-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.357-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.357-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.357-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65b8bed7a8518fa04db01c93
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65b8bed3038d747ad4d0d9ee
=> operator test-e2e-operator (0.1.357-1)

operators/test-e2e-community-operator/0.1.357-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.357-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.357-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.357-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.357-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.357-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.357-1)

operators/test-e2e-operator/0.1.358-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.358-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.358-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.358-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.358-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.358-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.358-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65ba3ad8038d747ad4d102a8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65ba3ad5a8518fa04db04638
=> operator test-e2e-operator (0.1.358-1)

operators/test-e2e-community-operator/0.1.358-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.358-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.358-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.358-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.358-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.358-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.358-1)

operators/test-e2e-operator/0.1.359-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.359-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.359-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.359-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.359-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.359-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.359-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65bb538f825ce70038b38994
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65bb538d2bedc5e3dccaa5bc
=> operator test-e2e-operator (0.1.359-1)

operators/test-e2e-community-operator/0.1.359-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.359-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.359-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.359-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.359-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.359-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.359-1)

operators/test-e2e-operator/0.1.360-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.360-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.360-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.360-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.360-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.360-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.360-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65bcbe302bedc5e3dccab341
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65bcbe2e825ce70038b396e6
=> operator test-e2e-operator (0.1.360-1)

operators/test-e2e-community-operator/0.1.360-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.360-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.360-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.360-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.360-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.360-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.360-1)

operators/test-e2e-operator/0.1.361-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.361-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.361-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.361-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.361-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.361-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.361-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65bd16ad2bedc5e3dccab66f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65bd16ab825ce70038b39a19
=> operator test-e2e-operator (0.1.361-1)

operators/test-e2e-community-operator/0.1.361-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.361-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.361-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.361-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.361-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.361-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.361-1)

operators/test-e2e-operator/0.1.361-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.361-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.361-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.361-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.361-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.361-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.361-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65c0d1322bedc5e3dccad2ea
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65c0d130825ce70038b3b703
=> operator test-e2e-operator (0.1.361-2)

operators/test-e2e-community-operator/0.1.362-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.362-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.362-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.362-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.362-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.362-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.362-1)

operators/test-e2e-operator/0.1.363-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.363-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.363-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.363-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.363-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.363-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.363-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65c63f2bc069f2804c0a0940
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65c63f28c069f2804c0a0937
=> operator test-e2e-operator (0.1.363-1)

operators/test-e2e-operator/0.1.363-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.363-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.363-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.363-4/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.363-4/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.363-4/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.363-4**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65ca38e4c069f2804c0a30ba
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65ca38e2adc0e5b47567ec1a
=> operator test-e2e-operator (0.1.363-4)

operators/test-e2e-community-operator/0.1.363-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.363-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.363-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.363-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.363-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.363-3/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.363-3)

operators/test-e2e-operator/0.1.364-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.364-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.364-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.364-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.364-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.364-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.364-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65cdceb57d415275b589aa37
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65cdceb296d6e42c321cff3b
=> operator test-e2e-operator (0.1.364-1)

operators/test-e2e-community-operator/0.1.364-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.364-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.364-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.364-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.364-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.364-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.364-1)

operators/test-e2e-community-operator/0.1.365-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.365-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.365-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.365-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.365-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.365-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.365-1)

operators/test-e2e-operator/0.1.365-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.365-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.365-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.365-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.365-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.365-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.365-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65cdecd87d415275b589abb3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65cdecd67d415275b589abaa
=> operator test-e2e-operator (0.1.365-2)

operators/test-e2e-operator/0.1.366-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.366-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.366-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.366-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.366-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.366-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.366-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65cf2ddc7d415275b589b2e1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65cf2dd97d415275b589b2dc
=> operator test-e2e-operator (0.1.366-1)

operators/test-e2e-community-operator/0.1.366-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.366-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.366-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.366-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.366-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.366-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.366-1)

operators/test-e2e-operator/0.1.367-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.367-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.367-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.367-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.367-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.367-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.367-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65d4681ec3c7419b1155acaf
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65d4681b483504eac00712be
=> operator test-e2e-operator (0.1.367-1)

operators/test-e2e-community-operator/0.1.367-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.367-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.367-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.367-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.367-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.367-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.367-2)

operators/test-e2e-community-operator/0.1.367-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.367-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.367-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.367-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.367-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.367-3/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.367-3)

operators/test-e2e-operator/0.1.368-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.368-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.368-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.368-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.368-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.368-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.368-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65d5c4313bec5bfd2ba53be7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65d5c42e9c625c5a657de786
=> operator test-e2e-operator (0.1.368-1)

operators/test-e2e-community-operator/0.1.368-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.368-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.368-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.368-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.368-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.368-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.368-1)

operators/test-e2e-operator/0.1.369-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.369-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.369-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.369-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.369-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.369-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.369-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65d75d5dbf47648ce4875a36
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65d75d5ab631f41a51d69a97
=> operator test-e2e-operator (0.1.369-1)

operators/test-e2e-community-operator/0.1.369-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.369-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.369-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.369-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.369-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.369-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.369-1)

operators/test-e2e-operator/0.1.369-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.369-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.369-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.369-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.369-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.369-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.369-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65dcbfe1db9691f39c48a90e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65dcbfdec1e7beb57f6150fc
=> operator test-e2e-operator (0.1.369-2)

operators/test-e2e-operator/0.1.370-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.370-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.370-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.370-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.370-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.370-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.370-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65ddf5c9c1e7beb57f615ab4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65ddf5c6db9691f39c48b2cd
=> operator test-e2e-operator (0.1.370-1)

operators/test-e2e-operator/0.1.371-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.371-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.371-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.371-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.371-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.371-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.371-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65de062ac1e7beb57f615b00
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65de0628db9691f39c48b35d
=> operator test-e2e-operator (0.1.371-1)

operators/test-e2e-community-operator/0.1.371-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.371-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.371-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.371-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.371-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.371-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.371-2)

operators/test-e2e-operator/0.1.372-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.372-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.372-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.372-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.372-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.372-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.372-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65df02b0c1e7beb57f616295
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65df02addb9691f39c48ba15
=> operator test-e2e-operator (0.1.372-1)

operators/test-e2e-community-operator/0.1.372-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.372-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.372-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.372-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.372-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.372-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.372-1)

operators/test-e2e-community-operator/0.1.373-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.373-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.373-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.373-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.373-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.373-3/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.373-3)

operators/test-e2e-operator/0.1.376-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.376-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.376-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.376-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.376-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.376-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.376-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65e0a6aec1e7beb57f616e64
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65e0a6abdb9691f39c48c6f4
=> operator test-e2e-operator (0.1.376-1)

operators/test-e2e-community-operator/0.1.376-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.376-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.376-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.376-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.376-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.376-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.376-2)

operators/test-e2e-community-operator/0.1.376-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.376-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.376-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.376-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.376-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.376-3/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.376-3)

operators/test-e2e-operator/0.1.377-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.377-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.377-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.377-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.377-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.377-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.377-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65e1af9adb9691f39c48ce31
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65e1af98c1e7beb57f6175bc
=> operator test-e2e-operator (0.1.377-1)

operators/test-e2e-community-operator/0.1.377-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.377-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.377-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.377-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.377-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.377-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.377-1)

operators/test-e2e-community-operator/0.1.378-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.378-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.378-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.378-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.378-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.378-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.378-1)

operators/test-e2e-operator/0.1.378-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.378-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.378-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.378-4/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.378-4/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.378-4/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.378-4**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65e59d34db6feb7befa5023e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65e59d3175de4b43bb07e0ce
=> operator test-e2e-operator (0.1.378-4)

operators/test-e2e-operator/0.1.378-5/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.378-5/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.378-5/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.378-5/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.378-5/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.378-5/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.378-5**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65e5b0dc75de4b43bb07e16d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65e5b0d9db6feb7befa502e4
=> operator test-e2e-operator (0.1.378-5)

operators/test-e2e-operator/0.1.380-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.380-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.380-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.380-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.380-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.380-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.380-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65e5d00f75de4b43bb07e3b3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65e5d00c75de4b43bb07e3aa
=> operator test-e2e-operator (0.1.380-1)

operators/test-e2e-community-operator/0.1.380-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.380-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.380-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.380-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.380-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.380-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.380-1)

operators/test-e2e-community-operator/0.1.382-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.382-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.382-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.382-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.382-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.382-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.382-1)

operators/test-e2e-operator/0.1.382-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.382-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.382-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.382-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.382-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.382-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.382-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65e64e6240a444aa3c0ef8e0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65e64e5f40a444aa3c0ef8db
=> operator test-e2e-operator (0.1.382-2)

operators/test-e2e-community-operator/0.1.383-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.383-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.383-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.383-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.383-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.383-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.383-1)

operators/test-e2e-operator/0.1.383-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.383-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.383-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.383-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.383-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.383-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.383-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65e7393b41ee4ac46c574480
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65e7393841ee4ac46c57447b
=> operator test-e2e-operator (0.1.383-2)

operators/test-e2e-community-operator/0.1.383-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.383-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.383-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.383-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.383-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.383-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.383-2)

operators/test-e2e-operator/0.1.384-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.384-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.384-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.384-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.384-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.384-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.384-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65e820b841ee4ac46c574a12
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65e820b641ee4ac46c574a09
=> operator test-e2e-operator (0.1.384-2)

operators/test-e2e-operator/0.1.384-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.384-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.384-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.384-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.384-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.384-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.384-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65e8678040a444aa3c0f07f7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65e8677e40a444aa3c0f07ee
=> operator test-e2e-operator (0.1.384-3)

operators/test-e2e-operator/0.1.383-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.383-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.383-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.383-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.383-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.383-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.383-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65e8708e40a444aa3c0f0841
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65e8708c40a444aa3c0f083c
=> operator test-e2e-operator (0.1.383-3)

operators/test-e2e-operator/0.1.384-7/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.384-7/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.384-7/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.384-7/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.384-7/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.384-7/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.384-7**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65eac673f4b4a8ba241f4ed1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65eac670e9aac6ed4f4b156f
=> operator test-e2e-operator (0.1.384-7)

operators/test-e2e-community-operator/0.1.385-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.385-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.385-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.385-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.385-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.385-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.385-1)

operators/test-e2e-operator/0.1.385-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.385-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.385-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.385-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.385-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.385-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.385-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65eb0006e9aac6ed4f4b170d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65eb0004f4b4a8ba241f508c
=> operator test-e2e-operator (0.1.385-2)

operators/test-e2e-operator/0.1.386-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.386-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.386-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.386-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.386-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.386-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.386-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65eb0470e9aac6ed4f4b1799
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65eb046ef4b4a8ba241f50ec
=> operator test-e2e-operator (0.1.386-1)

operators/test-e2e-community-operator/0.1.386-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.386-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.386-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.386-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.386-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.386-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.386-1)

operators/test-e2e-community-operator/0.1.387-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.387-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.387-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.387-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.387-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.387-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.387-1)

operators/test-e2e-operator/0.1.387-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.387-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.387-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.387-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.387-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.387-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.387-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65eecd90e9aac6ed4f4b2f61
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65eecd8e7d9a4d3f52e87d22
=> operator test-e2e-operator (0.1.387-2)

operators/test-e2e-operator/0.1.387-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.387-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.387-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.387-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.387-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.387-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.387-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65ef2eb1faabefabc57a4f03
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65ef2eac3214ce779c5b58cf
=> operator test-e2e-operator (0.1.387-3)

operators/test-e2e-operator/0.1.388-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.388-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.388-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.388-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.388-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.388-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.388-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65f036613214ce779c5b5f43
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65f0363ffaabefabc57a55a6
=> operator test-e2e-operator (0.1.388-1)

operators/test-e2e-community-operator/0.1.388-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.388-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.388-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.388-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.388-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.388-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.388-1)

operators/test-e2e-community-operator/0.1.388-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.388-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.388-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.388-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.388-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.388-3/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.388-3)

operators/test-e2e-community-operator/0.1.389-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.389-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.389-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.389-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.389-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.389-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.389-1)

operators/test-e2e-operator/0.1.389-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.389-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.389-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.389-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.389-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.389-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.389-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65f160b43214ce779c5b6597
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65f1609c3214ce779c5b6592
=> operator test-e2e-operator (0.1.389-1)

operators/test-e2e-operator/0.1.390-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.390-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.390-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.390-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.390-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.390-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.390-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65f17a24faabefabc57a5d52
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65f17a21faabefabc57a5d4d
=> operator test-e2e-operator (0.1.390-1)

operators/test-e2e-operator/0.1.391-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.391-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.391-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.391-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.391-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.391-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.391-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65f1bdcdbb64f9db4e025da0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65f1bdcabb64f9db4e025d97
=> operator test-e2e-operator (0.1.391-1)

operators/test-e2e-community-operator/0.1.390-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.390-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.390-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.390-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.390-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.390-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.390-1)

operators/test-e2e-operator/0.1.393-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.393-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.393-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.393-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.393-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.393-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.393-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65f81781b6e151f90dec9f2a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65f8176dd04e1e00d3382498
=> operator test-e2e-operator (0.1.393-1)

operators/test-e2e-community-operator/0.1.392-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.392-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.392-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.392-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.392-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.392-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.392-2)

operators/test-e2e-community-operator/0.1.393-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.393-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.393-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.393-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.393-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.393-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.393-1)

operators/test-e2e-community-operator/0.1.394-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.394-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.394-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.394-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.394-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.394-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.394-1)

operators/test-e2e-operator/0.1.394-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.394-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.394-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.394-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.394-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.394-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.394-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65fd385ee2874c86794833f3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65fd385c85daf6fb1671ebda
=> operator test-e2e-operator (0.1.394-2)

operators/test-e2e-operator/0.1.395-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.395-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.395-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.395-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.395-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.395-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.395-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65fd5c62e2874c8679483694
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65fd5c5f85daf6fb1671eea0
=> operator test-e2e-operator (0.1.395-1)

operators/test-e2e-operator/0.1.395-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.395-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.395-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.395-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.395-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.395-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.395-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/65fda091e2874c8679483b36
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/65fda08ee2874c8679483b31
=> operator test-e2e-operator (0.1.395-2)

operators/test-e2e-community-operator/0.1.395-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.395-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.395-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.395-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.395-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.395-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.395-2)

operators/test-e2e-operator/0.1.396-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.396-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.396-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.396-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.396-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.396-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.396-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66017ad5e2874c86794854c0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66017ad24a3b8f956e91f372
=> operator test-e2e-operator (0.1.396-1)

operators/test-e2e-community-operator/0.1.396-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.396-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.396-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.396-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.396-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.396-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.396-1)

operators/test-e2e-operator/0.1.397-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.397-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.397-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.397-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.397-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.397-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.397-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/660198b34a3b8f956e91f411
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/660198b04a3b8f956e91f40c
=> operator test-e2e-operator (0.1.397-1)

operators/test-e2e-community-operator/0.1.397-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.397-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.397-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.397-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.397-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.397-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.397-1)

operators/test-e2e-operator/0.1.398-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.398-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.398-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.398-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.398-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.398-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.398-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6601a345e2874c86794855ec
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6601a3424a3b8f956e91f46e
=> operator test-e2e-operator (0.1.398-1)

operators/test-e2e-community-operator/0.1.398-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.398-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.398-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.398-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.398-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.398-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.398-2)

operators/test-e2e-operator/0.1.399-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.399-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.399-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.399-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.399-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.399-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.399-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66059ed143b86f97b9cacdbf
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66059ece9bfce431c23aa726
=> operator test-e2e-operator (0.1.399-1)

operators/test-e2e-community-operator/0.1.399-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.399-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.399-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.399-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.399-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.399-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.399-1)

operators/test-e2e-community-operator/0.1.400-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.400-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.400-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.400-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.400-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.400-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.400-1)

operators/test-e2e-community-operator/0.1.401-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.401-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.401-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.401-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.401-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.401-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.401-1)

operators/test-e2e-community-operator/0.1.402-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.402-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.402-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.402-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.402-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.402-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.402-1)

operators/test-e2e-community-operator/0.1.402-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.402-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.402-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.402-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.402-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.402-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.402-2)

operators/test-e2e-operator/0.1.402-6/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.402-6/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.402-6/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.402-6/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.402-6/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.402-6/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.402-6**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/660d8984bd1fec276a475e82
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/660d8981bd1fec276a475e7d
=> operator test-e2e-operator (0.1.402-6)

operators/test-e2e-operator/0.1.402-8/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.402-8/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.402-8/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.402-8/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.402-8/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.402-8/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.402-8**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/660e4a5300be06826aff33ef
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/660e4a5000be06826aff33ea
=> operator test-e2e-operator (0.1.402-8)

operators/test-e2e-community-operator/0.1.402-8/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.402-8/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.402-8/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.402-8/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.402-8/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.402-8/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.402-8)

operators/test-e2e-operator/0.1.402-9/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.402-9/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.402-9/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.402-9/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.402-9/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.402-9/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.402-9**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6613bbb7bd1fec276a4783b8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6613bbb400be06826aff5509
=> operator test-e2e-operator (0.1.402-9)

operators/test-e2e-operator/0.1.402-10/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.402-10/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.402-10/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.402-10/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.402-10/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.402-10/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.402-10**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6614e8fbbd1fec276a478d60
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6614e8f8bd1fec276a478d5b
=> operator test-e2e-operator (0.1.402-10)

operators/test-e2e-community-operator/0.1.402-11/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.402-11/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.402-11/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.402-11/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.402-11/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.402-11/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.402-11)

operators/test-e2e-community-operator/0.1.402-12/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.402-12/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.402-12/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.402-12/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.402-12/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.402-12/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.402-12)

operators/test-e2e-operator/0.1.404-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.404-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.404-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.404-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.404-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.404-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.404-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6616eb6a718bb5907f59d235
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6616eb678b7035b141732da6
=> operator test-e2e-operator (0.1.404-1)

operators/test-e2e-operator/0.1.402-12/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.402-12/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.402-12/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.402-12/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.402-12/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.402-12/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.402-12**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6617a47f718bb5907f59d6dc
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6617a47c718bb5907f59d6d7
=> operator test-e2e-operator (0.1.402-12)

operators/test-e2e-operator/0.1.405-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.405-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.405-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.405-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.405-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.405-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.405-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6617d0f98b7035b1417334ca
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6617d0f78b7035b1417334c5
=> operator test-e2e-operator (0.1.405-1)

operators/test-e2e-operator/0.1.406-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.406-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.406-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.406-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.406-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.406-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.406-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66194220a3239d589aab178b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6619421ca3239d589aab1786
=> operator test-e2e-operator (0.1.406-1)

operators/test-e2e-operator/0.1.407-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.407-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.407-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.407-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.407-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.407-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.407-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/661ea5e3f5270e35f166e8f0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/661ea5e082725d4fba792703
=> operator test-e2e-operator (0.1.407-1)

operators/test-e2e-community-operator/0.1.407-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.407-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.407-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.407-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.407-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.407-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.407-1)

operators/test-e2e-community-operator/0.1.408-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.408-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.408-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.408-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.408-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.408-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.408-1)

operators/test-e2e-operator/0.1.409-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.409-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.409-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.409-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.409-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.409-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.409-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/662263569b51048ce97842d4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66226353a9c5b6385b670ea4
=> operator test-e2e-operator (0.1.409-1)

operators/test-e2e-operator/0.1.410-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.410-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.410-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.410-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.410-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.410-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.410-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6627d84b21443eb26c780cdc
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6627d84821443eb26c780cd3
=> operator test-e2e-operator (0.1.410-1)

operators/test-e2e-community-operator/0.1.410-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.410-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.410-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.410-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.410-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.410-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.410-2)

operators/test-e2e-operator/0.1.411-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.411-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.411-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.411-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.411-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.411-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.411-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/662ba7343f704bba76b4eee1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/662ba731ed5b489680de19b4
=> operator test-e2e-operator (0.1.411-1)

operators/test-e2e-operator/0.1.412-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.412-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.412-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.412-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.412-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.412-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.412-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/662bb1723f704bba76b4ef49
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/662bb16f3f704bba76b4ef40
=> operator test-e2e-operator (0.1.412-1)

operators/test-e2e-community-operator/0.1.412-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.412-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.412-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.412-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.412-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.412-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.412-1)

operators/test-e2e-operator/0.1.412-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.412-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.412-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.412-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.412-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.412-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.412-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/662fb781ed5b489680de2af0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/662fb77e3f704bba76b501f2
=> operator test-e2e-operator (0.1.412-2)

operators/test-e2e-operator/0.1.413-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.413-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.413-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.413-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.413-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.413-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.413-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66333483af2429f3f5f2d831
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/663334815e39c41209750286
=> operator test-e2e-operator (0.1.413-1)

operators/test-e2e-operator/0.1.414-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.414-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.414-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.414-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.414-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.414-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.414-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6634d68416ff6557f83010f8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6634d682ed7d00b560792733
=> operator test-e2e-operator (0.1.414-3)

operators/test-e2e-community-operator/0.1.414-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.414-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.414-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.414-4/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.414-4/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.414-4/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.414-4)

operators/test-e2e-operator/0.1.415-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.415-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.415-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.415-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.415-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.415-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.415-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6639415716ff6557f83022d3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6639415516ff6557f83022ce
=> operator test-e2e-operator (0.1.415-1)

operators/test-e2e-community-operator/0.1.415-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.415-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.415-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.415-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.415-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.415-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.415-1)

operators/test-e2e-community-operator/0.1.416-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.416-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.416-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.416-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.416-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.416-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.416-1)

operators/test-e2e-operator/0.1.417-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.417-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.417-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.417-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.417-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.417-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.417-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/663a3f2e16ff6557f830279c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/663a3f2c16ff6557f8302797
=> operator test-e2e-operator (0.1.417-1)

operators/test-e2e-operator/0.1.418-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.418-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.418-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.418-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.418-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.418-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.418-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/663a82bded7d00b560793ee9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/663a82bbed7d00b560793ee0
=> operator test-e2e-operator (0.1.418-1)

operators/test-e2e-community-operator/0.1.419-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.419-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.419-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.419-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.419-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.419-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.419-1)

operators/test-e2e-operator/0.1.419-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.419-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.419-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.419-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.419-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.419-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.419-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/663cdf2a16ff6557f83038bb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/663cdf2716ff6557f83038b6
=> operator test-e2e-operator (0.1.419-2)

operators/test-e2e-operator/0.1.420-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.420-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.420-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.420-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.420-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.420-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.420-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6641cb1f254539d6a5036706
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6641cb1c8a4728059b1d58b8
=> operator test-e2e-operator (0.1.420-1)

operators/test-e2e-operator/0.1.421-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.421-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.421-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.421-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.421-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.421-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.421-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66423361254539d6a503693f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6642335e8a4728059b1d5a5b
=> operator test-e2e-operator (0.1.421-1)

operators/test-e2e-community-operator/0.1.422-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.422-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.422-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.422-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.422-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.422-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.422-2)

operators/test-e2e-community-operator/0.1.424-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.424-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.424-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.424-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.424-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.424-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.424-1)

operators/test-e2e-operator/0.1.422-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.422-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.422-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.422-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.422-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.422-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.422-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66470d01158625a869b98b67
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66470cff158625a869b98b5e
=> operator test-e2e-operator (0.1.422-1)

operators/test-e2e-operator/0.1.426-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.426-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.426-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.426-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.426-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.426-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.426-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66470f8a158625a869b98b92
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66470f87e2c5eef0d5b5925d
=> operator test-e2e-operator (0.1.426-2)

operators/test-e2e-community-operator/0.1.426-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.426-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.426-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.426-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.426-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.426-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.426-2)

operators/test-e2e-community-operator/0.1.1-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.1-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.1-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.1-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.1-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.1-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.1-1)

operators/test-e2e-operator/0.1.427-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.427-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.427-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.427-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.427-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.427-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.427-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/664af816e2c5eef0d5b5a412
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/664af813158625a869b99dc9
=> operator test-e2e-operator (0.1.427-1)

operators/test-e2e-community-operator/0.1.427-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.427-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.427-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.427-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.427-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.427-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.427-1)

operators/test-e2e-operator/0.1.427-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.427-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.427-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.427-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.427-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.427-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.427-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/664b167ee2c5eef0d5b5a4bd
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/664b167c158625a869b99e76
=> operator test-e2e-operator (0.1.427-2)

operators/test-e2e-operator/0.1.427-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.427-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.427-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.427-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.427-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.427-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.427-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/664b4efee2c5eef0d5b5a5f5
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/664b4efce2c5eef0d5b5a5ec
=> operator test-e2e-operator (0.1.427-3)

operators/test-e2e-community-operator/0.1.428-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.428-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.428-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.428-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.428-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.428-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.428-1)

operators/test-e2e-operator/0.1.429-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.429-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.429-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.429-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.429-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.429-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.429-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/664dfe97c9eb11928995093c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/664dfe94c9042a370c1f133a
=> operator test-e2e-operator (0.1.429-1)

operators/test-e2e-operator/0.1.430-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.430-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.430-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.430-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.430-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.430-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.430-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/664f094727315f77d2ac2140
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/664f0944dd69440dd3d10952
=> operator test-e2e-operator (0.1.430-1)

operators/test-e2e-operator/0.1.428-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.428-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.428-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.428-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.428-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.428-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.428-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/665452b927315f77d2ac38c9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/665452b7dd69440dd3d121bd
=> operator test-e2e-operator (0.1.428-1)

operators/test-e2e-operator/0.1.1-8/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-8/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-8/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-8/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-8/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-8/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-8**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66547275dd69440dd3d1237d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66547272dd69440dd3d12378
=> operator test-e2e-operator (0.1.1-8)

operators/test-e2e-community-operator/0.1.1-8/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.1-8/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.1-8/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.1-8/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.1-8/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.1-8/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.1-8)

operators/test-e2e-operator/0.1.436-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.436-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.436-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.436-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.436-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.436-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.436-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6656ef80f16fbc69519324df
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6656ef7ef16fbc69519324da
=> operator test-e2e-operator (0.1.436-1)

operators/test-e2e-operator/0.1.437-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.437-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.437-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.437-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.437-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.437-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.437-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6656efca8eae81054397b773
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6656efc7f16fbc6951932506
=> operator test-e2e-operator (0.1.437-1)

operators/test-e2e-operator/0.1.443-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.443-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.443-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.443-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.443-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.443-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.443-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66572e6ef16fbc6951932772
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66572e6b8eae81054397b9db
=> operator test-e2e-operator (0.1.443-1)

operators/test-e2e-operator/0.1.437-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.437-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.437-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.437-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.437-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.437-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.437-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66573272f16fbc69519327b0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6657326f8eae81054397ba15
=> operator test-e2e-operator (0.1.437-2)

operators/test-e2e-operator/0.1.445-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.445-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.445-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.445-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.445-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.445-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.445-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/665871778eae81054397c0e1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66587174f16fbc6951932e58
=> operator test-e2e-operator (0.1.445-2)

operators/test-e2e-operator/0.1.1-10/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-10/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-10/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-10/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-10/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-10/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-10**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6660229f8d583bbf763b6378
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6660229c5768c053ebe87364
=> operator test-e2e-operator (0.1.1-10)

operators/test-e2e-operator/0.1.1-11/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-11/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-11/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-11/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-11/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-11/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-11**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66602e4c5768c053ebe873fd
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66602e4a8d583bbf763b643b
=> operator test-e2e-operator (0.1.1-11)

operators/test-e2e-operator/0.1.1-12/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-12/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-12/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-12/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-12/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-12/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-12**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6666bbeea6977a50ccbfe534
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6666bbeca6977a50ccbfe52f
=> operator test-e2e-operator (0.1.1-12)

operators/test-e2e-operator/0.1.1-13/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-13/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-13/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-13/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-13/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-13/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-13**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6666ee6ffb1281b07500e610
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6666ee6dfb1281b07500e607
=> operator test-e2e-operator (0.1.1-13)

operators/test-e2e-operator/0.1.1-14/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-14/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-14/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-14/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-14/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-14/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-14**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6667012ca6977a50ccbfe9d0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66670129fb1281b07500e71c
=> operator test-e2e-operator (0.1.1-14)

operators/test-e2e-operator/0.1.1-15/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-15/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-15/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-15/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-15/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-15/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-15**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/666812bcccc5ec6b7b92c942
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/666812baccc5ec6b7b92c939
=> operator test-e2e-operator (0.1.1-15)

operators/test-e2e-operator/0.1.1-16/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-16/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-16/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-16/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-16/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-16/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-16**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/666836f93fc6a950bfe4a576
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/666836f63fc6a950bfe4a56d
=> operator test-e2e-operator (0.1.1-16)

operators/test-e2e-operator/0.1.448-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.448-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.448-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.448-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.448-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.448-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.448-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6668636f3fc6a950bfe4a699
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6668636dccc5ec6b7b92cb8d
=> operator test-e2e-operator (0.1.448-1)

operators/test-e2e-operator/0.1.1-18/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-18/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-18/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-18/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-18/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-18/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-18**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66686d9dccc5ec6b7b92cbe8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66686d9accc5ec6b7b92cbe3
=> operator test-e2e-operator (0.1.1-18)

operators/test-e2e-operator/0.1.1-19/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-19/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-19/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-19/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-19/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-19/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-19**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66688a09ccc5ec6b7b92cc63
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66688a07ccc5ec6b7b92cc5a
=> operator test-e2e-operator (0.1.1-19)

operators/test-e2e-operator/0.1.448-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.448-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.448-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.448-3/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.448-3/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.448-3/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.448-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/666986e73fc6a950bfe4aaca
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/666986e5ccc5ec6b7b92d004
=> operator test-e2e-operator (0.1.448-3)

operators/test-e2e-operator/0.1.1-20/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-20/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-20/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-20/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-20/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-20/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-20**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6669bad73fc6a950bfe4ad24
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6669bad4ccc5ec6b7b92d256
=> operator test-e2e-operator (0.1.1-20)

operators/test-e2e-operator/0.1.449-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.449-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.449-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.449-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.449-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.449-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.449-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6669cc822443a72ca706798e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6669cc802443a72ca7067985
=> operator test-e2e-operator (0.1.449-1)

operators/test-e2e-operator/0.1.1-9/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-9/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-9/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-9/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-9/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-9/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-9**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/666adc152443a72ca7067d62
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/666adc132443a72ca7067d5d
=> operator test-e2e-operator (0.1.1-9)

operators/test-e2e-operator/0.1.1-21/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-21/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-21/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-21/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-21/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-21/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-21**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/666b0a872443a72ca7067e6b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/666b0a856b6aefd8dba07288
=> operator test-e2e-operator (0.1.1-21)

operators/test-e2e-operator/0.1.451-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.451-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.451-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.451-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.451-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.451-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.451-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/666b21f82443a72ca7067ee7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/666b21f66b6aefd8dba072f0
=> operator test-e2e-operator (0.1.451-1)

operators/test-e2e-operator/0.1.1-22/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-22/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-22/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-22/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-22/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-22/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-22**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/666c01e02443a72ca7068213
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/666c01de6b6aefd8dba07588
=> operator test-e2e-operator (0.1.1-22)

operators/test-e2e-operator/0.1.453-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.453-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.453-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.453-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.453-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.453-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.453-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/666c10762443a72ca70682a5
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/666c10736b6aefd8dba075fe
=> operator test-e2e-operator (0.1.453-1)

operators/test-e2e-community-operator/0.1.452-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.452-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.452-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.452-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.452-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.452-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.452-1)

operators/test-e2e-community-operator/0.1.453-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.453-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.453-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.453-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.453-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.453-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.453-1)

operators/test-e2e-operator/0.1.455-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.455-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.455-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.455-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.455-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.455-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.455-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/666c79d62443a72ca7068547
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/666c79d32443a72ca706853e
=> operator test-e2e-operator (0.1.455-1)

operators/test-e2e-community-operator/0.1.455-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.455-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.455-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.455-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.455-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.455-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.455-1)

operators/test-e2e-operator/0.1.1-23/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-23/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-23/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-23/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-23/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-23/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-23**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/666ff10d2443a72ca7069282
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/666ff10b2443a72ca7069279
=> operator test-e2e-operator (0.1.1-23)

operators/test-e2e-operator/0.1.456-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.456-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.456-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.456-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.456-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.456-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.456-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/666ff7966b6aefd8dba085d4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/666ff7942443a72ca70692bb
=> operator test-e2e-operator (0.1.456-1)

operators/test-e2e-operator/0.1.1-24/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-24/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-24/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-24/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-24/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-24/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-24**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/667002432443a72ca7069326
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/667002402443a72ca706931d
=> operator test-e2e-operator (0.1.1-24)

operators/test-e2e-operator/0.1.1-25/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-25/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-25/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-25/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-25/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-25/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-25**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6670205d6b6aefd8dba08707
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6670205b6b6aefd8dba08702
=> operator test-e2e-operator (0.1.1-25)

operators/test-e2e-operator/0.1.1-26/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-26/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-26/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-26/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-26/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-26/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-26**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/667040e62443a72ca70694e6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/667040e42443a72ca70694dd
=> operator test-e2e-operator (0.1.1-26)

operators/test-e2e-community-operator/0.1.458-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.458-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.458-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.458-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.458-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.458-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.458-1)

operators/test-e2e-operator/0.1.459-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.459-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.459-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.459-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.459-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.459-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.459-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66708c34e910fc5c50dd9e2e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66708c31348c054b708e77d6
=> operator test-e2e-operator (0.1.459-1)

operators/test-e2e-community-operator/0.1.459-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.459-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.459-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.459-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.459-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.459-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.459-1)

operators/test-e2e-operator/0.1.1-27/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-27/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-27/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-27/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-27/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-27/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-27**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66714776e910fc5c50dda2f6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66714773348c054b708e7cc2
=> operator test-e2e-operator (0.1.1-27)

operators/test-e2e-operator/0.1.460-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.460-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.460-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.460-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.460-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.460-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.460-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/667150a5348c054b708e7d7f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/667150a3e910fc5c50dda38d
=> operator test-e2e-operator (0.1.460-2)

operators/test-e2e-operator/0.1.461-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.461-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.461-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.461-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.461-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.461-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.461-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6671609ee910fc5c50dda40b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6671609b348c054b708e7e25
=> operator test-e2e-operator (0.1.461-1)

operators/test-e2e-operator/0.1.1-28/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-28/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-28/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-28/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-28/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-28/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-28**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6671656de910fc5c50dda451
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6671656b348c054b708e7e67
=> operator test-e2e-operator (0.1.1-28)

operators/test-e2e-operator/0.1.462-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.462-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.462-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.462-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.462-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.462-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.462-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66717ee4348c054b708e7ef7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66717ee1e910fc5c50dda4f9
=> operator test-e2e-operator (0.1.462-1)

operators/test-e2e-operator/0.1.463-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.463-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.463-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.463-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.463-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.463-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.463-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66719904e910fc5c50dda68d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66719902e910fc5c50dda688
=> operator test-e2e-operator (0.1.463-1)

operators/test-e2e-operator/0.1.1-29/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-29/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-29/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-29/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-29/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-29/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-29**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66719bc4e910fc5c50dda6d7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66719bc1348c054b708e8099
=> operator test-e2e-operator (0.1.1-29)

operators/test-e2e-community-operator/0.1.463-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.463-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.463-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.463-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.463-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.463-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.463-1)

operators/test-e2e-operator/0.1.1-30/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-30/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-30/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-30/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-30/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-30/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-30**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66728614e910fc5c50ddaa71
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66728611348c054b708e849f
=> operator test-e2e-operator (0.1.1-30)

operators/test-e2e-operator/0.1.1-31/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-31/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-31/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-31/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-31/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-31/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-31**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66729737348c054b708e8522
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66729734348c054b708e8519
=> operator test-e2e-operator (0.1.1-31)

operators/test-e2e-operator/0.1.1-32/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-32/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-32/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-32/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-32/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-32/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-32**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6672a500348c054b708e8579
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6672a4fde910fc5c50ddab71
=> operator test-e2e-operator (0.1.1-32)

operators/test-e2e-operator/0.1.1-33/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-33/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-33/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-33/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-33/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-33/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-33**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6672cab0e910fc5c50ddad48
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6672caae348c054b708e874a
=> operator test-e2e-operator (0.1.1-33)

operators/test-e2e-operator/0.1.1-34/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-34/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-34/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-34/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-34/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-34/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-34**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6672f88f348c054b708e880f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6672f88c348c054b708e880a
=> operator test-e2e-operator (0.1.1-34)

operators/test-e2e-operator/0.1.1-35/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-35/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-35/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-35/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-35/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-35/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-35**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6673009b348c054b708e8856
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66730098e910fc5c50ddae98
=> operator test-e2e-operator (0.1.1-35)

operators/test-e2e-operator/0.1.1-36/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-36/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-36/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-36/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-36/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-36/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-36**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/667315d2e910fc5c50ddaf1a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/667315d0348c054b708e88b1
=> operator test-e2e-operator (0.1.1-36)

operators/test-e2e-community-operator/0.1.1-36/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.1-36/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.1-36/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.1-36/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.1-36/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.1-36/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.1-36)

operators/test-e2e-operator/0.1.472-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.472-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.472-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.472-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.472-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.472-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.472-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66841cd929c9c2a7dda25a41
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66841cd6429463139f2c53d9
=> operator test-e2e-operator (0.1.472-1)

operators/test-e2e-operator/0.1.473-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.473-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.473-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.473-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.473-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.473-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.473-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6684330329c9c2a7dda25ad3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6684330029c9c2a7dda25ace
=> operator test-e2e-operator (0.1.473-1)

operators/test-e2e-community-operator/0.1.473-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.473-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.473-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.473-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.473-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.473-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.473-1)

operators/test-e2e-operator/0.1.473-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.473-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.473-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.473-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.473-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.473-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.473-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6684fc39429463139f2c58d3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6684fc3729c9c2a7dda25ecb
=> operator test-e2e-operator (0.1.473-2)

operators/test-e2e-operator/0.1.474-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.474-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.474-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.474-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.474-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.474-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.474-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6685122e429463139f2c59a9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6685122b429463139f2c59a4
=> operator test-e2e-operator (0.1.474-1)

operators/test-e2e-community-operator/0.1.474-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.474-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.474-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.474-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.474-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.474-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.474-1)

operators/test-e2e-operator/0.1.475-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.475-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.475-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.475-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.475-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.475-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.475-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6685227d429463139f2c5a2f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6685227a29c9c2a7dda2602f
=> operator test-e2e-operator (0.1.475-1)

operators/test-e2e-community-operator/0.1.475-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.475-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.475-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.475-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.475-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.475-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.475-1)

operators/test-e2e-operator/0.1.476-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.476-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.476-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.476-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.476-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.476-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.476-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/668533e4429463139f2c5b93
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/668533e129c9c2a7dda2617b
=> operator test-e2e-operator (0.1.476-1)

operators/test-e2e-community-operator/0.1.476-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.476-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.476-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.476-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.476-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.476-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.476-1)

operators/test-e2e-community-operator/0.1.477-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.477-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.477-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.477-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.477-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.477-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.477-1)

operators/test-e2e-operator/0.1.477-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.477-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.477-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.477-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.477-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.477-2/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.477-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/668b91f829c9c2a7dda2858e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/668b91f5429463139f2c7f92
=> operator test-e2e-operator (0.1.477-2)

operators/test-e2e-operator/0.1.1-39/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-39/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-39/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-39/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-39/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-39/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-39**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/668b9d37429463139f2c805a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/668b9d34429463139f2c8051
=> operator test-e2e-operator (0.1.1-39)

operators/test-e2e-operator/0.1.1-40/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-40/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-40/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-40/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-40/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-40/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-40**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/668bb457429463139f2c80f7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/668bb455429463139f2c80ee
=> operator test-e2e-operator (0.1.1-40)

operators/test-e2e-operator/0.1.1-41/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-41/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-41/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-41/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-41/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-41/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-41**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/668bc8fb429463139f2c8265
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/668bc8f929c9c2a7dda28882
=> operator test-e2e-operator (0.1.1-41)

operators/test-e2e-operator/0.1.1-42/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-42/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-42/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-42/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-42/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-42/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-42**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/668bd1b7429463139f2c82f6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/668bd1b5429463139f2c82f1
=> operator test-e2e-operator (0.1.1-42)

operators/test-e2e-operator/0.1.1-43/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-43/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-43/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-43/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-43/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-43/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-43**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/668be23e29c9c2a7dda289a0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/668be23b429463139f2c838b
=> operator test-e2e-operator (0.1.1-43)

operators/test-e2e-community-operator/0.1.1-43/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.1-43/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.1-43/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.1-43/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.1-43/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.1-43/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.1-43)

operators/test-e2e-operator/0.1.1-44/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-44/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-44/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-44/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-44/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-44/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-44**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/668d2d011d38d7b578f6b220
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/668d2cfee80fa1719baa76cd
=> operator test-e2e-operator (0.1.1-44)

operators/test-e2e-operator/0.1.478-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.478-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.478-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.478-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.478-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.478-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.478-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/668e5f42e80fa1719baa7df8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/668e5f401d38d7b578f6b93d
=> operator test-e2e-operator (0.1.478-1)

operators/test-e2e-community-operator/0.1.478-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.478-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.478-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.478-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.478-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.478-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.478-1)

operators/test-e2e-operator/0.1.479-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.479-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.479-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.479-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.479-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.479-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.479-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/668e8f4ee80fa1719baa7f48
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/668e8f4be80fa1719baa7f3f
=> operator test-e2e-operator (0.1.479-1)

operators/test-e2e-community-operator/0.1.479-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.479-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.479-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.479-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.479-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.479-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.479-1)

operators/test-e2e-operator/0.1.1-45/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-45/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-45/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-45/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-45/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-45/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-45**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/669128ace080d4394d5cd7ff
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/669128aa7f921e72f6432c5f
=> operator test-e2e-operator (0.1.1-45)

operators/test-e2e-operator/0.1.480-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.480-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.480-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.480-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.480-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.480-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.480-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66913a37e080d4394d5cd8a8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66913a34e080d4394d5cd8a3
=> operator test-e2e-operator (0.1.480-1)

operators/test-e2e-community-operator/0.1.480-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.480-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.480-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.480-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.480-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.480-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.480-1)

operators/test-e2e-operator/0.1.481-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.481-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.481-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.481-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.481-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.481-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.481-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66915f637f921e72f6432dfb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66915f607f921e72f6432df6
=> operator test-e2e-operator (0.1.481-1)

operators/test-e2e-community-operator/0.1.481-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.481-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.481-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.481-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.481-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.481-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.481-1)

operators/test-e2e-community-operator/0.1.1-46/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.1-46/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.1-46/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.1-46/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.1-46/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.1-46/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.1-46)

operators/test-e2e-operator/0.1.482-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.482-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.482-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.482-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.482-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.482-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.482-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66956b7fe5a1586d19727140
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66956b7ce5a1586d1972713b
=> operator test-e2e-operator (0.1.482-1)

operators/test-e2e-community-operator/0.1.482-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.482-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.482-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.482-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.482-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.482-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.482-1)

operators/test-e2e-community-operator/0.1.488-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.488-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.488-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.488-2/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.488-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.488-2/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.488-2)

operators/test-e2e-operator/0.1.1-47/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.1-47/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.1-47/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.1-47/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.1-47/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.1-47/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.1-47**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66a0b955b41c1313646e3af6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66a0b953b41c1313646e3aed
=> operator test-e2e-operator (0.1.1-47)

operators/test-e2e-operator-fbc/0.1.151-223/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator-fbc/0.1.151-223/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator-fbc/0.1.151-223/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator-fbc/0.1.151-223/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml, operators/test-e2e-operator-fbc/0.1.151-223/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator-fbc/0.1.151-223/metadata/annotations.yaml
Version: **0.1.151-223**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66a77cab84db889d16db5bf7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66a77ca9ed864bc7d00e52f0
=> operator test-e2e-operator-fbc (0.1.151-223)

operators/test-e2e-operator/0.1.489-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator/0.1.489-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator/0.1.489-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator/0.1.489-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-operator/0.1.489-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator/0.1.489-1/metadata/annotations.yaml, operators/test-e2e-operator/ci.yaml
Version: **0.1.489-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66a88e682871b72536804554
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66a88e65b24fb78e88eb0569
=> operator test-e2e-operator (0.1.489-1)

operators/test-e2e-community-operator/0.1.489-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.489-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.489-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.489-1/manifests/test-e2e-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.489-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.489-1/metadata/annotations.yaml, operators/test-e2e-community-operator/ci.yaml
=> operator test-e2e-community-operator (0.1.489-1)

operators/test-e2e-community-operator/0.1.493-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.493-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.493-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.493-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.493-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.493-1/metadata/annotations.yaml
E2e test for test-e2e-community-operator (0.1.493-1)
=> operator test-e2e-community-operator (0.1.493-1)

operators/test-e2e-community-operator/0.1.494-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.494-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.494-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.494-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.494-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.494-1/metadata/annotations.yaml
E2e test for test-e2e-community-operator (0.1.494-1)
=> operator test-e2e-community-operator (0.1.494-1)

operators/test-e2e-community-operator/0.1.495-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-community-operator/0.1.495-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-community-operator/0.1.495-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-community-operator/0.1.495-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml, operators/test-e2e-community-operator/0.1.495-2/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-community-operator/0.1.495-2/metadata/annotations.yaml
E2e test for test-e2e-community-operator (0.1.495-2)
=> operator test-e2e-community-operator (0.1.495-2)

operators/test-e2e-operator-fbc/0.1.497-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml, operators/test-e2e-operator-fbc/0.1.497-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml, operators/test-e2e-operator-fbc/0.1.497-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, operators/test-e2e-operator-fbc/0.1.497-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml, operators/test-e2e-operator-fbc/0.1.497-1/manifests/tools.opdev.io_demoresources.yaml, operators/test-e2e-operator-fbc/0.1.497-1/metadata/annotations.yaml
Version: **0.1.497-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66aa3c152871b72536804b04
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66aa3c12b24fb78e88eb0b4f
=> operator test-e2e-operator-fbc (0.1.497-1)
