redhat-openshift-ecosystem/operator-pipelines-test

operators/test-e2e-operator/0.1.497-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.497-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.497-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.497-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.497-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.497-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.497-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66aa3c44b24fb78e88eb0b6b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66aa3c42b24fb78e88eb0b66

operator test-e2e-operator (0.1.497-1)

---

operators/test-e2e-community-operator/0.1.497-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.497-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.497-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.497-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.497-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.497-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.497-1)

operator test-e2e-community-operator (0.1.497-1)

---

operators/test-e2e-operator-fbc/0.1.499-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.499-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.499-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.499-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.499-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.499-1/metadata/annotations.yaml

Version: **0.1.499-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66aa4e80b24fb78e88eb0be1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66aa4e7eb24fb78e88eb0bde

operator test-e2e-operator-fbc (0.1.499-1)

---

operators/test-e2e-community-operator/0.1.498-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.498-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.498-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.498-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.498-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.498-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.498-1)

operator test-e2e-community-operator (0.1.498-1)

---

operators/test-e2e-operator/0.1.499-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.499-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.499-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.499-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.499-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.499-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.499-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66aa4e742871b72536804b94
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66aa4e722871b72536804b91

operator test-e2e-operator (0.1.499-1)

---

operators/test-e2e-community-operator/0.1.499-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.499-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.499-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.499-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.499-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.499-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.499-1)

operator test-e2e-community-operator (0.1.499-1)

---

operators/test-e2e-operator-fbc/0.1.500-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.500-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.500-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.500-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.500-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.500-1/metadata/annotations.yaml

Version: **0.1.500-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66aa5f6730403fe86dddb854
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66aa5f6530403fe86dddb84f

operator test-e2e-operator-fbc (0.1.500-1)

---

operators/test-e2e-operator/0.1.500-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.500-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.500-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.500-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.500-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.500-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.500-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66aa5f5030403fe86dddb841
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66aa5f4e43ad185bcbc8559c

operator test-e2e-operator (0.1.500-1)

---

operators/test-e2e-community-operator/0.1.500-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.500-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.500-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.500-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.500-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.500-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.500-1)

operator test-e2e-community-operator (0.1.500-1)

---

operators/test-e2e-operator/0.1.151-227/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.151-227/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.151-227/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.151-227/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.151-227/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.151-227/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.151-227**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ab84e243ad185bcbc859c3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ab84e043ad185bcbc859b7

operator test-e2e-operator (0.1.151-227)

---

operators/test-e2e-operator-fbc/0.1.151-228/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.151-228/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.151-228/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.151-228/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.151-228/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.151-228/metadata/annotations.yaml

Version: **0.1.151-228**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66b07e6930403fe86dddcb30
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66b07e6743ad185bcbc869ae

operator test-e2e-operator-fbc (0.1.151-228)

---

operators/test-e2e-operator/0.1.151-228/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.151-228/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.151-228/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.151-228/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.151-228/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.151-228/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.151-228**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66b0894143ad185bcbc86a33
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66b0893f30403fe86dddcb99

operator test-e2e-operator (0.1.151-228)

---

operators/test-e2e-operator/0.1.501-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.501-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.501-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.501-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.501-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.501-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.501-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66b09f6843ad185bcbc86b80
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66b09f6543ad185bcbc86b7d

operator test-e2e-operator (0.1.501-1)

---

operators/test-e2e-community-operator/0.1.501-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.501-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.501-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.501-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.501-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.501-1/metadata/annotations.yaml
operators/test-e2e-community-operator/ci.yaml

operator test-e2e-community-operator (0.1.501-1)

---

operators/test-e2e-operator-fbc/0.1.502-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.502-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.502-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.502-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.502-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.502-1/metadata/annotations.yaml

Version: **0.1.502-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66b0cad9b0b1a8b90ee09492
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66b0cad710f02f8a3e2e7351

operator test-e2e-operator-fbc (0.1.502-1)

---

operators/test-e2e-operator/0.1.502-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.502-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.502-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.502-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.502-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.502-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.502-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66b0ca9db0b1a8b90ee0947f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66b0ca9bb0b1a8b90ee0947c

operator test-e2e-operator (0.1.502-1)

---

operators/test-e2e-community-operator/0.1.502-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.502-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.502-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.502-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.502-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.502-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.502-1)

operator test-e2e-community-operator (0.1.502-1)

---

operators/test-e2e-operator/0.1.503-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.503-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.503-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.503-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.503-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.503-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.503-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66b1115510f02f8a3e2e745b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66b1115310f02f8a3e2e7458

operator test-e2e-operator (0.1.503-1)

---

operators/test-e2e-community-operator/0.1.503-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.503-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.503-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.503-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.503-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.503-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.503-1)

operator test-e2e-community-operator (0.1.503-1)

---

operators/test-e2e-community-operator/0.1.503-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.503-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.503-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.503-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.503-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.503-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.503-2)

operator test-e2e-community-operator (0.1.503-2)

---

operators/test-e2e-community-operator/0.1.504-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.504-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.504-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.504-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.504-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.504-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.504-1)

operator test-e2e-community-operator (0.1.504-1)

---

operators/test-e2e-community-operator/0.1.505-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.505-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.505-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.505-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.505-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.505-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.505-1)

operator test-e2e-community-operator (0.1.505-1)

---

operators/test-e2e-community-operator/0.1.506-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.506-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.506-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.506-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.506-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.506-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.506-1)

operator test-e2e-community-operator (0.1.506-1)

---

operators/test-e2e-operator-fbc/0.1.507-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.507-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.507-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.507-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.507-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.507-1/metadata/annotations.yaml

Version: **0.1.507-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66b4a5bab0b1a8b90ee0a1be
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66b4a5b810f02f8a3e2e8098

operator test-e2e-operator-fbc (0.1.507-1)

---

operators/test-e2e-operator/0.1.507-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.507-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.507-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.507-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.507-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.507-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.507-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66b4a555b0b1a8b90ee0a19e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66b4a552b0b1a8b90ee0a19b

operator test-e2e-operator (0.1.507-1)

---

operators/test-e2e-community-operator/0.1.507-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.507-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.507-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.507-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.507-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.507-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.507-1)

operator test-e2e-community-operator (0.1.507-1)

---

operators/test-e2e-community-operator/0.1.507-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.507-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.507-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.507-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.507-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.507-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.507-2)

operator test-e2e-community-operator (0.1.507-2)

---

operators/test-e2e-operator-fbc/0.1.507-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.507-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.507-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.507-3/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.507-3/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.507-3/metadata/annotations.yaml

Version: **0.1.507-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66b4bcce10f02f8a3e2e8108
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66b4bccb10f02f8a3e2e8105

operator test-e2e-operator-fbc (0.1.507-3)

---

operators/test-e2e-operator-fbc/0.1.509-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.509-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.509-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.509-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.509-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.509-1/metadata/annotations.yaml

Version: **0.1.509-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66b9f73610f02f8a3e2e9159
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66b9f73410f02f8a3e2e9154

operator test-e2e-operator-fbc (0.1.509-1)

---

operators/test-e2e-operator/0.1.509-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.509-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.509-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.509-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.509-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.509-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.509-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66b9f77fb0b1a8b90ee0b2b4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66b9f77cb0b1a8b90ee0b2af

operator test-e2e-operator (0.1.509-1)

---

operators/test-e2e-community-operator/0.1.509-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.509-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.509-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.509-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.509-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.509-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.509-1)

operator test-e2e-community-operator (0.1.509-1)

---

operators/test-e2e-operator/0.1.510-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.510-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.510-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.510-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.510-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.510-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.510-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ba0c5ab0b1a8b90ee0b323
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ba0c5810f02f8a3e2e91c4

operator test-e2e-operator (0.1.510-1)

---

operators/test-e2e-community-operator/0.1.510-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.510-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.510-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.510-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.510-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.510-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.510-1)

operator test-e2e-community-operator (0.1.510-1)

---

operators/test-e2e-operator-fbc/0.1.510-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.510-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.510-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.510-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.510-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.510-2/metadata/annotations.yaml

Version: **0.1.510-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ba19ef10f02f8a3e2e920f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ba19ed10f02f8a3e2e920a

operator test-e2e-operator-fbc (0.1.510-2)

---

operators/test-e2e-operator/0.1.511-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.511-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.511-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.511-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.511-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.511-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.511-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ba1d35b0b1a8b90ee0b386
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ba1d3310f02f8a3e2e9232

operator test-e2e-operator (0.1.511-1)

---

operators/test-e2e-community-operator/0.1.511-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.511-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.511-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.511-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.511-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.511-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.511-1)

operator test-e2e-community-operator (0.1.511-1)

---

operators/test-e2e-operator-fbc/0.1.512-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.512-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.512-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.512-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.512-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.512-1/metadata/annotations.yaml

Version: **0.1.512-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66bb63cbe2d4088fc42d8f4b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66bb63c9e2d4088fc42d8f44

operator test-e2e-operator-fbc (0.1.512-1)

---

operators/test-e2e-operator/0.1.512-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.512-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.512-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.512-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.512-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.512-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.512-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66bb6423e2d4088fc42d8f68
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66bb642034cb03f08a15fac9

operator test-e2e-operator (0.1.512-1)

---

operators/test-e2e-community-operator/0.1.512-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.512-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.512-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.512-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.512-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.512-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.512-1)

operator test-e2e-community-operator (0.1.512-1)

---

operators/test-e2e-operator-fbc/0.1.513-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.513-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.513-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.513-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.513-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.513-1/metadata/annotations.yaml

Version: **0.1.513-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66bc50d434cb03f08a15fe8d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66bc50d234cb03f08a15fe88

operator test-e2e-operator-fbc (0.1.513-1)

---

operators/test-e2e-operator/0.1.513-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.513-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.513-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.513-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.513-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.513-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.513-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66bc50da34cb03f08a15fe98
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66bc50d7e2d4088fc42d9316

operator test-e2e-operator (0.1.513-1)

---

operators/test-e2e-community-operator/0.1.513-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.513-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.513-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.513-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.513-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.513-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.513-1)

operator test-e2e-community-operator (0.1.513-1)

---

operators/test-e2e-community-operator/0.1.514-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.514-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.514-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.514-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.514-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.514-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.514-1)

operator test-e2e-community-operator (0.1.514-1)

---

operators/test-e2e-operator-fbc/0.1.514-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.514-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.514-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.514-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.514-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.514-2/metadata/annotations.yaml

Version: **0.1.514-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66bdaa9ac261c5f9f7e0612b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66bdaa98c261c5f9f7e06126

operator test-e2e-operator-fbc (0.1.514-2)

---

operators/test-e2e-operator/0.1.514-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.514-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.514-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.514-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.514-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.514-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.514-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66bdaa84eb0bace25dffa1e3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66bdaa81eb0bace25dffa1e0

operator test-e2e-operator (0.1.514-2)

---

operators/test-e2e-operator-fbc/0.1.515-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.515-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.515-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.515-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.515-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.515-1/metadata/annotations.yaml

Version: **0.1.515-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66bdbdf3c261c5f9f7e061b1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66bdbdf1c261c5f9f7e061ac

operator test-e2e-operator-fbc (0.1.515-1)

---

operators/test-e2e-community-operator/0.1.515-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.515-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.515-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.515-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.515-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.515-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.515-1)

operator test-e2e-community-operator (0.1.515-1)

---

operators/test-e2e-operator/0.1.515-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.515-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.515-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.515-3/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.515-3/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.515-3/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.515-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66be1cc2c261c5f9f7e06314
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66be1cbfc261c5f9f7e0630f

operator test-e2e-operator (0.1.515-3)

---

operators/test-e2e-community-operator/0.1.516-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.516-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.516-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.516-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.516-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.516-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.516-1)

operator test-e2e-community-operator (0.1.516-1)

---

operators/test-e2e-operator-fbc/0.1.516-6/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.516-6/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.516-6/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.516-6/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.516-6/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.516-6/metadata/annotations.yaml

Version: **0.1.516-6**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c45aeb816f070e272f64b1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c45ae9816f070e272f64ae

operator test-e2e-operator-fbc (0.1.516-6)

---

operators/test-e2e-operator/0.1.516-6/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.516-6/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.516-6/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.516-6/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.516-6/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.516-6/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.516-6**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c45af7c261c5f9f7e0778c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c45af5816f070e272f64cb

operator test-e2e-operator (0.1.516-6)

---

operators/test-e2e-operator/0.1.517-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.517-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.517-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.517-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.517-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.517-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.517-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c47c4e816f070e272f65c7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c47c4b9b6164d0710a17cd

operator test-e2e-operator (0.1.517-1)

---

operators/test-e2e-operator/0.1.518-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.518-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.518-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.518-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.518-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.518-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.518-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c48caf9b6164d0710a1851
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c48cac9b6164d0710a184e

operator test-e2e-operator (0.1.518-1)

---

operators/test-e2e-operator/0.1.519-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.519-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.519-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.519-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.519-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.519-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.519-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c4fa46816f070e272f6765
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c4fa389b6164d0710a19ce

operator test-e2e-operator (0.1.519-2)

---

operators/test-e2e-community-operator/0.1.519-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.519-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.519-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.519-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.519-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.519-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.519-2)

operator test-e2e-community-operator (0.1.519-2)

---

operators/test-e2e-operator/0.1.519-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.519-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.519-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.519-3/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.519-3/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.519-3/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.519-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c584fb816f070e272f690c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c584f9816f070e272f6907

operator test-e2e-operator (0.1.519-3)

---

operators/test-e2e-operator-fbc/0.1.151-118/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.151-118/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.151-118/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.151-118/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.151-118/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.151-118/metadata/annotations.yaml

Version: **0.1.151-118**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c5b392816f070e272f6a21
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c5b3909b6164d0710a1c72

operator test-e2e-operator-fbc (0.1.151-118)

---

operators/test-e2e-operator/0.1.520-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.520-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.520-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.520-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.520-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.520-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.520-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c5ce6e9b6164d0710a1d1d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c5ce6c9b6164d0710a1d1a

operator test-e2e-operator (0.1.520-1)

---

operators/test-e2e-community-operator/0.1.520-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.520-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.520-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.520-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.520-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.520-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.520-1)

operator test-e2e-community-operator (0.1.520-1)

---

operators/test-e2e-operator-fbc/0.1.520-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.520-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.520-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.520-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.520-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.520-2/metadata/annotations.yaml

Version: **0.1.520-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c5e035816f070e272f6b2b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c5e032816f070e272f6b26

operator test-e2e-operator-fbc (0.1.520-2)

---

operators/test-e2e-operator-fbc/0.1.521-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.521-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.521-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.521-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.521-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.521-1/metadata/annotations.yaml

Version: **0.1.521-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c5f52b9b6164d0710a1dd6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c5f5289b6164d0710a1dd1

operator test-e2e-operator-fbc (0.1.521-1)

---

operators/test-e2e-operator/0.1.521-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.521-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.521-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.521-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.521-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.521-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.521-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c5f5469b6164d0710a1de9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c5f544816f070e272f6b7d

operator test-e2e-operator (0.1.521-1)

---

operators/test-e2e-community-operator/0.1.521-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.521-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.521-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.521-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.521-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.521-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.521-1)

operator test-e2e-community-operator (0.1.521-1)

---

operators/test-e2e-operator/0.1.521-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.521-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.521-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.521-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.521-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.521-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.521-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c64e7e1997afc545986690
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c64e7b248e6b70a6bf362a

operator test-e2e-operator (0.1.521-2)

---

operators/test-e2e-operator-fbc/0.1.151-128/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.151-128/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.151-128/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.151-128/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.151-128/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.151-128/metadata/annotations.yaml

Version: **0.1.151-128**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66c71d141997afc545986a0d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66c71d121997afc545986a08

operator test-e2e-operator-fbc (0.1.151-128)

---

operators/test-e2e-operator-fbc/0.1.522-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.522-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.522-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.522-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.522-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.522-1/metadata/annotations.yaml

Version: **0.1.522-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66cc288f1997afc545987844
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66cc288c248e6b70a6bf47d3

operator test-e2e-operator-fbc (0.1.522-1)

---

operators/test-e2e-operator/0.1.522-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.522-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.522-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.522-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.522-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.522-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.522-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66cc286c1997afc54598782e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66cc286b1997afc545987829

operator test-e2e-operator (0.1.522-1)

---

operators/test-e2e-community-operator/0.1.522-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.522-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.522-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.522-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.522-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.522-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.522-1)

operator test-e2e-community-operator (0.1.522-1)

---

operators/test-e2e-operator-fbc/0.1.523-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.523-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.523-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.523-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.523-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.523-1/metadata/annotations.yaml

Version: **0.1.523-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66cdd288ad2ad9fb013a9a9e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66cdd285caeda517256b4066

operator test-e2e-operator-fbc (0.1.523-1)

---

operators/test-e2e-operator/0.1.523-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.523-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.523-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.523-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.523-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.523-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.523-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66cdd235ad2ad9fb013a9a8e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66cdd233ad2ad9fb013a9a8b

operator test-e2e-operator (0.1.523-1)

---

operators/test-e2e-community-operator/0.1.523-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.523-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.523-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.523-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.523-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.523-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.523-1)

operator test-e2e-community-operator (0.1.523-1)

---

operators/test-e2e-operator-fbc/0.1.524-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.524-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.524-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.524-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.524-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.524-1/metadata/annotations.yaml

Version: **0.1.524-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66cf1061caeda517256b4573
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66cf105ead2ad9fb013a9fd1

operator test-e2e-operator-fbc (0.1.524-1)

---

operators/test-e2e-community-operator/0.1.524-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.524-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.524-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.524-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.524-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.524-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.524-1)

operator test-e2e-community-operator (0.1.524-1)

---

operators/test-e2e-operator/0.1.524-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.524-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.524-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.524-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.524-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.524-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.524-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66d019a7c7bf58c621433900
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66d019a4c7bf58c6214338fd

operator test-e2e-operator (0.1.524-2)

---

operators/test-e2e-operator-fbc/0.1.525-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.525-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.525-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.525-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.525-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.525-1/metadata/annotations.yaml

Version: **0.1.525-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66d6ecba42749b2c4e30816d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66d6ecb8c7bf58c621435176

operator test-e2e-operator-fbc (0.1.525-1)

---

operators/test-e2e-operator/0.1.525-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.525-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.525-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.525-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.525-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.525-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.525-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66d6ecadc7bf58c621435167
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66d6ecab42749b2c4e308155

operator test-e2e-operator (0.1.525-1)

---

operators/test-e2e-community-operator/0.1.525-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.525-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.525-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.525-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.525-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.525-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.525-1)

operator test-e2e-community-operator (0.1.525-1)

---

operators/test-e2e-operator-fbc/0.1.525-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.525-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.525-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.525-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.525-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.525-2/metadata/annotations.yaml

Version: **0.1.525-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66d84c0587eba1a8667a4b61
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66d84c0287eba1a8667a4b5c

operator test-e2e-operator-fbc (0.1.525-2)

---

operators/test-e2e-community-operator/0.1.1-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.1-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.1-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.1-4/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.1-4/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.1-4/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.1-4)

operator test-e2e-community-operator (0.1.1-4)

---

operators/test-e2e-operator-fbc/0.1.526-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.526-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.526-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.526-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.526-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.526-1/metadata/annotations.yaml

Version: **0.1.526-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66d9c25616ea35f368ad5a45
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66d9c25487eba1a8667a51f9

operator test-e2e-operator-fbc (0.1.526-1)

---

operators/test-e2e-operator/0.1.526-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.526-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.526-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.526-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.526-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.526-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.526-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66d9c24916ea35f368ad5a3a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66d9c24687eba1a8667a51dd

operator test-e2e-operator (0.1.526-1)

---

operators/test-e2e-community-operator/0.1.526-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.526-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.526-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.526-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.526-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.526-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.526-1)

operator test-e2e-community-operator (0.1.526-1)

---

operators/test-e2e-operator-fbc/0.1.526-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.526-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.526-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.526-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.526-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.526-2/metadata/annotations.yaml

Version: **0.1.526-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66df01f687eba1a8667a6384
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66df01f487eba1a8667a6381

operator test-e2e-operator-fbc (0.1.526-2)

---

operators/test-e2e-operator-fbc/0.1.527-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.527-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.527-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.527-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.527-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.527-1/metadata/annotations.yaml

Version: **0.1.527-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66dfec23992c4a393fa9bbb0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66dfec20b746e891051ead0e

operator test-e2e-operator-fbc (0.1.527-1)

---

operators/test-e2e-operator/0.1.527-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.527-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.527-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.527-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.527-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.527-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.527-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66dfec23b746e891051ead16
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66dfec21b746e891051ead11

operator test-e2e-operator (0.1.527-1)

---

operators/test-e2e-community-operator/0.1.527-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.527-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.527-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.527-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.527-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.527-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.527-1)

operator test-e2e-community-operator (0.1.527-1)

---

operators/test-e2e-operator-fbc/0.1.528-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.528-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.528-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.528-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.528-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.528-1/metadata/annotations.yaml

Version: **0.1.528-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e03711b746e891051eaf29
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e0370eb746e891051eaf24

operator test-e2e-operator-fbc (0.1.528-1)

---

operators/test-e2e-community-operator/0.1.529-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.529-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.529-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.529-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.529-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.529-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.529-1)

operator test-e2e-community-operator (0.1.529-1)

---

operators/test-e2e-community-operator/0.1.1-11/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.1-11/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.1-11/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.1-11/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.1-11/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.1-11/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.1-11)

operator test-e2e-community-operator (0.1.1-11)

---

operators/test-e2e-operator/0.1.530-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.530-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.530-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.530-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.530-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.530-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.530-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e1aaa7b746e891051eb4bb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e1aaa3992c4a393fa9c391

operator test-e2e-operator (0.1.530-1)

---

operators/test-e2e-community-operator/0.1.530-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.530-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.530-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.530-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.530-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.530-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.530-1)

operator test-e2e-community-operator (0.1.530-1)

---

operators/test-e2e-community-operator/0.1.1-77/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.1-77/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.1-77/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.1-77/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.1-77/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.1-77/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.1-77)

operator test-e2e-community-operator (0.1.1-77)

---

operators/test-e2e-operator-fbc/0.1.1-78/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.1-78/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.1-78/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.1-78/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.1-78/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.1-78/metadata/annotations.yaml

Version: **0.1.1-78**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e2d05262f59a305642a607
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e2d05162f59a305642a602

operator test-e2e-operator-fbc (0.1.1-78)

---

operators/test-e2e-operator-fbc/0.1.531-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.531-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.531-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.531-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.531-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.531-1/metadata/annotations.yaml

Version: **0.1.531-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e304af083ecb919a38d48b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e304ac62f59a305642a695

operator test-e2e-operator-fbc (0.1.531-1)

---

operators/test-e2e-operator/0.1.531-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.531-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.531-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.531-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.531-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.531-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.531-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e304b862f59a305642a6ad
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e304b662f59a305642a6a8

operator test-e2e-operator (0.1.531-1)

---

operators/test-e2e-operator-fbc/0.1.532-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.1.532-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.1.532-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.1.532-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.1.532-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.1.532-1/metadata/annotations.yaml

Version: **0.1.532-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e309ae083ecb919a38d4db
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e309ab62f59a305642a6dc

operator test-e2e-operator-fbc (0.1.532-1)

---

operators/test-e2e-community-operator/0.1.531-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.531-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.531-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.531-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.531-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.531-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.531-1)

operator test-e2e-community-operator (0.1.531-1)

---

operators/test-e2e-operator/0.1.532-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.532-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.532-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.532-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.532-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.532-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.532-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e3099d62f59a305642a6d1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e3099b083ecb919a38d4bf

operator test-e2e-operator (0.1.532-1)

---

operators/test-e2e-operator/0.1.532-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.532-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.532-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.532-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.532-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.532-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.532-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e3f812083ecb919a38d7e7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e3f80f083ecb919a38d7e4

operator test-e2e-operator (0.1.532-2)

---

operators/test-e2e-community-operator/0.1.532-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.532-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.532-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.532-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.532-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.532-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.532-2)

operator test-e2e-community-operator (0.1.532-2)

---

operators/test-e2e-operator/0.1.533-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.533-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.533-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.533-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.533-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.533-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.533-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e7d422083ecb919a38e3d7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e7d41f62f59a305642b530

operator test-e2e-operator (0.1.533-1)

---

operators/test-e2e-operator-fbc/0.0.1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.0.1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.0.1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.0.1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.0.1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.0.1/metadata/annotations.yaml

Version: **0.0.1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e7d8ff083ecb919a38e3fa
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e7d8fe62f59a305642b54d

operator test-e2e-operator-fbc (0.0.1)

---

operators/test-e2e-community-operator/0.1.533-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.533-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.533-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.533-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.533-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.533-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.533-1)

operator test-e2e-community-operator (0.1.533-1)

---

operators/test-e2e-community-operator/0.0.1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.0.1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.0.1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.0.1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.0.1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.0.1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.0.1)

operator test-e2e-community-operator (0.0.1)

---

operators/test-e2e-operator/0.1.534-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.534-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.534-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.534-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.534-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.534-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.534-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e82439083ecb919a38e83b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e82436083ecb919a38e838

operator test-e2e-operator (0.1.534-1)

---

operators/test-e2e-community-operator/0.1.534-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.1.534-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.1.534-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.1.534-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.1.534-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.1.534-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.1.534-1)

operator test-e2e-community-operator (0.1.534-1)

---

operators/test-e2e-community-operator/0.2.15-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.15-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.15-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.15-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.15-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.15-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.15-1)

operator test-e2e-community-operator (0.2.15-1)

---

operators/test-e2e-operator/0.2.15-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.15-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.15-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.15-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.15-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.15-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.15-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e84a38083ecb919a38e8fa
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e84a3662f59a305642b9ee

operator test-e2e-operator (0.2.15-2)

---

operators/test-e2e-operator-fbc/0.2.17-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.17-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.17-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.17-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.17-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.17-1/metadata/annotations.yaml

Version: **0.2.17-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e87de8e06d3bb2de7872c6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e87de5e06d3bb2de7872be

operator test-e2e-operator-fbc (0.2.17-1)

---

operators/test-e2e-operator/0.2.17-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.17-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.17-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.17-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.17-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.17-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.17-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e87de9e06d3bb2de7872cb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e87de7e06d3bb2de7872c1

operator test-e2e-operator (0.2.17-1)

---

operators/test-e2e-community-operator/0.2.17-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.17-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.17-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.17-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.17-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.17-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.17-1)

operator test-e2e-community-operator (0.2.17-1)

---

operators/test-e2e-operator-fbc/0.2.18-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.18-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.18-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.18-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.18-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.18-1/metadata/annotations.yaml

Version: **0.2.18-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e9d584d31eddbfbfad0df7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e9d581d31eddbfbfad0ded

operator test-e2e-operator-fbc (0.2.18-1)

---

operators/test-e2e-operator/0.2.18-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.18-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.18-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.18-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.18-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.18-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.18-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66e9d57dd31eddbfbfad0de6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66e9d57be06d3bb2de787734

operator test-e2e-operator (0.2.18-1)

---

operators/test-e2e-community-operator/0.2.18-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.18-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.18-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.18-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.18-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.18-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.18-1)

operator test-e2e-community-operator (0.2.18-1)

---

operators/test-e2e-operator/0.2.18-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.18-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.18-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.18-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.18-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.18-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.18-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ea8367d31eddbfbfad1041
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ea8365d31eddbfbfad103c

operator test-e2e-operator (0.2.18-2)

---

operators/test-e2e-operator-fbc/0.2.21-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.21-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.21-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.21-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.21-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.21-1/metadata/annotations.yaml

Version: **0.2.21-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ebf7c7e06d3bb2de787eda
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ebf7c4e06d3bb2de787ed5

operator test-e2e-operator-fbc (0.2.21-1)

---

operators/test-e2e-operator/0.2.21-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.21-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.21-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.21-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.21-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.21-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.21-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ebf7d2d31eddbfbfad15f0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ebf7cfe06d3bb2de787ee5

operator test-e2e-operator (0.2.21-1)

---

operators/test-e2e-community-operator/0.2.21-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.21-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.21-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.21-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.21-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.21-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.21-1)

operator test-e2e-community-operator (0.2.21-1)

---

operators/test-e2e-operator/0.2.22-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.22-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.22-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.22-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.22-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.22-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.22-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ec12c4d31eddbfbfad1725
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ec12c3e06d3bb2de788038

operator test-e2e-operator (0.2.22-1)

---

operators/test-e2e-operator-fbc/0.2.22-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.22-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.22-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.22-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.22-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.22-2/metadata/annotations.yaml

Version: **0.2.22-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ec873ee06d3bb2de788199
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ec873cd31eddbfbfad18b1

operator test-e2e-operator-fbc (0.2.22-2)

---

operators/test-e2e-community-operator/0.2.22-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.22-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.22-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.22-3/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.22-3/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.22-3/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.22-3)

operator test-e2e-community-operator (0.2.22-3)

---

operators/test-e2e-operator-fbc/0.2.25-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.25-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.25-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.25-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.25-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.25-1/metadata/annotations.yaml

Version: **0.2.25-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ed7b2cd31eddbfbfad1e16
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ed7b2ae06d3bb2de788678

operator test-e2e-operator-fbc (0.2.25-1)

---

operators/test-e2e-operator/0.2.25-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.25-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.25-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.25-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.25-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.25-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.25-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ed7b35e06d3bb2de78868c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ed7b33e06d3bb2de788688

operator test-e2e-operator (0.2.25-1)

---

operators/test-e2e-community-operator/0.2.25-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.25-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.25-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.25-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.25-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.25-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.25-1)

operator test-e2e-community-operator (0.2.25-1)

---

operators/test-e2e-operator-fbc/0.2.28-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.28-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.28-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.28-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.28-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.28-1/metadata/annotations.yaml

Version: **0.2.28-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66f3fef3c5567d8f215eca64
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66f3fef1705398a189bbbe71

operator test-e2e-operator-fbc (0.2.28-1)

---

operators/test-e2e-operator/0.2.28-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.28-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.28-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.28-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.28-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.28-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.28-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66f3fee9705398a189bbbe5c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66f3fee7705398a189bbbe57

operator test-e2e-operator (0.2.28-1)

---

operators/test-e2e-community-operator/0.2.28-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.28-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.28-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.28-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.28-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.28-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.28-1)

operator test-e2e-community-operator (0.2.28-1)

---

operators/test-e2e-community-operator/0.2.28-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.28-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.28-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.28-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.28-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.28-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.28-2)

operator test-e2e-community-operator (0.2.28-2)

---

operators/test-e2e-operator-fbc/0.2.29-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.29-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.29-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.29-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.29-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.29-1/metadata/annotations.yaml

Version: **0.2.29-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66f41b67705398a189bbbedb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66f41b64c5567d8f215ecac5

operator test-e2e-operator-fbc (0.2.29-1)

---

operators/test-e2e-operator/0.2.29-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.29-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.29-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.29-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.29-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.29-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.29-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66f41b90705398a189bbbef6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66f41b8ec5567d8f215ecad7

operator test-e2e-operator (0.2.29-1)

---

operators/test-e2e-community-operator/0.2.29-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.29-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.29-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.29-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.29-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.29-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.29-1)

operator test-e2e-community-operator (0.2.29-1)

---

operators/test-e2e-operator-fbc/0.2.30-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.30-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.30-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.30-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.30-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.30-1/metadata/annotations.yaml

Version: **0.2.30-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66f51f20579e86b21388ad7d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66f51f1d92cf511ae9927205

operator test-e2e-operator-fbc (0.2.30-1)

---

operators/test-e2e-operator/0.2.30-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.30-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.30-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.30-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.30-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.30-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.30-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66f51f1192cf511ae99271f2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66f51f0e92cf511ae99271ef

operator test-e2e-operator (0.2.30-1)

---

operators/test-e2e-community-operator/0.2.30-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.30-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.30-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.30-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.30-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.30-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.30-1)

operator test-e2e-community-operator (0.2.30-1)

---

operators/test-e2e-operator-fbc/0.2.32-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.32-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.32-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.32-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.32-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.32-1/metadata/annotations.yaml

Version: **0.2.32-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66f54419579e86b21388af0b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66f54416579e86b21388af06

operator test-e2e-operator-fbc (0.2.32-1)

---

operators/test-e2e-operator/0.2.32-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.32-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.32-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.32-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.32-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.32-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.32-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66f5441f92cf511ae99273c9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66f5441c92cf511ae99273bd

operator test-e2e-operator (0.2.32-1)

---

operators/test-e2e-community-operator/0.2.32-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.32-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.32-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.32-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.32-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.32-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.32-1)

operator test-e2e-community-operator (0.2.32-1)

---

operators/test-e2e-operator-fbc/0.2.33-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.33-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.33-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.33-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.33-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.33-1/metadata/annotations.yaml

Version: **0.2.33-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66fcf32d92cf511ae992915c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66fcf32b92cf511ae9929159

operator test-e2e-operator-fbc (0.2.33-1)

---

operators/test-e2e-operator/0.2.33-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.33-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.33-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.33-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.33-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.33-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.33-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66fcf31f92cf511ae992914a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66fcf31d579e86b21388cc13

operator test-e2e-operator (0.2.33-1)

---

operators/test-e2e-community-operator/0.2.33-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.33-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.33-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.33-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.33-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.33-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.33-1)

operator test-e2e-community-operator (0.2.33-1)

---

operators/test-e2e-operator-fbc/0.2.37-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.37-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.37-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.37-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.37-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.37-1/metadata/annotations.yaml

Version: **0.2.37-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ffa650118654e988ca7fbb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ffa64e3bd9eb18d7558432

operator test-e2e-operator-fbc (0.2.37-1)

---

operators/test-e2e-operator/0.2.37-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.37-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.37-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.37-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.37-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.37-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.37-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/66ffa61c3bd9eb18d755841c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/66ffa61a3bd9eb18d7558419

operator test-e2e-operator (0.2.37-1)

---

operators/test-e2e-community-operator/0.2.37-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.37-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.37-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.37-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.37-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.37-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.37-1)

operator test-e2e-community-operator (0.2.37-1)

---

operators/test-e2e-operator-fbc/0.2.38-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.38-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.38-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.38-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.38-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.38-1/metadata/annotations.yaml

Version: **0.2.38-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67038e2e3bd9eb18d755931d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67038e2c3bd9eb18d755931a

operator test-e2e-operator-fbc (0.2.38-1)

---

operators/test-e2e-operator/0.2.38-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.38-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.38-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.38-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.38-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.38-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.38-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67038de73bd9eb18d7559309
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67038de5118654e988ca8ef9

operator test-e2e-operator (0.2.38-1)

---

operators/test-e2e-community-operator/0.2.38-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.38-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.38-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.38-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.38-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.38-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.38-1)

operator test-e2e-community-operator (0.2.38-1)

---

operators/test-e2e-operator-fbc/0.2.41-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.41-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.41-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.41-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.41-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.41-1/metadata/annotations.yaml

Version: **0.2.41-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6703ee2a118654e988ca91dd
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6703ee28118654e988ca91d8

operator test-e2e-operator-fbc (0.2.41-1)

---

operators/test-e2e-operator/0.2.41-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.41-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.41-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.41-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.41-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.41-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.41-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6703ee19118654e988ca91c6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6703ee17118654e988ca91c1

operator test-e2e-operator (0.2.41-1)

---

operators/test-e2e-community-operator/0.2.41-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.41-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.41-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.41-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.41-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.41-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.41-1)

operator test-e2e-community-operator (0.2.41-1)

---

operators/test-e2e-operator/0.2.42-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.42-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.42-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.42-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.42-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.42-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.42-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6703f278118654e988ca921d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6703f276118654e988ca921a

operator test-e2e-operator (0.2.42-1)

---

operators/test-e2e-community-operator/0.2.42-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.42-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.42-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.42-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.42-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.42-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.42-1)

operator test-e2e-community-operator (0.2.42-1)

---

operators/test-e2e-operator-fbc/0.2.42-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.42-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.42-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.42-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.42-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.42-2/metadata/annotations.yaml

Version: **0.2.42-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/670401a517d5f2e05aa9df40
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/670401a117d5f2e05aa9df3d

operator test-e2e-operator-fbc (0.2.42-2)

---

operators/test-e2e-operator-fbc/0.2.45-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.45-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.45-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.45-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.45-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.45-1/metadata/annotations.yaml

Version: **0.2.45-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67041049cb6ac3fc3a6c0d40
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67041046cb6ac3fc3a6c0d3d

operator test-e2e-operator-fbc (0.2.45-1)

---

operators/test-e2e-operator/0.2.45-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.45-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.45-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.45-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.45-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.45-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.45-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6704105fcb6ac3fc3a6c0d59
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6704105ccb6ac3fc3a6c0d54

operator test-e2e-operator (0.2.45-1)

---

operators/test-e2e-community-operator/0.2.45-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.45-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.45-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.45-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.45-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.45-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.45-1)

operator test-e2e-community-operator (0.2.45-1)

---

operators/test-e2e-operator-fbc/0.2.46-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.46-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.46-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.46-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.46-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.46-1/metadata/annotations.yaml

Version: **0.2.46-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/670448a8cb6ac3fc3a6c0dfd
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/670448a5cb6ac3fc3a6c0df8

operator test-e2e-operator-fbc (0.2.46-1)

---

operators/test-e2e-operator/0.2.46-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.46-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.46-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.46-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.46-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.46-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.46-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/670448b4cb6ac3fc3a6c0e0d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/670448b1cb6ac3fc3a6c0e0a

operator test-e2e-operator (0.2.46-1)

---

operators/test-e2e-community-operator/0.2.46-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.46-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.46-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.46-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.46-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.46-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.46-1)

operator test-e2e-community-operator (0.2.46-1)

---

operators/test-e2e-operator-fbc/0.2.51-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.51-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.51-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.51-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.51-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.51-1/metadata/annotations.yaml

Version: **0.2.51-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/670e2cca15be562ee23dd265
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/670e2cc8b66099edb2e6555b

operator test-e2e-operator-fbc (0.2.51-1)

---

operators/test-e2e-operator/0.2.51-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.51-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.51-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.51-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.51-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.51-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.51-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/670e2d36b66099edb2e6556b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/670e2d3315be562ee23dd283

operator test-e2e-operator (0.2.51-1)

---

operators/test-e2e-community-operator/0.2.51-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.51-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.51-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.51-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.51-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.51-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.51-1)

operator test-e2e-community-operator (0.2.51-1)

---

operators/test-e2e-operator-fbc/0.2.51-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.51-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.51-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.51-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.51-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.51-2/metadata/annotations.yaml

Version: **0.2.51-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/670e4277b66099edb2e655db
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/670e4274b66099edb2e655d6

operator test-e2e-operator-fbc (0.2.51-2)

---

operators/test-e2e-operator/0.2.51-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.51-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.51-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.51-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.51-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.51-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.51-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/670e427db66099edb2e655f3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/670e427ab66099edb2e655e5

operator test-e2e-operator (0.2.51-2)

---

operators/test-e2e-community-operator/0.2.51-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.51-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.51-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.51-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.51-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.51-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.51-2)

operator test-e2e-community-operator (0.2.51-2)

---

operators/test-e2e-operator/0.2.69-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.69-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.69-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.69-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.69-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.69-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.69-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/670fe74849ef19cf3a3fb04f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/670fe745f9fce75c64be6aaf

operator test-e2e-operator (0.2.69-1)

---

operators/test-e2e-community-operator/0.2.69-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.69-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.69-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.69-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.69-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.69-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.69-1)

operator test-e2e-community-operator (0.2.69-1)

---

operators/test-e2e-community-operator/0.2.73-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.73-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.73-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.73-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.73-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.73-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.73-1)

operator test-e2e-community-operator (0.2.73-1)

---

operators/test-e2e-operator-fbc/0.2.79-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.79-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.79-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.79-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.79-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.79-1/metadata/annotations.yaml

Version: **0.2.79-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67100916f9fce75c64be6b8e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6710091449ef19cf3a3fb0df

operator test-e2e-operator-fbc (0.2.79-1)

---

operators/test-e2e-community-operator/0.2.79-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.79-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.79-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.79-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.79-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.79-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.79-1)

operator test-e2e-community-operator (0.2.79-1)

---

operators/test-e2e-operator/0.2.79-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.79-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.79-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.79-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.79-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.79-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.79-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6710161549ef19cf3a3fb125
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67101612f9fce75c64be6bcd

operator test-e2e-operator (0.2.79-2)

---

operators/test-e2e-operator-fbc/0.2.81-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.81-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.81-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.81-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.81-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.81-1/metadata/annotations.yaml

Version: **0.2.81-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6710eb5d49ef19cf3a3fb5d1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6710eb5bf9fce75c64be70a9

operator test-e2e-operator-fbc (0.2.81-1)

---

operators/test-e2e-operator/0.2.81-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.81-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.81-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.81-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.81-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.81-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.81-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6710eb29f9fce75c64be7092
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6710eb2749ef19cf3a3fb5bb

operator test-e2e-operator (0.2.81-1)

---

operators/test-e2e-operator-fbc/0.2.83-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.83-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.83-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.83-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.83-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.83-1/metadata/annotations.yaml

Version: **0.2.83-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6711153d49ef19cf3a3fb6ac
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6711153af9fce75c64be7177

operator test-e2e-operator-fbc (0.2.83-1)

---

operators/test-e2e-operator/0.2.83-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.83-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.83-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.83-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.83-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.83-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.83-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67111543f9fce75c64be7192
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6711154149ef19cf3a3fb6b4

operator test-e2e-operator (0.2.83-1)

---

operators/test-e2e-operator-fbc/0.2.85-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.85-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.85-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.85-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.85-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.85-1/metadata/annotations.yaml

Version: **0.2.85-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6712237cf9fce75c64be7601
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6712237af9fce75c64be75fc

operator test-e2e-operator-fbc (0.2.85-1)

---

operators/test-e2e-operator/0.2.85-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.85-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.85-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.85-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.85-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.85-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.85-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/671223ae49ef19cf3a3fbb6d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/671223acf9fce75c64be7618

operator test-e2e-operator (0.2.85-1)

---

operators/test-e2e-community-operator/0.2.85-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.85-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.85-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.85-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.85-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.85-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.85-1)

operator test-e2e-community-operator (0.2.85-1)

---

operators/test-e2e-operator-fbc/0.2.87-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.87-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.87-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.87-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.87-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.87-1/metadata/annotations.yaml

Version: **0.2.87-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/671233f449ef19cf3a3fbbfb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/671233f2f9fce75c64be76a5

operator test-e2e-operator-fbc (0.2.87-1)

---

operators/test-e2e-operator/0.2.87-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.87-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.87-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.87-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.87-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.87-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.87-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/671233d4f9fce75c64be7689
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/671233d249ef19cf3a3fbbea

operator test-e2e-operator (0.2.87-1)

---

operators/test-e2e-operator-fbc/0.2.73-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.73-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.73-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.73-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.73-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.73-2/metadata/annotations.yaml

Version: **0.2.73-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6712635a49ef19cf3a3fbd61
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6712635849ef19cf3a3fbd5e

operator test-e2e-operator-fbc (0.2.73-2)

---

operators/test-e2e-operator/0.2.88-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.88-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.88-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.88-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.88-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.88-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.88-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6712701ef9fce75c64be7831
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6712701cf9fce75c64be782e

operator test-e2e-operator (0.2.88-1)

---

operators/test-e2e-community-operator/0.2.88-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.88-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.88-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.88-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.88-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.88-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.88-1)

operator test-e2e-community-operator (0.2.88-1)

---

operators/test-e2e-operator-fbc/0.2.89-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.89-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.89-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.89-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.89-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.89-1/metadata/annotations.yaml

Version: **0.2.89-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6712895b49ef19cf3a3fbe21
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67128958f9fce75c64be789f

operator test-e2e-operator-fbc (0.2.89-1)

---

operators/test-e2e-operator/0.2.89-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.89-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.89-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.89-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.89-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.89-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.89-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67128958f9fce75c64be789c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67128955f9fce75c64be7899

operator test-e2e-operator (0.2.89-1)

---

operators/test-e2e-community-operator/0.2.89-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.89-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.89-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.89-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.89-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.89-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.89-1)

operator test-e2e-community-operator (0.2.89-1)

---

operators/test-e2e-operator-fbc/0.2.88-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.88-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.88-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.88-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.88-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.88-2/metadata/annotations.yaml

Version: **0.2.88-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67129546f9fce75c64be78eb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67129544f9fce75c64be78e8

operator test-e2e-operator-fbc (0.2.88-2)

---

operators/test-e2e-operator-fbc/0.2.94-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.94-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.94-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.94-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.94-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.94-1/metadata/annotations.yaml

Version: **0.2.94-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6721f9387d40cd642f1895fe
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6721f9357d40cd642f1895fb

operator test-e2e-operator-fbc (0.2.94-1)

---

operators/test-e2e-operator/0.2.94-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.94-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.94-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.94-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.94-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.94-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.94-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6721f92b90dd760b7062b680
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6721f92990dd760b7062b67b

operator test-e2e-operator (0.2.94-1)

---

operators/test-e2e-community-operator/0.2.94-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.94-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.94-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.94-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.94-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.94-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.94-1)

operator test-e2e-community-operator (0.2.94-1)

---

operators/test-e2e-operator-fbc/0.2.96-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.96-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.96-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.96-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.96-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.96-1/metadata/annotations.yaml

Version: **0.2.96-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67249dd62cb77ae4934e7645
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67249dd42cb77ae4934e7640

operator test-e2e-operator-fbc (0.2.96-1)

---

operators/test-e2e-operator/0.2.96-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.96-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.96-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.96-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.96-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.96-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.96-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67249dd32cb77ae4934e763d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67249dd1603c5ff8c0ef0916

operator test-e2e-operator (0.2.96-1)

---

operators/test-e2e-community-operator/0.2.96-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.96-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.96-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.96-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.96-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.96-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.96-1)

operator test-e2e-community-operator (0.2.96-1)

---

operators/test-e2e-community-operator/0.2.101-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.101-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.101-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.101-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.101-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.101-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.101-1)

operator test-e2e-community-operator (0.2.101-1)

---

operators/test-e2e-operator-fbc/0.2.101-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.101-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.101-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.101-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.101-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.101-2/metadata/annotations.yaml

Version: **0.2.101-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/672b51cb86572cefdd684811
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/672b51caef308bd533200d17

operator test-e2e-operator-fbc (0.2.101-2)

---

operators/test-e2e-operator-fbc/0.2.102-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.102-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.102-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.102-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.102-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.102-1/metadata/annotations.yaml

Version: **0.2.102-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/672b9561ab45acaa29592f9f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/672b955f55aead05c5da3265

operator test-e2e-operator-fbc (0.2.102-1)

---

operators/test-e2e-operator/0.2.102-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.102-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.102-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.102-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.102-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.102-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.102-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/672b955455aead05c5da3256
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/672b955155aead05c5da3251

operator test-e2e-operator (0.2.102-1)

---

operators/test-e2e-community-operator/0.2.102-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.102-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.102-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.102-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.102-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.102-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.102-1)

operator test-e2e-community-operator (0.2.102-1)

---

operators/test-e2e-operator-fbc/0.2.104-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.104-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.104-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.104-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.104-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.104-1/metadata/annotations.yaml

Version: **0.2.104-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/672de74dab45acaa295939b1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/672de74bab45acaa295939ae

operator test-e2e-operator-fbc (0.2.104-1)

---

operators/test-e2e-operator/0.2.104-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.104-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.104-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.104-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.104-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.104-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.104-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/672de751ab45acaa295939be
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/672de74e55aead05c5da3bcf

operator test-e2e-operator (0.2.104-1)

---

operators/test-e2e-community-operator/0.2.104-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.104-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.104-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.104-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.104-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.104-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.104-1)

operator test-e2e-community-operator (0.2.104-1)

---

operators/test-e2e-operator-fbc/0.2.110-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.110-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.110-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.110-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.110-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.110-1/metadata/annotations.yaml

Version: **0.2.110-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6733295cc709e0dc93edad39
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6733295a7b16d65901bcb98b

operator test-e2e-operator-fbc (0.2.110-1)

---

operators/test-e2e-operator/0.2.110-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.110-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.110-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.110-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.110-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.110-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.110-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67332932c709e0dc93edad2d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/673329307b16d65901bcb968

operator test-e2e-operator (0.2.110-1)

---

operators/test-e2e-community-operator/0.2.110-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.110-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.110-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.110-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.110-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.110-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.110-1)

operator test-e2e-community-operator (0.2.110-1)

---

operators/test-e2e-community-operator/0.2.113-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.113-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.113-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.113-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.113-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.113-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.113-1)

operator test-e2e-community-operator (0.2.113-1)

---

operators/test-e2e-operator-fbc/0.2.115-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.115-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.115-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.115-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.115-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.115-1/metadata/annotations.yaml

Version: **0.2.115-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/674711fe22d00e2713401e2b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/674711fc22d00e2713401e28

operator test-e2e-operator-fbc (0.2.115-1)

---

operators/test-e2e-operator/0.2.115-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.115-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.115-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.115-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.115-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.115-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.115-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/674711f222d00e2713401e12
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/674711f0f0d75710ef025d79

operator test-e2e-operator (0.2.115-1)

---

operators/test-e2e-operator-fbc/0.2.116-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.116-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.116-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.116-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.116-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.116-1/metadata/annotations.yaml

Version: **0.2.116-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/674da0e84023ad27c8bdc276
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/674da0e54023ad27c8bdc271

operator test-e2e-operator-fbc (0.2.116-1)

---

operators/test-e2e-operator/0.2.116-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.116-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.116-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.116-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.116-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.116-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.116-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/674da0cc4023ad27c8bdc263
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/674da0c9aeb185c6e93d1b89

operator test-e2e-operator (0.2.116-1)

---

operators/test-e2e-community-operator/0.2.116-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.116-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.116-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.116-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.116-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.116-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.116-1)

operator test-e2e-community-operator (0.2.116-1)

---

operators/test-e2e-operator-fbc/0.2.122-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.122-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.122-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.122-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.122-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.122-1/metadata/annotations.yaml

Version: **0.2.122-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6750788caeb185c6e93d29b2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6750788aaeb185c6e93d29ad

operator test-e2e-operator-fbc (0.2.122-1)

---

operators/test-e2e-operator/0.2.122-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.122-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.122-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.122-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.122-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.122-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.122-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/675078e84023ad27c8bdd081
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/675078e54023ad27c8bdd07c

operator test-e2e-operator (0.2.122-1)

---

operators/test-e2e-community-operator/0.2.122-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.122-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.122-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.122-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.122-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.122-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.122-1)

operator test-e2e-community-operator (0.2.122-1)

---

operators/test-e2e-community-operator/0.2.122-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.122-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.122-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.122-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.122-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.122-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.122-2)

operator test-e2e-community-operator (0.2.122-2)

---

operators/test-e2e-operator-fbc/0.2.123-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.123-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.123-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.123-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.123-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.123-1/metadata/annotations.yaml

Version: **0.2.123-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6751a6a23685b60bb491ee87
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6751a6a0b6ac8dcd1586d559

operator test-e2e-operator-fbc (0.2.123-1)

---

operators/test-e2e-community-operator/0.2.123-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.123-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.123-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.123-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.123-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.123-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.123-1)

operator test-e2e-community-operator (0.2.123-1)

---

operators/test-e2e-operator-fbc/0.2.127-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.127-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.127-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.127-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.127-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.127-1/metadata/annotations.yaml

Version: **0.2.127-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6756cb51b6ac8dcd1586eecd
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6756cb4e3685b60bb492082b

operator test-e2e-operator-fbc (0.2.127-1)

---

operators/test-e2e-operator/0.2.127-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.127-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.127-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.127-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.127-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.127-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.127-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6756cb63b6ac8dcd1586eee7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6756cb61b6ac8dcd1586eee2

operator test-e2e-operator (0.2.127-1)

---

operators/test-e2e-community-operator/0.2.127-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.127-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.127-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.127-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.127-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.127-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.127-1)

operator test-e2e-community-operator (0.2.127-1)

---

operators/test-e2e-community-operator/0.2.127-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.127-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.127-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.127-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.127-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.127-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.127-2)

operator test-e2e-community-operator (0.2.127-2)

---

operators/test-e2e-operator-fbc/0.2.129-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.129-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.129-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.129-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.129-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.129-1/metadata/annotations.yaml

Version: **0.2.129-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/675719913685b60bb49209d7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6757198f3685b60bb49209d4

operator test-e2e-operator-fbc (0.2.129-1)

---

operators/test-e2e-operator/0.2.129-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.129-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.129-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.129-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.129-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.129-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.129-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67571995b6ac8dcd1586f083
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/675719933685b60bb49209de

operator test-e2e-operator (0.2.129-1)

---

operators/test-e2e-community-operator/0.2.129-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.129-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.129-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.129-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.129-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.129-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.129-1)

operator test-e2e-community-operator (0.2.129-1)

---

operators/test-e2e-operator/0.2.132-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.132-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.132-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.132-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.132-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.132-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.132-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/675805dcf744f1023def0532
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/675805daf744f1023def052f

operator test-e2e-operator (0.2.132-1)

---

operators/test-e2e-community-operator/0.2.132-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.132-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.132-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.132-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.132-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.132-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.132-1)

operator test-e2e-community-operator (0.2.132-1)

---

operators/test-e2e-operator-fbc/0.2.140-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.140-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.140-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.140-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.140-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.140-1/metadata/annotations.yaml

Version: **0.2.140-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6759abf5f8e6179295ae7f46
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6759abf3f8e6179295ae7f43

operator test-e2e-operator-fbc (0.2.140-1)

---

operators/test-e2e-community-operator/0.2.140-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.140-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.140-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.140-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.140-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.140-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.140-1)

operator test-e2e-community-operator (0.2.140-1)

---

operators/test-e2e-operator-fbc/0.2.143-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.143-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.143-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.143-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.143-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.143-1/metadata/annotations.yaml

Version: **0.2.143-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6759d6e9f8e6179295ae7ff9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6759d6e7f8e6179295ae7ff4

operator test-e2e-operator-fbc (0.2.143-1)

---

operators/test-e2e-operator/0.2.143-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.143-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.143-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.143-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.143-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.143-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.143-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6759d68bf8e6179295ae7fe1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6759d688f8e6179295ae7fdc

operator test-e2e-operator (0.2.143-1)

---

operators/test-e2e-community-operator/0.2.143-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.143-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.143-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.143-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.143-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.143-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.143-1)

operator test-e2e-community-operator (0.2.143-1)

---

operators/test-e2e-community-operator/0.2.145-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.145-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.145-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.145-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.145-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.145-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.145-1)

operator test-e2e-community-operator (0.2.145-1)

---

operators/test-e2e-operator-fbc/0.2.145-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.145-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.145-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.145-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.145-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.145-2/metadata/annotations.yaml

Version: **0.2.145-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/675b65c4f744f1023def1572
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/675b65c2f8e6179295ae86f2

operator test-e2e-operator-fbc (0.2.145-2)

---

operators/test-e2e-operator/0.2.145-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.145-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.145-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.145-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.145-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.145-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.145-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/675b65acf8e6179295ae86e4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/675b65a9f744f1023def1553

operator test-e2e-operator (0.2.145-2)

---

operators/test-e2e-community-operator/0.2.145-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.145-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.145-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.145-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.145-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.145-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.145-2)

operator test-e2e-community-operator (0.2.145-2)

---

operators/test-e2e-operator-fbc/0.2.147-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.147-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.147-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.147-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.147-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.147-1/metadata/annotations.yaml

Version: **0.2.147-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/675beef1f8e6179295ae89e8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/675beeeef8e6179295ae89e5

operator test-e2e-operator-fbc (0.2.147-1)

---

operators/test-e2e-community-operator/0.2.147-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.147-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.147-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.147-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.147-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.147-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.147-1)

operator test-e2e-community-operator (0.2.147-1)

---

operators/test-e2e-operator/0.2.149-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.149-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.149-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.149-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.149-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.149-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.149-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/675bfda2f744f1023def1923
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/675bfda0f8e6179295ae8a48

operator test-e2e-operator (0.2.149-1)

---

operators/test-e2e-community-operator/0.2.149-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.149-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.149-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.149-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.149-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.149-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.149-1)

operator test-e2e-community-operator (0.2.149-1)

---

operators/test-e2e-operator-fbc/0.2.151-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.151-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.151-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.151-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.151-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.151-1/metadata/annotations.yaml

Version: **0.2.151-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/675fe411f744f1023def2aa9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/675fe40ef8e6179295ae9c21

operator test-e2e-operator-fbc (0.2.151-1)

---

operators/test-e2e-operator/0.2.151-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.151-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.151-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.151-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.151-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.151-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.151-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/675fe405f8e6179295ae9c0d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/675fe402f744f1023def2a94

operator test-e2e-operator (0.2.151-1)

---

operators/test-e2e-community-operator/0.2.151-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.151-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.151-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.151-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.151-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.151-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.151-1)

operator test-e2e-community-operator (0.2.151-1)

---

operators/test-e2e-operator-fbc/0.2.152-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.152-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.152-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.152-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.152-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.152-1/metadata/annotations.yaml

Version: **0.2.152-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/676003a4f8e6179295ae9d0b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/676003a2f744f1023def2b9d

operator test-e2e-operator-fbc (0.2.152-1)

---

operators/test-e2e-operator/0.2.152-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.152-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.152-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.152-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.152-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.152-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.152-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67600382f8e6179295ae9cee
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67600380f744f1023def2b7f

operator test-e2e-operator (0.2.152-1)

---

operators/test-e2e-community-operator/0.2.152-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.152-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.152-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.152-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.152-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.152-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.152-1)

operator test-e2e-community-operator (0.2.152-1)

---

operators/test-e2e-operator-fbc/0.2.153-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.153-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.153-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.153-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.153-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.153-1/metadata/annotations.yaml

Version: **0.2.153-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/676022e0f744f1023def2c6f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/676022def744f1023def2c6c

operator test-e2e-operator-fbc (0.2.153-1)

---

operators/test-e2e-operator/0.2.153-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.153-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.153-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.153-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.153-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.153-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.153-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6760332bf8e6179295ae9e3b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67603329f744f1023def2cce

operator test-e2e-operator (0.2.153-2)

---

operators/test-e2e-operator-fbc/0.2.158-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.158-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.158-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.158-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.158-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.158-1/metadata/annotations.yaml

Version: **0.2.158-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67653113b622c1793b34004a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67653111b622c1793b340045

operator test-e2e-operator-fbc (0.2.158-1)

---

operators/test-e2e-operator/0.2.158-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.158-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.158-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.158-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.158-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.158-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.158-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6765311d171c79c6e39cc55b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6765311b171c79c6e39cc558

operator test-e2e-operator (0.2.158-1)

---

operators/test-e2e-operator-fbc/0.2.162-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.162-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.162-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.162-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.162-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.162-1/metadata/annotations.yaml

Version: **0.2.162-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67657734171c79c6e39cc87f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67657732171c79c6e39cc87c

operator test-e2e-operator-fbc (0.2.162-1)

---

operators/test-e2e-operator/0.2.162-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.162-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.162-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.162-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.162-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.162-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.162-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/676576e3b622c1793b34039a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/676576e1b622c1793b340397

operator test-e2e-operator (0.2.162-1)

---

operators/test-e2e-community-operator/0.2.162-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.162-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.162-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.162-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.162-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.162-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.162-1)

operator test-e2e-community-operator (0.2.162-1)

---

operators/test-e2e-operator-fbc/0.2.164-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.164-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.164-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.164-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.164-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.164-1/metadata/annotations.yaml

Version: **0.2.164-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67658a2d171c79c6e39cc8b0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67658a2b171c79c6e39cc8a9

operator test-e2e-operator-fbc (0.2.164-1)

---

operators/test-e2e-operator/0.2.164-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.164-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.164-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.164-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.164-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.164-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.164-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67658a4ab622c1793b340402
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67658a48171c79c6e39cc8c7

operator test-e2e-operator (0.2.164-1)

---

operators/test-e2e-community-operator/0.2.164-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.164-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.164-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.164-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.164-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.164-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.164-1)

operator test-e2e-community-operator (0.2.164-1)

---

operators/test-e2e-operator-fbc/0.2.166-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.166-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.166-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.166-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.166-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.166-2/metadata/annotations.yaml

Version: **0.2.166-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67659acd171c79c6e39cc932
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67659acb171c79c6e39cc92f

operator test-e2e-operator-fbc (0.2.166-2)

---

operators/test-e2e-operator/0.2.166-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.166-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.166-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.166-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.166-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.166-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.166-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67659ac0171c79c6e39cc916
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67659abe171c79c6e39cc911

operator test-e2e-operator (0.2.166-2)

---

operators/test-e2e-community-operator/0.2.166-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.166-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.166-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.166-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.166-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.166-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.166-2)

operator test-e2e-community-operator (0.2.166-2)

---

operators/test-e2e-operator-fbc/0.2.172-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.172-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.172-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.172-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.172-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.172-1/metadata/annotations.yaml

Version: **0.2.172-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67767da0171c79c6e39d16c9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67767d9db622c1793b34507d

operator test-e2e-operator-fbc (0.2.172-1)

---

operators/test-e2e-operator/0.2.172-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.172-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.172-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.172-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.172-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.172-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.172-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67767daa171c79c6e39d16e5
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67767da8171c79c6e39d16e0

operator test-e2e-operator (0.2.172-1)

---

operators/test-e2e-community-operator/0.2.172-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.172-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.172-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.172-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.172-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.172-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.172-1)

operator test-e2e-community-operator (0.2.172-1)

---

operators/test-e2e-operator-fbc/0.2.173-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.173-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.173-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.173-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.173-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.173-1/metadata/annotations.yaml

Version: **0.2.173-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6776a5fcb622c1793b345232
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6776a5fab622c1793b34522f

operator test-e2e-operator-fbc (0.2.173-1)

---

operators/test-e2e-operator/0.2.173-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.173-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.173-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.173-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.173-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.173-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.173-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6776a606171c79c6e39d188a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6776a603171c79c6e39d1886

operator test-e2e-operator (0.2.173-1)

---

operators/test-e2e-community-operator/0.2.173-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.173-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.173-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.173-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.173-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.173-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.173-1)

operator test-e2e-community-operator (0.2.173-1)

---

operators/test-e2e-operator/0.2.177-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.177-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.177-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.177-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.177-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.177-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.177-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/677bfdc0171c79c6e39d34c5
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/677bfdbe171c79c6e39d34c2

operator test-e2e-operator (0.2.177-1)

---

operators/test-e2e-community-operator/0.2.177-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.177-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.177-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.177-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.177-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.177-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.177-1)

operator test-e2e-community-operator (0.2.177-1)

---

operators/test-e2e-operator-fbc/0.2.177-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.177-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.177-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.177-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.177-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.177-2/metadata/annotations.yaml

Version: **0.2.177-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/677cdc47d9771d0413ed44fe
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/677cdc45d9771d0413ed44f9

operator test-e2e-operator-fbc (0.2.177-2)

---

operators/test-e2e-operator-fbc/0.2.181-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.181-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.181-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.181-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.181-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.181-1/metadata/annotations.yaml

Version: **0.2.181-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/677e9a38e507bb44f3f0ed5a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/677e9a36e507bb44f3f0ed4b

operator test-e2e-operator-fbc (0.2.181-1)

---

operators/test-e2e-operator-fbc/0.2.182-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.182-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.182-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.182-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.182-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.182-1/metadata/annotations.yaml

Version: **0.2.182-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/677e9a3ae507bb44f3f0ed65
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/677e9a38e507bb44f3f0ed57

operator test-e2e-operator-fbc (0.2.182-1)

---

operators/test-e2e-operator/0.2.182-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.182-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.182-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.182-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.182-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.182-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.182-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/677e9a37e507bb44f3f0ed52
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/677e9a34bef1cd02670ef569

operator test-e2e-operator (0.2.182-1)

---

operators/test-e2e-community-operator/0.2.181-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.181-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.181-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.181-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.181-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.181-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.181-1)

operator test-e2e-community-operator (0.2.181-1)

---

operators/test-e2e-operator-fbc/0.2.189-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.189-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.189-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.189-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.189-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.189-1/metadata/annotations.yaml

Version: **0.2.189-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67853d877d234e52dd648989
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67853d852f11b2e23c7627b3

operator test-e2e-operator-fbc (0.2.189-1)

---

operators/test-e2e-operator/0.2.189-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.189-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.189-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.189-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.189-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.189-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.189-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67853d757d234e52dd648970
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67853d737d234e52dd648969

operator test-e2e-operator (0.2.189-1)

---

operators/test-e2e-community-operator/0.2.189-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.189-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.189-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.189-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.189-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.189-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.189-1)

operator test-e2e-community-operator (0.2.189-1)

---

operators/test-e2e-operator-fbc/0.2.190-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.190-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.190-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.190-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.190-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.190-1/metadata/annotations.yaml

Version: **0.2.190-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/678623992f11b2e23c7687a8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/678623982f11b2e23c7687a1

operator test-e2e-operator-fbc (0.2.190-1)

---

operators/test-e2e-operator-fbc/0.2.193-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.193-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.193-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.193-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.193-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.193-1/metadata/annotations.yaml

Version: **0.2.193-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67868eea7d234e52dd65169e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67868ee82f11b2e23c76b460

operator test-e2e-operator-fbc (0.2.193-1)

---

operators/test-e2e-community-operator/0.2.193-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.193-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.193-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.193-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.193-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.193-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.193-1)

operator test-e2e-community-operator (0.2.193-1)

---

operators/test-e2e-operator-fbc/0.2.194-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.194-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.194-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.194-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.194-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.194-1/metadata/annotations.yaml

Version: **0.2.194-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67869ba37d234e52dd651be8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67869ba17d234e52dd651be5

operator test-e2e-operator-fbc (0.2.194-1)

---

operators/test-e2e-operator/0.2.194-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.194-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.194-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.194-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.194-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.194-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.194-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67869bbc7d234e52dd651c02
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67869bba2f11b2e23c76b9f2

operator test-e2e-operator (0.2.194-1)

---

operators/test-e2e-community-operator/0.2.194-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.194-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.194-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.194-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.194-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.194-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.194-1)

operator test-e2e-community-operator (0.2.194-1)

---

operators/test-e2e-community-operator/0.2.194-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.194-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.194-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.194-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.194-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.194-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.194-2)

operator test-e2e-community-operator (0.2.194-2)

---

operators/test-e2e-operator-fbc/0.2.197-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.197-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.197-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.197-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.197-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.197-1/metadata/annotations.yaml

Version: **0.2.197-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6787d38f7d234e52dd659f83
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6787d38d7d234e52dd659f7e

operator test-e2e-operator-fbc (0.2.197-1)

---

operators/test-e2e-operator/0.2.197-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.197-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.197-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.197-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.197-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.197-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.197-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6787d3812f11b2e23c773d7d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6787d37f7d234e52dd659f69

operator test-e2e-operator (0.2.197-1)

---

operators/test-e2e-community-operator/0.2.197-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.197-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.197-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.197-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.197-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.197-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.197-1)

operator test-e2e-community-operator (0.2.197-1)

---

operators/test-e2e-operator-fbc/0.2.198-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.198-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.198-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.198-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.198-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.198-1/metadata/annotations.yaml

Version: **0.2.198-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6789403af6ab24bb52df51df
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67894038f6ab24bb52df51dc

operator test-e2e-operator-fbc (0.2.198-1)

---

operators/test-e2e-operator/0.2.198-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.198-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.198-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.198-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.198-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.198-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.198-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6789403debaaa6abf7dbef10
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6789403bf6ab24bb52df51e2

operator test-e2e-operator (0.2.198-1)

---

operators/test-e2e-community-operator/0.2.198-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.198-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.198-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.198-3/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.198-3/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.198-3/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.198-3)

operator test-e2e-community-operator (0.2.198-3)

---

operators/test-e2e-operator-fbc/0.2.201-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.201-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.201-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.201-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.201-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.201-1/metadata/annotations.yaml

Version: **0.2.201-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6790f043cad6ad26604e1b4f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6790f041cad6ad26604e1b4a

operator test-e2e-operator-fbc (0.2.201-1)

---

operators/test-e2e-operator/0.2.201-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.201-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.201-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.201-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.201-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.201-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.201-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6790eff1cad6ad26604e1b10
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6790eff00716edcc2360e45c

operator test-e2e-operator (0.2.201-1)

---

operators/test-e2e-community-operator/0.2.201-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.201-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.201-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.201-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.201-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.201-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.201-1)

operator test-e2e-community-operator (0.2.201-1)

---

operators/test-e2e-operator-fbc/0.2.214-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.214-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.214-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.214-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.214-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.214-1/metadata/annotations.yaml

Version: **0.2.214-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a37733aa8086f32d0fc6f1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a3773037d8bf02a8196102

operator test-e2e-operator-fbc (0.2.214-1)

---

operators/test-e2e-operator/0.2.214-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.214-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.214-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.214-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.214-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.214-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.214-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a3772737d8bf02a81960f6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a3772237d8bf02a81960f1

operator test-e2e-operator (0.2.214-1)

---

operators/test-e2e-operator/0.2.214-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.214-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.214-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.214-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.214-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.214-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.214-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a392fe37d8bf02a8196c9d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a392fbaa8086f32d0fd295

operator test-e2e-operator (0.2.214-2)

---

operators/test-e2e-operator-fbc/0.2.214-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.214-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.214-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.214-4/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.214-4/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.214-4/metadata/annotations.yaml

Version: **0.2.214-4**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a46bd637d8bf02a819c5d6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a46bd437d8bf02a819c5d1

operator test-e2e-operator-fbc (0.2.214-4)

---

operators/test-e2e-operator/0.2.214-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.214-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.214-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.214-4/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.214-4/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.214-4/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.214-4**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a46bdc37d8bf02a819c5f2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a46bda37d8bf02a819c5e4

operator test-e2e-operator (0.2.214-4)

---

operators/test-e2e-operator/0.2.217-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.217-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.217-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.217-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.217-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.217-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.217-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a47dd137d8bf02a819cd68
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a47dcf37d8bf02a819cd63

operator test-e2e-operator (0.2.217-1)

---

operators/test-e2e-operator-fbc/0.2.217-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.217-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.217-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.217-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.217-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.217-2/metadata/annotations.yaml

Version: **0.2.217-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a4942c37d8bf02a819d71c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a4942a37d8bf02a819d715

operator test-e2e-operator-fbc (0.2.217-2)

---

operators/test-e2e-operator/0.2.217-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.217-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.217-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.217-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.217-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.217-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.217-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a4943837d8bf02a819d73a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a4943637d8bf02a819d737

operator test-e2e-operator (0.2.217-2)

---

operators/test-e2e-community-operator/0.2.217-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.217-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.217-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.217-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.217-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.217-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.217-2)

operator test-e2e-community-operator (0.2.217-2)

---

operators/test-e2e-operator-fbc/0.2.219-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.219-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.219-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.219-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.219-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.219-1/metadata/annotations.yaml

Version: **0.2.219-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a4f116aa8086f32d1063fb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a4f11437d8bf02a819fe42

operator test-e2e-operator-fbc (0.2.219-1)

---

operators/test-e2e-operator/0.2.219-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.219-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.219-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.219-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.219-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.219-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.219-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a4f0df37d8bf02a819fe13
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a4f0dd37d8bf02a819fe0e

operator test-e2e-operator (0.2.219-1)

---

operators/test-e2e-community-operator/0.2.219-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.219-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.219-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.219-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.219-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.219-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.219-2)

operator test-e2e-community-operator (0.2.219-2)

---

operators/test-e2e-operator-fbc/0.2.220-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.220-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.220-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.220-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.220-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.220-1/metadata/annotations.yaml

Version: **0.2.220-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a5100baa8086f32d1070f0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a5100aaa8086f32d1070ed

operator test-e2e-operator-fbc (0.2.220-1)

---

operators/test-e2e-operator/0.2.220-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.220-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.220-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.220-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.220-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.220-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.220-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a51003aa8086f32d1070d0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a51000aa8086f32d1070cd

operator test-e2e-operator (0.2.220-1)

---

operators/test-e2e-community-operator/0.2.220-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.220-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.220-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.220-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.220-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.220-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.220-1)

operator test-e2e-community-operator (0.2.220-1)

---

operators/test-e2e-operator-fbc/0.2.222-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.222-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.222-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.222-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.222-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.222-1/metadata/annotations.yaml

Version: **0.2.222-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a5d61decae3468dcf0a521
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a5d61b4967c6a7d79de266

operator test-e2e-operator-fbc (0.2.222-1)

---

operators/test-e2e-operator/0.2.222-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.222-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.222-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.222-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.222-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.222-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.222-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a5d6244967c6a7d79de284
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a5d6224967c6a7d79de27b

operator test-e2e-operator (0.2.222-1)

---

operators/test-e2e-community-operator/0.2.222-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.222-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.222-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.222-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.222-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.222-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.222-1)

operator test-e2e-community-operator (0.2.222-1)

---

operators/test-e2e-operator-fbc/0.2.224-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.224-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.224-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.224-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.224-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.224-1/metadata/annotations.yaml

Version: **0.2.224-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a623f94967c6a7d79e035c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a623f74967c6a7d79e0358

operator test-e2e-operator-fbc (0.2.224-1)

---

operators/test-e2e-operator/0.2.224-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.224-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.224-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.224-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.224-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.224-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.224-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a623f24967c6a7d79e0346
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a623ef4967c6a7d79e033f

operator test-e2e-operator (0.2.224-1)

---

operators/test-e2e-community-operator/0.2.224-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.224-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.224-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.224-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.224-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.224-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.224-1)

operator test-e2e-community-operator (0.2.224-1)

---

operators/test-e2e-operator-fbc/0.2.226-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.226-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.226-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.226-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.226-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.226-1/metadata/annotations.yaml

Version: **0.2.226-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a62aadecae3468dcf0c8f8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a62aabecae3468dcf0c8f1

operator test-e2e-operator-fbc (0.2.226-1)

---

operators/test-e2e-operator/0.2.226-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.226-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.226-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.226-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.226-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.226-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.226-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a62aec4967c6a7d79e065d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a62ae94967c6a7d79e065a

operator test-e2e-operator (0.2.226-1)

---

operators/test-e2e-community-operator/0.2.226-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.226-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.226-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.226-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.226-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.226-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.226-1)

operator test-e2e-community-operator (0.2.226-1)

---

operators/test-e2e-operator-fbc/0.2.227-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.227-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.227-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.227-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.227-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.227-1/metadata/annotations.yaml

Version: **0.2.227-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a6481decae3468dcf0d51e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a6481a4967c6a7d79e125b

operator test-e2e-operator-fbc (0.2.227-1)

---

operators/test-e2e-operator/0.2.227-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.227-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.227-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.227-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.227-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.227-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.227-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a64831ecae3468dcf0d53b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a6482f4967c6a7d79e1273

operator test-e2e-operator (0.2.227-1)

---

operators/test-e2e-community-operator/0.2.227-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.227-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.227-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.227-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.227-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.227-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.227-1)

operator test-e2e-community-operator (0.2.227-1)

---

operators/test-e2e-operator-fbc/0.2.228-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.228-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.228-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.228-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.228-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.228-1/metadata/annotations.yaml

Version: **0.2.228-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a9ab08ecae3468dcf23c67
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a9ab044967c6a7d79f7941

operator test-e2e-operator-fbc (0.2.228-1)

---

operators/test-e2e-operator/0.2.228-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.228-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.228-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.228-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.228-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.228-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.228-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a9ab20ecae3468dcf23c7d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a9ab1e4967c6a7d79f7964

operator test-e2e-operator (0.2.228-1)

---

operators/test-e2e-community-operator/0.2.228-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.228-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.228-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.228-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.228-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.228-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.228-1)

operator test-e2e-community-operator (0.2.228-1)

---

operators/test-e2e-operator-fbc/0.2.238-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.238-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.238-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.238-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.238-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.238-1/metadata/annotations.yaml

Version: **0.2.238-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a9eeef4967c6a7d79f96f8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a9eeed4967c6a7d79f96f1

operator test-e2e-operator-fbc (0.2.238-1)

---

operators/test-e2e-operator/0.2.238-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.238-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.238-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.238-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.238-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.238-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.238-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67a9ef084967c6a7d79f971b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67a9ef064967c6a7d79f9716

operator test-e2e-operator (0.2.238-1)

---

operators/test-e2e-community-operator/0.2.238-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.238-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.238-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.238-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.238-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.238-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.238-1)

operator test-e2e-community-operator (0.2.238-1)

---

operators/test-e2e-operator-fbc/0.2.245-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.245-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.245-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.245-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.245-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.245-1/metadata/annotations.yaml

Version: **0.2.245-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67ab145e52fcf4faabe1e2ae
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67ab145cf40f26f19939f607

operator test-e2e-operator-fbc (0.2.245-1)

---

operators/test-e2e-operator/0.2.245-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.245-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.245-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.245-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.245-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.245-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.245-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67ab1485f40f26f19939f631
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67ab1483f40f26f19939f62c

operator test-e2e-operator (0.2.245-1)

---

operators/test-e2e-community-operator/0.2.245-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.245-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.245-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.245-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.245-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.245-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.245-1)

operator test-e2e-community-operator (0.2.245-1)

---

operators/test-e2e-operator-fbc/0.2.249-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.249-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.249-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.249-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.249-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.249-1/metadata/annotations.yaml

Version: **0.2.249-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67ac5a8b52fcf4faabe26cb3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67ac5a8852fcf4faabe26cae

operator test-e2e-operator-fbc (0.2.249-1)

---

operators/test-e2e-operator-fbc/0.2.248-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.248-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.248-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.248-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.248-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.248-1/metadata/annotations.yaml

Version: **0.2.248-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67ac5a8ef40f26f1993a7f6a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67ac5a8c52fcf4faabe26cba

operator test-e2e-operator-fbc (0.2.248-1)

---

operators/test-e2e-operator/0.2.249-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.249-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.249-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.249-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.249-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.249-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.249-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67ac5a9952fcf4faabe26cef
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67ac5a97f40f26f1993a7f8e

operator test-e2e-operator (0.2.249-1)

---

operators/test-e2e-community-operator/0.2.248-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.248-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.248-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.248-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.248-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.248-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.248-1)

operator test-e2e-community-operator (0.2.248-1)

---

operators/test-e2e-community-operator/0.2.249-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.249-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.249-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.249-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.249-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.249-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.249-1)

operator test-e2e-community-operator (0.2.249-1)

---

operators/test-e2e-operator-fbc/0.2.252-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.252-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.252-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.252-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.252-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.252-1/metadata/annotations.yaml

Version: **0.2.252-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67ac86a852fcf4faabe28072
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67ac86a6f40f26f1993a930b

operator test-e2e-operator-fbc (0.2.252-1)

---

operators/test-e2e-operator/0.2.252-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.252-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.252-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.252-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.252-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.252-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.252-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67ac865bf40f26f1993a92d5
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67ac865a52fcf4faabe28040

operator test-e2e-operator (0.2.252-1)

---

operators/test-e2e-operator-fbc/0.2.253-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.253-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.253-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.253-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.253-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.253-1/metadata/annotations.yaml

Version: **0.2.253-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67ac9630f40f26f1993a9997
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67ac962ef40f26f1993a9990

operator test-e2e-operator-fbc (0.2.253-1)

---

operators/test-e2e-community-operator/0.2.253-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.253-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.253-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.253-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.253-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.253-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.253-1)

operator test-e2e-community-operator (0.2.253-1)

---

operators/test-e2e-operator-fbc/0.2.256-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.256-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.256-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.256-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.256-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.256-1/metadata/annotations.yaml

Version: **0.2.256-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67adfe5433dc933baa9a6727
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67adfe524d4c62b9d11e1bb3

operator test-e2e-operator-fbc (0.2.256-1)

---

operators/test-e2e-operator/0.2.256-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.256-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.256-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.256-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.256-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.256-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.256-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67adfe404d4c62b9d11e1b89
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67adfe3e4d4c62b9d11e1b82

operator test-e2e-operator (0.2.256-1)

---

operators/test-e2e-operator/0.2.257-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.257-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.257-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.257-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.257-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.257-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.257-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67adfe4533dc933baa9a6704
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67adfe4333dc933baa9a6701

operator test-e2e-operator (0.2.257-1)

---

operators/test-e2e-community-operator/0.2.256-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.256-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.256-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.256-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.256-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.256-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.256-1)

operator test-e2e-community-operator (0.2.256-1)

---

operators/test-e2e-operator-fbc/0.2.261-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.261-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.261-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.261-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.261-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.261-1/metadata/annotations.yaml

Version: **0.2.261-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67aef9fd4d4c62b9d11e87c3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67aef9fc33dc933baa9ad30f

operator test-e2e-operator-fbc (0.2.261-1)

---

operators/test-e2e-operator/0.2.261-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.261-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.261-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.261-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.261-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.261-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.261-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67aefa1d4d4c62b9d11e87ed
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67aefa1b33dc933baa9ad330

operator test-e2e-operator (0.2.261-1)

---

operators/test-e2e-community-operator/0.2.261-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.261-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.261-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.261-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.261-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.261-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.261-1)

operator test-e2e-community-operator (0.2.261-1)

---

operators/test-e2e-operator/0.1.1-49/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.1-49/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.1-49/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.1-49/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.1-49/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.1-49/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.1-49**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67af1a854d4c62b9d11e970a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67af1a834d4c62b9d11e9707

operator test-e2e-operator (0.1.1-49)

---

operators/test-e2e-operator/0.2.265-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.265-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.265-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.265-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.265-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.265-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.265-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67af1eec33dc933baa9ae4e8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67af1eea33dc933baa9ae4e0

operator test-e2e-operator (0.2.265-1)

---

operators/test-e2e-community-operator/0.2.265-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.265-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.265-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.265-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.265-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.265-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.265-1)

operator test-e2e-community-operator (0.2.265-1)

---

operators/test-e2e-operator/0.2.267-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.267-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.267-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.267-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.267-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.267-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.267-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67af377a4d4c62b9d11ea462
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67af37774d4c62b9d11ea45b

operator test-e2e-operator (0.2.267-1)

---

operators/test-e2e-operator/0.1.1-51/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.1-51/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.1-51/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.1-51/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.1-51/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.1-51/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.1-51**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67af40ce33dc933baa9af3e5
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67af40cc4d4c62b9d11ea875

operator test-e2e-operator (0.1.1-51)

---

operators/test-e2e-operator/0.1.1-53/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.1.1-53/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.1.1-53/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.1.1-53/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.1.1-53/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.1.1-53/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.1.1-53**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b317ff33dc933baa9c8ef4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b317fd33dc933baa9c8eef

operator test-e2e-operator (0.1.1-53)

---

operators/test-e2e-operator-fbc/0.2.269-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.269-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.269-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.269-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.269-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.269-1/metadata/annotations.yaml

Version: **0.2.269-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b3210c4d4c62b9d1204713
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b3210933dc933baa9c9336

operator test-e2e-operator-fbc (0.2.269-1)

---

operators/test-e2e-operator/0.2.269-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.269-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.269-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.269-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.269-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.269-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.269-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b3211433dc933baa9c9351
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b321124d4c62b9d1204727

operator test-e2e-operator (0.2.269-1)

---

operators/test-e2e-community-operator/0.2.269-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.269-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.269-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.269-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.269-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.269-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.269-1)

operator test-e2e-community-operator (0.2.269-1)

---

operators/test-e2e-operator-fbc/0.2.271-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.271-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.271-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.271-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.271-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.271-1/metadata/annotations.yaml

Version: **0.2.271-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b32c3a4d4c62b9d1204c22
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b32c374d4c62b9d1204c1d

operator test-e2e-operator-fbc (0.2.271-1)

---

operators/test-e2e-operator/0.2.271-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.271-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.271-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.271-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.271-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.271-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.271-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b32bfa4d4c62b9d1204bef
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b32bf94d4c62b9d1204bea

operator test-e2e-operator (0.2.271-1)

---

operators/test-e2e-community-operator/0.2.271-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.271-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.271-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.271-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.271-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.271-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.271-1)

operator test-e2e-community-operator (0.2.271-1)

---

operators/test-e2e-operator-fbc/0.2.272-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.272-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.272-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.272-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.272-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.272-1/metadata/annotations.yaml

Version: **0.2.272-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b3589e4d4c62b9d1205e81
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b3589c4d4c62b9d1205e7e

operator test-e2e-operator-fbc (0.2.272-1)

---

operators/test-e2e-operator/0.2.272-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.272-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.272-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.272-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.272-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.272-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.272-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b358ce33dc933baa9caada
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b358cc33dc933baa9caad5

operator test-e2e-operator (0.2.272-1)

---

operators/test-e2e-community-operator/0.2.272-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.272-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.272-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.272-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.272-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.272-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.272-1)

operator test-e2e-community-operator (0.2.272-1)

---

operators/test-e2e-operator/0.2.274-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.274-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.274-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.274-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.274-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.274-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.274-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b36be04d4c62b9d12066a7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b36bdd33dc933baa9cb2cb

operator test-e2e-operator (0.2.274-1)

---

operators/test-e2e-community-operator/0.2.274-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.274-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.274-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.274-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.274-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.274-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.274-1)

operator test-e2e-community-operator (0.2.274-1)

---

operators/test-e2e-operator-fbc/0.2.276-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.276-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.276-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.276-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.276-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.276-1/metadata/annotations.yaml

Version: **0.2.276-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b44bc16669ebd80af53294
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b44bbf6669ebd80af5328f

operator test-e2e-operator-fbc (0.2.276-1)

---

operators/test-e2e-operator/0.2.276-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.276-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.276-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.276-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.276-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.276-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.276-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b44c066669ebd80af532c7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b44c04ad1f74368f2f0ac9

operator test-e2e-operator (0.2.276-1)

---

operators/test-e2e-community-operator/0.2.276-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.276-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.276-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.276-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.276-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.276-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.276-1)

operator test-e2e-community-operator (0.2.276-1)

---

operators/test-e2e-operator-fbc/0.2.278-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.278-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.278-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.278-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.278-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.278-1/metadata/annotations.yaml

Version: **0.2.278-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b58f906669ebd80af5bc21
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b58f8dad1f74368f2f93f1

operator test-e2e-operator-fbc (0.2.278-1)

---

operators/test-e2e-operator/0.2.278-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.278-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.278-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.278-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.278-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.278-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.278-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b58f906669ebd80af5bc20
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b58f8d6669ebd80af5bc13

operator test-e2e-operator (0.2.278-1)

---

operators/test-e2e-community-operator/0.2.278-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.278-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.278-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.278-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.278-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.278-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.278-1)

operator test-e2e-community-operator (0.2.278-1)

---

operators/test-e2e-operator-fbc/0.2.279-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.279-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.279-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.279-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.279-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.279-1/metadata/annotations.yaml

Version: **0.2.279-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b5a3cc6669ebd80af5c68d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b5a3caad1f74368f2f9ee0

operator test-e2e-operator-fbc (0.2.279-1)

---

operators/test-e2e-operator/0.2.279-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.279-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.279-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.279-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.279-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.279-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.279-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b5a3ba6669ebd80af5c672
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b5a3b86669ebd80af5c66f

operator test-e2e-operator (0.2.279-1)

---

operators/test-e2e-community-operator/0.2.279-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.279-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.279-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.279-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.279-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.279-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.279-1)

operator test-e2e-community-operator (0.2.279-1)

---

operators/test-e2e-operator-fbc/0.2.286-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.286-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.286-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.286-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.286-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.286-1/metadata/annotations.yaml

Version: **0.2.286-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b73213ad1f74368f304ce0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b732106669ebd80af674e7

operator test-e2e-operator-fbc (0.2.286-1)

---

operators/test-e2e-operator/0.2.286-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.286-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.286-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.286-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.286-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.286-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.286-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67b732066669ebd80af674ce
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67b73203ad1f74368f304cc8

operator test-e2e-operator (0.2.286-1)

---

operators/test-e2e-community-operator/0.2.286-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.286-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.286-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.286-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.286-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.286-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.286-2)

operator test-e2e-community-operator (0.2.286-2)

---

operators/test-e2e-operator-fbc/0.2.289-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.289-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.289-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.289-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.289-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.289-1/metadata/annotations.yaml

Version: **0.2.289-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67bcae5ddcfbf55ead982667
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67bcae5b98bd918cd2f46060

operator test-e2e-operator-fbc (0.2.289-1)

---

operators/test-e2e-community-operator/0.2.289-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.289-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.289-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.289-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.289-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.289-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.289-1)

operator test-e2e-community-operator (0.2.289-1)

---

operators/test-e2e-operator-fbc/0.2.291-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.291-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.291-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.291-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.291-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.291-1/metadata/annotations.yaml

Version: **0.2.291-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67bdadc798bd918cd2f4cd68
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67bdadc5dcfbf55ead9893a7

operator test-e2e-operator-fbc (0.2.291-1)

---

operators/test-e2e-operator/0.2.291-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.291-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.291-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.291-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.291-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.291-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.291-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67bdadc898bd918cd2f4cd6d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67bdadc6dcfbf55ead9893ac

operator test-e2e-operator (0.2.291-1)

---

operators/test-e2e-operator-fbc/0.2.293-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.293-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.293-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.293-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.293-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.293-1/metadata/annotations.yaml

Version: **0.2.293-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67bdb45edcfbf55ead9896a1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67bdb45c98bd918cd2f4d059

operator test-e2e-operator-fbc (0.2.293-1)

---

operators/test-e2e-operator/0.2.293-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.293-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.293-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.293-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.293-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.293-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.293-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67bdb466dcfbf55ead9896be
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67bdb464dcfbf55ead9896b9

operator test-e2e-operator (0.2.293-1)

---

operators/test-e2e-community-operator/0.2.291-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.291-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.291-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.291-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.291-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.291-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.291-1)

operator test-e2e-community-operator (0.2.291-1)

---

operators/test-e2e-community-operator/0.2.293-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.293-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.293-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.293-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.293-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.293-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.293-1)

operator test-e2e-community-operator (0.2.293-1)

---

operators/test-e2e-operator-fbc/0.2.294-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.294-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.294-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.294-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.294-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.294-1/metadata/annotations.yaml

Version: **0.2.294-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67bee4ccdcfbf55ead99184a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67bee4ca98bd918cd2f551ef

operator test-e2e-operator-fbc (0.2.294-1)

---

operators/test-e2e-operator/0.2.294-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.294-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.294-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.294-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.294-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.294-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.294-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67bee4d198bd918cd2f55203
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67bee4cf98bd918cd2f551f8

operator test-e2e-operator (0.2.294-1)

---

operators/test-e2e-community-operator/0.2.294-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.294-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.294-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.294-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.294-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.294-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.294-1)

operator test-e2e-community-operator (0.2.294-1)

---

operators/test-e2e-operator-fbc/0.2.297-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.297-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.297-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.297-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.297-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.297-1/metadata/annotations.yaml

Version: **0.2.297-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67bf175a98bd918cd2f569d8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67bf175798bd918cd2f569d5

operator test-e2e-operator-fbc (0.2.297-1)

---

operators/test-e2e-operator/0.2.297-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.297-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.297-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.297-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.297-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.297-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.297-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67bf175fdcfbf55ead993055
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67bf175cdcfbf55ead993046

operator test-e2e-operator (0.2.297-1)

---

operators/test-e2e-community-operator/0.2.297-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.297-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.297-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.297-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.297-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.297-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.297-1)

operator test-e2e-community-operator (0.2.297-1)

---

operators/test-e2e-operator-fbc/0.2.301-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.301-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.301-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.301-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.301-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.301-1/metadata/annotations.yaml

Version: **0.2.301-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c07ca149a7a608ed192cef
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c07c9e49a7a608ed192ce8

operator test-e2e-operator-fbc (0.2.301-1)

---

operators/test-e2e-operator/0.2.301-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.301-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.301-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.301-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.301-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.301-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.301-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c07c8fcc6f0db0901df923
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c07c8c49a7a608ed192ccb

operator test-e2e-operator (0.2.301-1)

---

operators/test-e2e-community-operator/0.2.301-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.301-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.301-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.301-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.301-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.301-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.301-1)

operator test-e2e-community-operator (0.2.301-1)

---

operators/test-e2e-operator-fbc/0.2.302-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.302-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.302-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.302-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.302-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.302-1/metadata/annotations.yaml

Version: **0.2.302-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c0918949a7a608ed193594
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c09187cc6f0db0901e01da

operator test-e2e-operator-fbc (0.2.302-1)

---

operators/test-e2e-operator/0.2.302-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.302-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.302-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.302-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.302-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.302-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.302-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c091b9cc6f0db0901e0203
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c091b7cc6f0db0901e01fe

operator test-e2e-operator (0.2.302-1)

---

operators/test-e2e-community-operator/0.2.302-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.302-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.302-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.302-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.302-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.302-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.302-1)

operator test-e2e-community-operator (0.2.302-1)

---

operators/test-e2e-operator-fbc/0.2.304-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.304-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.304-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.304-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.304-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.304-1/metadata/annotations.yaml

Version: **0.2.304-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c6cef4b007d9729e894496
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c6cef2fba301d4371d5a38

operator test-e2e-operator-fbc (0.2.304-1)

---

operators/test-e2e-operator/0.2.304-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.304-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.304-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.304-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.304-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.304-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.304-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c6cef2b007d9729e89448f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c6ceeffba301d4371d5a33

operator test-e2e-operator (0.2.304-1)

---

operators/test-e2e-community-operator/0.2.304-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.304-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.304-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.304-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.304-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.304-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.304-1)

operator test-e2e-community-operator (0.2.304-1)

---

operators/test-e2e-operator-fbc/0.2.311-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.311-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.311-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.311-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.311-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.311-1/metadata/annotations.yaml

Version: **0.2.311-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c77a4dfba301d4371da19e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c77a4bfba301d4371da19b

operator test-e2e-operator-fbc (0.2.311-1)

---

operators/test-e2e-operator/0.2.311-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.311-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.311-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.311-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.311-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.311-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.311-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c77a57b007d9729e898c01
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c77a55b007d9729e898bfc

operator test-e2e-operator (0.2.311-1)

---

operators/test-e2e-operator-fbc/0.2.314-7/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.314-7/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.314-7/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.314-7/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.314-7/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.314-7/metadata/annotations.yaml

Version: **0.2.314-7**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c813a3b007d9729e89ceb1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c813a1b007d9729e89cea5

operator test-e2e-operator-fbc (0.2.314-7)

---

operators/test-e2e-operator-fbc/0.2.315-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.315-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.315-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.315-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.315-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.315-1/metadata/annotations.yaml

Version: **0.2.315-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c959cc82b13377412459d5
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c959ca82b13377412459d0

operator test-e2e-operator-fbc (0.2.315-1)

---

operators/test-e2e-operator/0.2.315-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.315-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.315-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.315-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.315-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.315-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.315-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c959b76a42120f2a89b620
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c959b482b13377412459af

operator test-e2e-operator (0.2.315-1)

---

operators/test-e2e-community-operator/0.2.315-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.315-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.315-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.315-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.315-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.315-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.315-1)

operator test-e2e-community-operator (0.2.315-1)

---

operators/test-e2e-operator-fbc/0.2.319-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.319-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.319-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.319-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.319-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.319-1/metadata/annotations.yaml

Version: **0.2.319-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c9a3c76a42120f2a89d62f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c9a3c56a42120f2a89d629

operator test-e2e-operator-fbc (0.2.319-1)

---

operators/test-e2e-operator/0.2.319-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.319-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.319-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.319-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.319-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.319-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.319-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c9a3c66a42120f2a89d62c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c9a3c482b1337741247992

operator test-e2e-operator (0.2.319-1)

---

operators/test-e2e-community-operator/0.2.319-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.319-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.319-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.319-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.319-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.319-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.319-1)

operator test-e2e-community-operator (0.2.319-1)

---

operators/test-e2e-operator/0.2.320-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.320-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.320-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.320-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.320-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.320-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.320-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67c9b50c6a42120f2a89dd7e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67c9b50a6a42120f2a89dd7b

operator test-e2e-operator (0.2.320-1)

---

operators/test-e2e-community-operator/0.2.320-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.320-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.320-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.320-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.320-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.320-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.320-1)

operator test-e2e-community-operator (0.2.320-1)

---

operators/test-e2e-operator-fbc/0.2.324-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.324-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.324-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.324-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.324-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.324-1/metadata/annotations.yaml

Version: **0.2.324-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67d170928b19aee5be251cf0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67d170918b19aee5be251ced

operator test-e2e-operator-fbc (0.2.324-1)

---

operators/test-e2e-community-operator/0.2.324-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.324-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.324-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.324-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.324-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.324-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.324-1)

operator test-e2e-community-operator (0.2.324-1)

---

operators/test-e2e-operator/0.2.326-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.326-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.326-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.326-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.326-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.326-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.326-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67d1aaf51a290006f9ca0117
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67d1aaf2a22b0fd23f4dea57

operator test-e2e-operator (0.2.326-1)

---

operators/test-e2e-community-operator/0.2.326-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.326-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.326-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.326-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.326-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.326-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.326-1)

operator test-e2e-community-operator (0.2.326-1)

---

operators/test-e2e-operator/0.2.327-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.327-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.327-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.327-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.327-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.327-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.327-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67d2ce1606cb1997807ce46e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67d2ce1306cb1997807ce469

operator test-e2e-operator (0.2.327-1)

---

operators/test-e2e-community-operator/0.2.327-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.327-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.327-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.327-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.327-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.327-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.327-1)

operator test-e2e-community-operator (0.2.327-1)

---

operators/test-e2e-operator-fbc/0.2.331-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.331-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.331-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.331-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.331-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.331-1/metadata/annotations.yaml

Version: **0.2.331-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67d2fffa06cb1997807cf968
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67d2fff806cb1997807cf963

operator test-e2e-operator-fbc (0.2.331-1)

---

operators/test-e2e-community-operator/0.2.331-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.331-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.331-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.331-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.331-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.331-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.331-2)

operator test-e2e-community-operator (0.2.331-2)

---

operators/test-e2e-operator-fbc/0.2.332-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.332-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.332-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.332-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.332-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.332-1/metadata/annotations.yaml

Version: **0.2.332-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67d95cef67fd544181b7cbdc
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67d95ced67fd544181b7cbd7

operator test-e2e-operator-fbc (0.2.332-1)

---

operators/test-e2e-operator/0.2.332-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.332-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.332-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.332-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.332-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.332-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.332-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67d96fec67fd544181b7d48c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67d96febfc213e0980cfa544

operator test-e2e-operator (0.2.332-2)

---

operators/test-e2e-community-operator/0.2.332-5/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.332-5/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.332-5/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.332-5/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.332-5/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.332-5/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.332-5)

operator test-e2e-community-operator (0.2.332-5)

---

operators/test-e2e-community-operator/0.2.332-6/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.332-6/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.332-6/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.332-6/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.332-6/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.332-6/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.332-6)

operator test-e2e-community-operator (0.2.332-6)

---

operators/test-e2e-community-operator/0.2.332-7/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.332-7/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.332-7/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.332-7/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.332-7/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.332-7/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.332-7)

operator test-e2e-community-operator (0.2.332-7)

---

operators/test-e2e-operator-fbc/0.2.335-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.335-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.335-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.335-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.335-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.335-1/metadata/annotations.yaml

Version: **0.2.335-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67dc15f49b1e55aaffa955c9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67dc15f19b1e55aaffa955c6

operator test-e2e-operator-fbc (0.2.335-1)

---

operators/test-e2e-community-operator/0.2.335-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.335-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.335-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.335-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.335-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.335-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.335-1)

operator test-e2e-community-operator (0.2.335-1)

---

operators/test-e2e-community-operator/0.2.337-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.337-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.337-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.337-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.337-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.337-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.337-1)

operator test-e2e-community-operator (0.2.337-1)

---

operators/test-e2e-operator-fbc/0.2.341-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.341-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.341-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.341-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.341-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.341-1/metadata/annotations.yaml

Version: **0.2.341-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67dc379b9b1e55aaffa964e4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67dc37987ffad7290be03b2a

operator test-e2e-operator-fbc (0.2.341-1)

---

operators/test-e2e-operator/0.2.341-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.341-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.341-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.341-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.341-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.341-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.341-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67dc37c17ffad7290be03b47
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67dc37bf9b1e55aaffa9650e

operator test-e2e-operator (0.2.341-1)

---

operators/test-e2e-operator-fbc/0.2.339-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.339-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.339-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.339-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.339-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.339-2/metadata/annotations.yaml

Version: **0.2.339-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67dc41e67ffad7290be03f80
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67dc41e47ffad7290be03f7b

operator test-e2e-operator-fbc (0.2.339-2)

---

operators/test-e2e-operator/0.2.339-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.339-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.339-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.339-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.339-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.339-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.339-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67dc41f89b1e55aaffa9696b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67dc41f67ffad7290be03f9e

operator test-e2e-operator (0.2.339-2)

---

operators/test-e2e-community-operator/0.2.339-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.339-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.339-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.339-3/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.339-3/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.339-3/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.339-3)

operator test-e2e-community-operator (0.2.339-3)

---

operators/test-e2e-operator/0.2.339-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.339-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.339-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.339-4/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.339-4/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.339-4/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.339-4**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67dd2da19b1e55aaffa9cccb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67dd2da07ffad7290be0a2ff

operator test-e2e-operator (0.2.339-4)

---

operators/test-e2e-operator-fbc/0.2.342-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.342-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.342-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.342-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.342-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.342-1/metadata/annotations.yaml

Version: **0.2.342-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67dd3a187ffad7290be0a869
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67dd3a177ffad7290be0a866

operator test-e2e-operator-fbc (0.2.342-1)

---

operators/test-e2e-community-operator/0.2.342-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.342-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.342-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.342-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.342-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.342-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.342-1)

operator test-e2e-community-operator (0.2.342-1)

---

operators/test-e2e-operator-fbc/0.2.343-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.343-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.343-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.343-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.343-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.343-2/metadata/annotations.yaml

Version: **0.2.343-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67dd4da57ffad7290be0b170
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67dd4da39b1e55aaffa9db36

operator test-e2e-operator-fbc (0.2.343-2)

---

operators/test-e2e-operator/0.2.343-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.343-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.343-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.343-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.343-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.343-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.343-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67dd4d967ffad7290be0b153
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67dd4d949b1e55aaffa9db20

operator test-e2e-operator (0.2.343-2)

---

operators/test-e2e-operator-fbc/0.2.349-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.349-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.349-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.349-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.349-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.349-1/metadata/annotations.yaml

Version: **0.2.349-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/67fe78168c57c57f17b33386
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/67fe78149262efedc34d05e0

operator test-e2e-operator-fbc (0.2.349-1)

---

operators/test-e2e-community-operator/0.2.349-5/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.349-5/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.349-5/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.349-5/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.349-5/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.349-5/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.349-5)

operator test-e2e-community-operator (0.2.349-5)

---

operators/test-e2e-operator-fbc/0.2.354-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.354-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.354-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.354-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.354-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.354-1/metadata/annotations.yaml

Version: **0.2.354-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6800be6161459382c9f9fe0a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6800be5f61459382c9f9fe07

operator test-e2e-operator-fbc (0.2.354-1)

---

operators/test-e2e-operator/0.2.354-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.354-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.354-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.354-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.354-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.354-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.354-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6800bea19e38a13f6c8b600a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6800be9f61459382c9f9fe3c

operator test-e2e-operator (0.2.354-1)

---

operators/test-e2e-community-operator/0.2.356-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.356-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.356-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.356-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.356-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.356-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.356-1)

operator test-e2e-community-operator (0.2.356-1)

---

operators/test-e2e-operator/0.2.356-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.356-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.356-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.356-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.356-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.356-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.356-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6800df0961459382c9fa0cec
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6800df0761459382c9fa0ce7

operator test-e2e-operator (0.2.356-2)

---

operators/test-e2e-community-operator/0.2.357-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.357-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.357-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.357-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.357-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.357-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.357-1)

operator test-e2e-community-operator (0.2.357-1)

---

operators/test-e2e-operator-fbc/0.2.358-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.358-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.358-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.358-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.358-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.358-1/metadata/annotations.yaml

Version: **0.2.358-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6800e98f61459382c9fa11ec
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6800e98e9e38a13f6c8b73f8

operator test-e2e-operator-fbc (0.2.358-1)

---

operators/test-e2e-operator/0.2.358-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.358-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.358-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.358-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.358-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.358-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.358-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6800e9979e38a13f6c8b7419
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6800e9959e38a13f6c8b7411

operator test-e2e-operator (0.2.358-1)

---

operators/test-e2e-community-operator/0.2.358-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.358-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.358-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.358-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.358-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.358-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.358-1)

operator test-e2e-community-operator (0.2.358-1)

---

operators/test-e2e-operator/0.2.358-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.358-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.358-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.358-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.358-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.358-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.358-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6800fc8361459382c9fa1a86
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6800fc819e38a13f6c8b7cad

operator test-e2e-operator (0.2.358-2)

---

operators/test-e2e-operator-fbc/0.2.358-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.358-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.358-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.358-3/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.358-3/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.358-3/metadata/annotations.yaml

Version: **0.2.358-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/680104b861459382c9fa1e31
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/680104b69e38a13f6c8b8055

operator test-e2e-operator-fbc (0.2.358-3)

---

operators/test-e2e-operator/0.2.363-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.363-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.363-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.363-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.363-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.363-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.363-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6808d4a57440ec80d4ab7e1f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6808d4a37440ec80d4ab7e18

operator test-e2e-operator (0.2.363-1)

---

operators/test-e2e-community-operator/0.2.363-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.363-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.363-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.363-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.363-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.363-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.363-1)

operator test-e2e-community-operator (0.2.363-1)

---

operators/test-e2e-operator-fbc/0.2.365-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.365-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.365-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.365-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.365-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.365-1/metadata/annotations.yaml

Version: **0.2.365-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6808feb77440ec80d4ab9096
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6808feb67440ec80d4ab9091

operator test-e2e-operator-fbc (0.2.365-1)

---

operators/test-e2e-operator/0.2.365-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.365-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.365-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.365-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.365-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.365-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.365-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6808fe5c7440ec80d4ab904d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6808fe5a8aa9d94f45c70ca4

operator test-e2e-operator (0.2.365-1)

---

operators/test-e2e-operator-fbc/0.2.367-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.367-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.367-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.367-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.367-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.367-1/metadata/annotations.yaml

Version: **0.2.367-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68093ec78aa9d94f45c72720
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68093ec58aa9d94f45c72719

operator test-e2e-operator-fbc (0.2.367-1)

---

operators/test-e2e-operator/0.2.367-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.367-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.367-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.367-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.367-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.367-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.367-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68093ec87440ec80d4abaacf
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68093ec67440ec80d4abaaca

operator test-e2e-operator (0.2.367-1)

---

operators/test-e2e-community-operator/0.2.367-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.367-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.367-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.367-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.367-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.367-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.367-1)

operator test-e2e-community-operator (0.2.367-1)

---

operators/test-e2e-operator/0.2.367-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.367-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.367-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.367-3/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.367-3/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.367-3/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.367-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/680f6cd56820d76ddf59a474
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/680f6cd423364c079d11cdfd

operator test-e2e-operator (0.2.367-3)

---

operators/test-e2e-operator-fbc/0.2.369-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.369-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.369-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.369-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.369-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.369-1/metadata/annotations.yaml

Version: **0.2.369-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68107b400c0afc0845151bdf
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68107b3ea0366ec95662e5c5

operator test-e2e-operator-fbc (0.2.369-1)

---

operators/test-e2e-community-operator/0.2.369-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.369-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.369-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.369-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.369-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.369-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.369-1)

operator test-e2e-community-operator (0.2.369-1)

---

operators/test-e2e-operator-fbc/0.2.373-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.373-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.373-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.373-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.373-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.373-1/metadata/annotations.yaml

Version: **0.2.373-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68221a0aaf35d255bd038e6d
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68221a0869ad34acd2ec8bb2

operator test-e2e-operator-fbc (0.2.373-1)

---

operators/test-e2e-community-operator/0.2.373-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.373-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.373-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.373-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.373-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.373-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.373-1)

operator test-e2e-community-operator (0.2.373-1)

---

operators/test-e2e-community-operator/0.2.379-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.379-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.379-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.379-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.379-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.379-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.379-1)

operator test-e2e-community-operator (0.2.379-1)

---

operators/test-e2e-community-operator/0.2.381-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.381-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.381-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.381-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.381-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.381-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.381-1)

operator test-e2e-community-operator (0.2.381-1)

---

operators/test-e2e-community-operator/0.2.382-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.382-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.382-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.382-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.382-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.382-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.382-1)

operator test-e2e-community-operator (0.2.382-1)

---

operators/test-e2e-operator-fbc/0.2.382-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.382-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.382-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.382-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.382-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.382-2/metadata/annotations.yaml

Version: **0.2.382-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6825fd5e2fb6b25e796e684a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6825fd5c2fb6b25e796e6845

operator test-e2e-operator-fbc (0.2.382-2)

---

operators/test-e2e-operator/0.2.382-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.382-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.382-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.382-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.382-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.382-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.382-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6825fd5f05a8f4a22ee5aaaa
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6825fd5c05a8f4a22ee5aaa5

operator test-e2e-operator (0.2.382-2)

---

operators/test-e2e-operator-fbc/0.2.384-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.384-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.384-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.384-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.384-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.384-1/metadata/annotations.yaml

Version: **0.2.384-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6825fdf005a8f4a22ee5ab05
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6825fdee05a8f4a22ee5ab00

operator test-e2e-operator-fbc (0.2.384-1)

---

operators/test-e2e-operator/0.2.384-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.384-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.384-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.384-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.384-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.384-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.384-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6826496305a8f4a22ee5ca08
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682649622fb6b25e796e87b2

operator test-e2e-operator (0.2.384-2)

---

operators/test-e2e-operator/0.2.386-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.386-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.386-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.386-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.386-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.386-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.386-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682736812fb6b25e796eefe2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6827367e05a8f4a22ee631f4

operator test-e2e-operator (0.2.386-1)

---

operators/test-e2e-community-operator/0.2.386-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.386-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.386-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.386-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.386-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.386-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.386-1)

operator test-e2e-community-operator (0.2.386-1)

---

operators/test-e2e-operator-fbc/0.2.387-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.387-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.387-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.387-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.387-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.387-1/metadata/annotations.yaml

Version: **0.2.387-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6827489205a8f4a22ee639db
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682748902fb6b25e796ef7b1

operator test-e2e-operator-fbc (0.2.387-1)

---

operators/test-e2e-operator/0.2.387-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.387-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.387-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.387-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.387-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.387-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.387-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6827489e2fb6b25e796ef7c5
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6827489b05a8f4a22ee639f6

operator test-e2e-operator (0.2.387-1)

---

operators/test-e2e-community-operator/0.2.387-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.387-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.387-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.387-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.387-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.387-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.387-1)

operator test-e2e-community-operator (0.2.387-1)

---

operators/test-e2e-operator/0.2.390-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.390-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.390-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.390-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.390-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.390-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.390-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682b2eec1472b9f185f8851a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682b2eea743d4540777656aa

operator test-e2e-operator (0.2.390-1)

---

operators/test-e2e-community-operator/0.2.390-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.390-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.390-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.390-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.390-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.390-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.390-1)

operator test-e2e-community-operator (0.2.390-1)

---

operators/test-e2e-operator-fbc/0.2.390-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.390-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.390-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.390-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.390-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.390-2/metadata/annotations.yaml

Version: **0.2.390-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682b423c8432f29db1412e44
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682b423b743d454077765f5a

operator test-e2e-operator-fbc (0.2.390-2)

---

operators/test-e2e-operator-fbc/0.2.391-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.391-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.391-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.391-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.391-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.391-1/metadata/annotations.yaml

Version: **0.2.391-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682b4df9743d454077766466
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682b4df7743d454077766463

operator test-e2e-operator-fbc (0.2.391-1)

---

operators/test-e2e-operator/0.2.391-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.391-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.391-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.391-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.391-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.391-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.391-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682b4de18432f29db1413335
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682b4ddf743d454077766448

operator test-e2e-operator (0.2.391-1)

---

operators/test-e2e-community-operator/0.2.391-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.391-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.391-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.391-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.391-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.391-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.391-1)

operator test-e2e-community-operator (0.2.391-1)

---

operators/test-e2e-operator-fbc/0.2.392-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.392-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.392-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.392-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.392-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.392-1/metadata/annotations.yaml

Version: **0.2.392-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682c281e8432f29db1418dfe
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682c281c743d45407776befb

operator test-e2e-operator-fbc (0.2.392-1)

---

operators/test-e2e-operator/0.2.392-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.392-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.392-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.392-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.392-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.392-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.392-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682c2848743d45407776bf20
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682c2846743d45407776bf1b

operator test-e2e-operator (0.2.392-1)

---

operators/test-e2e-operator-fbc/0.2.393-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.393-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.393-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.393-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.393-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.393-1/metadata/annotations.yaml

Version: **0.2.393-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682c2d318432f29db1419138
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682c2d2f743d45407776c244

operator test-e2e-operator-fbc (0.2.393-1)

---

operators/test-e2e-community-operator/0.2.392-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.392-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.392-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.392-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.392-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.392-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.392-1)

operator test-e2e-community-operator (0.2.392-1)

---

operators/test-e2e-operator/0.2.393-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.393-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.393-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.393-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.393-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.393-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.393-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682c2ce88432f29db14190f9
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682c2ce6743d45407776c207

operator test-e2e-operator (0.2.393-1)

---

operators/test-e2e-community-operator/0.2.393-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.393-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.393-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.393-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.393-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.393-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.393-1)

operator test-e2e-community-operator (0.2.393-1)

---

operators/test-e2e-operator-fbc/0.2.395-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.395-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.395-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.395-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.395-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.395-1/metadata/annotations.yaml

Version: **0.2.395-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682c7509743d45407776e300
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682c75078432f29db141b194

operator test-e2e-operator-fbc (0.2.395-1)

---

operators/test-e2e-operator/0.2.395-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.395-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.395-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.395-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.395-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.395-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.395-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682c74f7743d45407776e2e1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682c74f6743d45407776e2dc

operator test-e2e-operator (0.2.395-1)

---

operators/test-e2e-community-operator/0.2.395-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.395-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.395-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.395-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.395-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.395-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.395-1)

operator test-e2e-community-operator (0.2.395-1)

---

operators/test-e2e-operator-fbc/0.2.397-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.397-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.397-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.397-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.397-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.397-1/metadata/annotations.yaml

Version: **0.2.397-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682c86e88432f29db141b9a1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682c86e68432f29db141b99c

operator test-e2e-operator-fbc (0.2.397-1)

---

operators/test-e2e-operator/0.2.397-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.397-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.397-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.397-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.397-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.397-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.397-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682c86f18432f29db141b9b5
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682c86ef743d45407776eb2f

operator test-e2e-operator (0.2.397-1)

---

operators/test-e2e-community-operator/0.2.397-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.397-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.397-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.397-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.397-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.397-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.397-1)

operator test-e2e-community-operator (0.2.397-1)

---

operators/test-e2e-operator-fbc/0.2.416-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.416-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.416-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.416-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.416-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.416-1/metadata/annotations.yaml

Version: **0.2.416-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682ee80cd88a00fadbcb44f3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682ee80ae367c7775148e0d9

operator test-e2e-operator-fbc (0.2.416-1)

---

operators/test-e2e-operator-fbc/0.2.418-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.418-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.418-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.418-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.418-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.418-1/metadata/annotations.yaml

Version: **0.2.418-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682efad0d88a00fadbcb4ce1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682efacee367c7775148e8c7

operator test-e2e-operator-fbc (0.2.418-1)

---

operators/test-e2e-community-operator/0.2.418-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.418-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.418-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.418-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.418-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.418-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.418-2)

operator test-e2e-community-operator (0.2.418-2)

---

operators/test-e2e-operator-fbc/0.2.419-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.419-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.419-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.419-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.419-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.419-1/metadata/annotations.yaml

Version: **0.2.419-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682f0aaee367c7775148ef70
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682f0aacd88a00fadbcb5396

operator test-e2e-operator-fbc (0.2.419-1)

---

operators/test-e2e-operator/0.2.419-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.419-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.419-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.419-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.419-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.419-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.419-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682f0ad7d88a00fadbcb53c8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682f0ad5e367c7775148ef89

operator test-e2e-operator (0.2.419-1)

---

operators/test-e2e-community-operator/0.2.419-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.419-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.419-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.419-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.419-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.419-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.419-1)

operator test-e2e-community-operator (0.2.419-1)

---

operators/test-e2e-operator/0.2.422-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.422-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.422-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.422-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.422-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.422-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.422-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/682f6d91e367c77751491834
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/682f6d8fd88a00fadbcb7c90

operator test-e2e-operator (0.2.422-1)

---

operators/test-e2e-community-operator/0.2.422-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.422-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.422-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.422-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.422-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.422-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.422-1)

operator test-e2e-community-operator (0.2.422-1)

---

operators/test-e2e-operator-fbc/0.2.423-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.423-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.423-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.423-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.423-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.423-2/metadata/annotations.yaml

Version: **0.2.423-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68341684e367c777514b0597
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68341681e367c777514b058c

operator test-e2e-operator-fbc (0.2.423-2)

---

operators/test-e2e-community-operator/0.2.423-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.423-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.423-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.423-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.423-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.423-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.423-2)

operator test-e2e-community-operator (0.2.423-2)

---

operators/test-e2e-community-operator/0.2.423-5/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.423-5/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.423-5/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.423-5/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.423-5/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.423-5/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.423-5)

operator test-e2e-community-operator (0.2.423-5)

---

operators/test-e2e-operator-fbc/0.2.427-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.427-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.427-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.427-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.427-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.427-1/metadata/annotations.yaml

Version: **0.2.427-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/683457b8e367c777514b22e2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/683457b7e367c777514b22df

operator test-e2e-operator-fbc (0.2.427-1)

---

operators/test-e2e-operator/0.2.427-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.427-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.427-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.427-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.427-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.427-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.427-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/683457e5d88a00fadbcd867f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/683457e3e367c777514b230b

operator test-e2e-operator (0.2.427-1)

---

operators/test-e2e-community-operator/0.2.427-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.427-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.427-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.427-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.427-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.427-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.427-1)

operator test-e2e-community-operator (0.2.427-1)

---

operators/test-e2e-operator/0.2.432-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.432-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.432-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.432-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.432-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.432-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.432-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68370315563e221cc33264c0
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68370313563e221cc33264b9

operator test-e2e-operator (0.2.432-1)

---

operators/test-e2e-community-operator/0.2.434-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.434-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.434-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.434-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.434-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.434-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.434-1)

operator test-e2e-community-operator (0.2.434-1)

---

operators/test-e2e-community-operator/0.2.436-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.436-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.436-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.436-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.436-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.436-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.436-1)

operator test-e2e-community-operator (0.2.436-1)

---

operators/test-e2e-community-operator/0.2.445-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.445-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.445-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.445-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.445-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.445-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.445-1)

operator test-e2e-community-operator (0.2.445-1)

---

catalogs/v4.17/test-e2e-operator-fbc-catalog/catalog.yaml

E2e test for test-e2e-operator-fbc-catalog (0.2.446-1)

Catalog update [test-e2e-operator-fbc-catalog] [v4.17]

---

operators/test-e2e-operator/0.2.446-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.446-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.446-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.446-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.446-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.446-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.446-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/683da174b7b6d8c0d65a17e8
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/683da171563e221cc3352e77

operator test-e2e-operator (0.2.446-1)

---

operators/test-e2e-community-operator/0.2.446-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.446-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.446-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.446-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.446-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.446-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.446-1)

operator test-e2e-community-operator (0.2.446-1)

---

operators/test-e2e-operator-fbc/0.2.448-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.448-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.448-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.448-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.448-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.448-1/metadata/annotations.yaml

Version: **0.2.448-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/683eb31ac901de85b07a4d0e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/683eb318c901de85b07a4d0b

operator test-e2e-operator-fbc (0.2.448-1)

---

operators/test-e2e-operator/0.2.448-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.448-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.448-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.448-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.448-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.448-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.448-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/683eb330e4453625a8915344
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/683eb32ee4453625a891533d

operator test-e2e-operator (0.2.448-1)

---

operators/test-e2e-operator-fbc/0.2.451-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.451-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.451-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.451-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.451-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.451-1/metadata/annotations.yaml

Version: **0.2.451-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68404bf9e4453625a8920024
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68404bf7c901de85b07afb1b

operator test-e2e-operator-fbc (0.2.451-1)

---

operators/test-e2e-community-operator/0.2.451-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.451-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.451-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.451-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.451-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.451-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.451-1)

operator test-e2e-community-operator (0.2.451-1)

---

operators/test-e2e-operator-fbc/0.2.453-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.453-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.453-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.453-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.453-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.453-1/metadata/annotations.yaml

Version: **0.2.453-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6846c3715c479ca594697738
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6846c36f0033936657907895

operator test-e2e-operator-fbc (0.2.453-1)

---

operators/test-e2e-community-operator/0.2.453-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.453-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.453-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.453-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.453-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.453-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.453-1)

operator test-e2e-community-operator (0.2.453-1)

---

operators/test-e2e-operator/0.2.454-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.454-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.454-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.454-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.454-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.454-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.454-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/684700700033936657909299
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6847006d0033936657909294

operator test-e2e-operator (0.2.454-1)

---

operators/test-e2e-operator/0.2.462-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.462-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.462-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.462-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.462-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.462-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.462-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/684fe11319f1336c0405e1ba
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/684fe111af5309bc863318d8

operator test-e2e-operator (0.2.462-1)

---

operators/test-e2e-operator-fbc/0.2.464-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.464-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.464-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.464-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.464-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.464-1/metadata/annotations.yaml

Version: **0.2.464-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/684ff44119f1336c0405ec6c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/684ff43f19f1336c0405ec65

operator test-e2e-operator-fbc (0.2.464-1)

---

operators/test-e2e-community-operator/0.2.476-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.476-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.476-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.476-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.476-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.476-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.476-1)

operator test-e2e-community-operator (0.2.476-1)

---

operators/test-e2e-community-operator/0.2.477-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.477-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.477-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.477-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.477-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.477-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.477-1)

operator test-e2e-community-operator (0.2.477-1)

---

operators/test-e2e-operator-fbc/0.2.477-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.477-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.477-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.477-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.477-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.477-2/metadata/annotations.yaml

Version: **0.2.477-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6852b65c54faad601aebcaf7
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6852b65963eb4fcc5473f87a

operator test-e2e-operator-fbc (0.2.477-2)

---

operators/test-e2e-operator-fbc/0.2.482-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.482-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.482-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.482-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.482-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.482-1/metadata/annotations.yaml

Version: **0.2.482-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/685333d646f0fca28c9d33af
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/685333d3d0f3043a5da5fc42

operator test-e2e-operator-fbc (0.2.482-1)

---

operators/test-e2e-operator/0.2.482-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.482-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.482-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.482-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.482-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.482-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.482-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/685333f246f0fca28c9d33d3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/685333efd0f3043a5da5fc5e

operator test-e2e-operator (0.2.482-1)

---

operators/test-e2e-community-operator/0.2.482-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.482-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.482-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.482-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.482-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.482-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.482-1)

operator test-e2e-community-operator (0.2.482-1)

---

operators/test-e2e-operator-fbc/0.2.481-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.481-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.481-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.481-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.481-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.481-2/metadata/annotations.yaml

Version: **0.2.481-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6853c518d0f3043a5da6394c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6853c516d0f3043a5da63947

operator test-e2e-operator-fbc (0.2.481-2)

---

operators/test-e2e-operator/0.2.484-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.484-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.484-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.484-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.484-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.484-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.484-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/685508acd0f3043a5da6c324
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/685508aa46f0fca28c9df9ff

operator test-e2e-operator (0.2.484-1)

---

operators/test-e2e-operator-fbc/0.2.491-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.491-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.491-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.491-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.491-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.491-1/metadata/annotations.yaml

Version: **0.2.491-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68556fd6d0f3043a5da6ef95
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68556fd4d0f3043a5da6ef90

operator test-e2e-operator-fbc (0.2.491-1)

---

operators/test-e2e-operator/0.2.490-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.490-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.490-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.490-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.490-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.490-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.490-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68557003d0f3043a5da6efc2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68557001d0f3043a5da6efbb

operator test-e2e-operator (0.2.490-1)

---

operators/test-e2e-operator/0.2.491-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.491-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.491-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.491-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.491-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.491-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.491-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6855700846f0fca28c9e26dc
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68557006d0f3043a5da6efd3

operator test-e2e-operator (0.2.491-1)

---

operators/test-e2e-community-operator/0.2.491-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.491-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.491-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.491-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.491-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.491-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.491-1)

operator test-e2e-community-operator (0.2.491-1)

---

operators/test-e2e-operator/0.2.492-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.492-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.492-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.492-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.492-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.492-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.492-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68597074bc2128912141e83c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/685970724628287b9b523197

operator test-e2e-operator (0.2.492-1)

---

operators/test-e2e-community-operator/0.2.492-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.492-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.492-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.492-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.492-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.492-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.492-1)

operator test-e2e-community-operator (0.2.492-1)

---

operators/test-e2e-operator-fbc/0.2.496-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.496-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.496-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.496-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.496-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.496-1/metadata/annotations.yaml

Version: **0.2.496-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/685b0e6a4628287b9b52df71
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/685b0e674628287b9b52df6e

operator test-e2e-operator-fbc (0.2.496-1)

---

operators/test-e2e-operator/0.2.496-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.496-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.496-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.496-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.496-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.496-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.496-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/685b0e88bc21289121429641
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/685b0e86bc2128912142963c

operator test-e2e-operator (0.2.496-1)

---

operators/test-e2e-operator-fbc/0.2.499-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.499-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.499-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.499-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.499-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.499-1/metadata/annotations.yaml

Version: **0.2.499-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/685cffb6063886fcd087b1f1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/685cffb4063886fcd087b1ea

operator test-e2e-operator-fbc (0.2.499-1)

---

operators/test-e2e-operator-fbc/0.2.503-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.503-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.503-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.503-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.503-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.503-1/metadata/annotations.yaml

Version: **0.2.503-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/687530981fc7165858a74c23
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/687530960eed01939e4fa731

operator test-e2e-operator-fbc (0.2.503-1)

---

operators/test-e2e-operator-fbc/0.2.513-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.513-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.513-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.513-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.513-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.513-1/metadata/annotations.yaml

Version: **0.2.513-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6888c6d6a4322fe3aadedf19
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6888c6d3630c083c470c95bb

operator test-e2e-operator-fbc (0.2.513-1)

---

operators/test-e2e-operator/0.2.513-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.513-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.513-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.513-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.513-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.513-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.513-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6888c6d6a4322fe3aadedf18
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6888c6d4a4322fe3aadedf0d

operator test-e2e-operator (0.2.513-1)

---

operators/test-e2e-community-operator/0.2.514-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.514-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.514-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.514-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.514-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.514-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.514-1)

operator test-e2e-community-operator (0.2.514-1)

---

operators/test-e2e-operator/0.2.520-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.520-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.520-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.520-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.520-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.520-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.520-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6891fd8ae683febda1218a5c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6891fd88e683febda1218a55

operator test-e2e-operator (0.2.520-1)

---

operators/test-e2e-community-operator/0.2.520-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.520-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.520-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.520-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.520-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.520-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.520-1)

operator test-e2e-community-operator (0.2.520-1)

---

operators/test-e2e-operator-fbc/0.2.528-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.528-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.528-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.528-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.528-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.528-1/metadata/annotations.yaml

Version: **0.2.528-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6893059a3c880bdc00c51130
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68930599e683febda121f828

operator test-e2e-operator-fbc (0.2.528-1)

---

operators/test-e2e-operator-fbc/0.2.530-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.530-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.530-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.530-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.530-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.530-1/metadata/annotations.yaml

Version: **0.2.530-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6893646fe683febda1222142
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6893646d3c880bdc00c53a75

operator test-e2e-operator-fbc (0.2.530-1)

---

operators/test-e2e-community-operator/0.2.530-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.530-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.530-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.530-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.530-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.530-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.530-1)

operator test-e2e-community-operator (0.2.530-1)

---

operators/test-e2e-community-operator/0.2.531-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.531-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.531-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.531-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.531-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.531-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.531-1)

operator test-e2e-community-operator (0.2.531-1)

---

operators/test-e2e-operator-fbc/0.2.534-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.534-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.534-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.534-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.534-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.534-1/metadata/annotations.yaml

Version: **0.2.534-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6894b3b7505ee57fc7bc9820
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6894b3b4c775230bdc4d2803

operator test-e2e-operator-fbc (0.2.534-1)

---

operators/test-e2e-operator/0.2.534-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.534-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.534-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.534-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.534-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.534-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.534-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6894b34e505ee57fc7bc97dc
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6894b34dc775230bdc4d27c0

operator test-e2e-operator (0.2.534-1)

---

operators/test-e2e-operator-fbc/0.2.537-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.537-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.537-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.537-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.537-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.537-1/metadata/annotations.yaml

Version: **0.2.537-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/6899da09c775230bdc4f52b2
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/6899da06c775230bdc4f52ac

operator test-e2e-operator-fbc (0.2.537-1)

---

operators/test-e2e-community-operator/0.2.537-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.537-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.537-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.537-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.537-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.537-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.537-1)

operator test-e2e-community-operator (0.2.537-1)

---

operators/test-e2e-operator/0.2.545-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.545-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.545-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.545-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.545-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.545-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.545-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/689ba4e9e4f088b23174b809
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/689ba4e8cfea31cb6ac7533c

operator test-e2e-operator (0.2.545-1)

---

operators/test-e2e-community-operator/0.2.545-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.545-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.545-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.545-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.545-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.545-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.545-1)

operator test-e2e-community-operator (0.2.545-1)

---

operators/test-e2e-community-operator/0.2.547-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.547-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.547-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.547-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.547-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.547-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.547-2)

operator test-e2e-community-operator (0.2.547-2)

---

operators/test-e2e-operator-fbc/0.2.551-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.551-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.551-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.551-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.551-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.551-1/metadata/annotations.yaml

Version: **0.2.551-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/689dc6dacfea31cb6ac83a44
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/689dc6d71add77354b5040da

operator test-e2e-operator-fbc (0.2.551-1)

---

operators/test-e2e-operator/0.2.551-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.551-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.551-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.551-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.551-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.551-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.551-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/689dd084cfea31cb6ac83e6f
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/689dd0831add77354b5044f1

operator test-e2e-operator (0.2.551-2)

---

operators/test-e2e-operator/0.2.551-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.551-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.551-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.551-3/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.551-3/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.551-3/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.551-3**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/689dde431add77354b504af1
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/689dde41cfea31cb6ac8446a

operator test-e2e-operator (0.2.551-3)

---

operators/test-e2e-community-operator/0.2.551-3/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.551-3/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.551-3/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.551-3/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.551-3/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.551-3/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.551-3)

operator test-e2e-community-operator (0.2.551-3)

---

operators/test-e2e-operator/0.2.551-4/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.551-4/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.551-4/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.551-4/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.551-4/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.551-4/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.551-4**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/689df9e0cfea31cb6ac8503c
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/689df9de1add77354b5056d6

operator test-e2e-operator (0.2.551-4)

---

operators/test-e2e-community-operator/0.2.551-5/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.551-5/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.551-5/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.551-5/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.551-5/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.551-5/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.551-5)

operator test-e2e-community-operator (0.2.551-5)

---

operators/test-e2e-operator/0.2.551-7/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.551-7/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.551-7/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.551-7/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.551-7/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.551-7/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.551-7**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/689efb3bcfea31cb6ac8bafb
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/689efb3a1add77354b50c16f

operator test-e2e-operator (0.2.551-7)

---

operators/test-e2e-operator-fbc/0.2.552-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.552-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.552-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.552-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.552-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.552-1/metadata/annotations.yaml

Version: **0.2.552-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/689f099d1add77354b50c76e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/689f099bcfea31cb6ac8c0ed

operator test-e2e-operator-fbc (0.2.552-1)

---

operators/test-e2e-operator-fbc/0.2.555-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.555-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.555-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.555-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.555-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.555-1/metadata/annotations.yaml

Version: **0.2.555-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/689fa4d7cfea31cb6ac90155
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/689fa4d5cfea31cb6ac9014e

operator test-e2e-operator-fbc (0.2.555-1)

---

operators/test-e2e-operator-fbc/0.2.565-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.565-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.565-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.565-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.565-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.565-1/metadata/annotations.yaml

Version: **0.2.565-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68a43a2ffc735426b05f006e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68a43a2dfc735426b05f0065

operator test-e2e-operator-fbc (0.2.565-1)

---

operators/test-e2e-operator/0.2.565-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.565-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.565-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.565-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.565-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.565-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.565-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68a43a092c8a284148622903
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68a43a06fc735426b05f0047

operator test-e2e-operator (0.2.565-1)

---

operators/test-e2e-operator/0.2.567-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.567-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.567-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.567-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.567-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.567-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.567-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68a45fb92c8a284148623b73
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68a45fb82c8a284148623b70

operator test-e2e-operator (0.2.567-1)

---

operators/test-e2e-community-operator/0.2.567-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.567-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.567-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.567-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.567-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.567-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.567-1)

operator test-e2e-community-operator (0.2.567-1)

---

operators/test-e2e-operator/0.2.568-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.568-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.568-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.568-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.568-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.568-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.568-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68a485d5fc735426b05f2418
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68a485d4fc735426b05f2415

operator test-e2e-operator (0.2.568-1)

---

operators/test-e2e-operator/0.2.570-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.570-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.570-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.570-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.570-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.570-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.570-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68a4bcb6fc735426b05f3b9b
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68a4bcb42c8a2841486263e0

operator test-e2e-operator (0.2.570-1)

---

operators/test-e2e-community-operator/0.2.570-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.570-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.570-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.570-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.570-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.570-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.570-1)

operator test-e2e-community-operator (0.2.570-1)

---

operators/test-e2e-operator-fbc/0.2.571-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.571-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.571-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.571-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.571-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.571-1/metadata/annotations.yaml

Version: **0.2.571-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68a57688fc735426b05f89d3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68a576862c8a28414862b1f8

operator test-e2e-operator-fbc (0.2.571-1)

---

operators/test-e2e-community-operator/0.2.571-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.571-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.571-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.571-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.571-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.571-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.571-1)

operator test-e2e-community-operator (0.2.571-1)

---

operators/test-e2e-operator-fbc/0.2.573-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.573-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.573-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.573-2/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.573-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.573-2/metadata/annotations.yaml

Version: **0.2.573-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68a5c78afc735426b05fad4e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68a5c7882c8a28414862d57c

operator test-e2e-operator-fbc (0.2.573-2)

---

operators/test-e2e-operator-fbc/0.2.577-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.577-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.577-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.577-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.577-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.577-1/metadata/annotations.yaml

Version: **0.2.577-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68ad9e84fdfcaea4bde3964a
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68ad9e83fdfcaea4bde39645

operator test-e2e-operator-fbc (0.2.577-1)

---

operators/test-e2e-operator/0.2.577-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.577-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.577-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.577-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.577-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.577-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.577-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68ad9eda4b3e50de9e952dc4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68ad9ed8fdfcaea4bde3968b

operator test-e2e-operator (0.2.577-1)

---

operators/test-e2e-operator-fbc/0.2.580-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.580-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.580-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.580-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.580-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.580-1/metadata/annotations.yaml

Version: **0.2.580-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68b009bd4b3e50de9e9632ee
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68b009bcfdfcaea4bde49ad6

operator test-e2e-operator-fbc (0.2.580-1)

---

operators/test-e2e-community-operator/0.2.581-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.581-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.581-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.581-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.581-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.581-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.581-1)

operator test-e2e-community-operator (0.2.581-1)

---

operators/test-e2e-community-operator/0.2.580-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.580-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.580-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.580-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.580-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.580-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.580-1)

operator test-e2e-community-operator (0.2.580-1)

---

operators/test-e2e-operator/0.2.580-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.580-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.580-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.580-2/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.580-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.580-2/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.580-2**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68b01bc84b3e50de9e963aa6
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68b01bc54b3e50de9e963a9f

operator test-e2e-operator (0.2.580-2)

---

operators/test-e2e-operator-fbc/0.2.582-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.582-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.582-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.582-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.582-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.582-1/metadata/annotations.yaml

Version: **0.2.582-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68b0381c4b3e50de9e9647f4
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68b03819fdfcaea4bde4afe2

operator test-e2e-operator-fbc (0.2.582-1)

---

operators/test-e2e-community-operator/0.2.582-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.582-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.582-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.582-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.582-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.582-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.582-1)

operator test-e2e-community-operator (0.2.582-1)

---

operators/test-e2e-operator-fbc/0.2.586-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.586-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.586-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.586-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.586-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.586-1/metadata/annotations.yaml

Version: **0.2.586-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68b54f03407819111828e2af
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68b54f01407819111828e2a8

operator test-e2e-operator-fbc (0.2.586-1)

---

operators/test-e2e-operator-fbc/0.2.590-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.590-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.590-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.590-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.590-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.590-1/metadata/annotations.yaml

Version: **0.2.590-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68b71466520bef2eafcb4fb3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68b714623c3a9afea9e9402f

operator test-e2e-operator-fbc (0.2.590-1)

---

operators/test-e2e-community-operator/0.2.591-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.591-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.591-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.591-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.591-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.591-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.591-1)

operator test-e2e-community-operator (0.2.591-1)

---

operators/test-e2e-operator/0.2.591-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.591-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.591-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.591-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.591-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.591-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.591-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68b7eb843c3a9afea9e99932
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68b7eb7e3c3a9afea9e9992d

operator test-e2e-operator (0.2.591-1)

---

operators/test-e2e-community-operator/0.2.599-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.599-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.599-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.599-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.599-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.599-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.599-1)

operator test-e2e-community-operator (0.2.599-1)

---

operators/test-e2e-community-operator/0.2.600-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.600-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.600-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.600-1/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.600-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.600-1/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.600-1)

operator test-e2e-community-operator (0.2.600-1)

---

operators/test-e2e-community-operator/0.2.601-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.601-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.601-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.601-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.601-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.601-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.601-2)

operator test-e2e-community-operator (0.2.601-2)

---

operators/test-e2e-operator/0.2.603-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.603-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.603-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.603-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.603-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.603-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.603-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68c7c894b4c7c0b6c443a09e
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68c7c892b4c7c0b6c443a099

operator test-e2e-operator (0.2.603-1)

---

operators/test-e2e-community-operator/0.2.603-2/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-community-operator/0.2.603-2/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-community-operator/0.2.603-2/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-community-operator/0.2.603-2/manifests/test-e2e-community-operator.clusterserviceversion.yaml
operators/test-e2e-community-operator/0.2.603-2/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-community-operator/0.2.603-2/metadata/annotations.yaml

E2e test for test-e2e-community-operator (0.2.603-2)

operator test-e2e-community-operator (0.2.603-2)

---

operators/test-e2e-operator-fbc/0.2.604-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator-fbc/0.2.604-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator-fbc/0.2.604-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator-fbc/0.2.604-1/manifests/test-e2e-operator-fbc.clusterserviceversion.yaml
operators/test-e2e-operator-fbc/0.2.604-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator-fbc/0.2.604-1/metadata/annotations.yaml

Version: **0.2.604-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68c82674daafbc9a821cfbf3
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68c82672b4c7c0b6c443c85d

operator test-e2e-operator-fbc (0.2.604-1)

---

operators/test-e2e-operator/0.2.604-1/manifests/simple-demo-operator-controller-manager-metrics-service_v1_service.yaml
operators/test-e2e-operator/0.2.604-1/manifests/simple-demo-operator-manager-config_v1_configmap.yaml
operators/test-e2e-operator/0.2.604-1/manifests/simple-demo-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
operators/test-e2e-operator/0.2.604-1/manifests/test-e2e-operator.clusterserviceversion.yaml
operators/test-e2e-operator/0.2.604-1/manifests/tools.opdev.io_demoresources.yaml
operators/test-e2e-operator/0.2.604-1/metadata/annotations.yaml
operators/test-e2e-operator/ci.yaml

Version: **0.2.604-1**
Test result URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/test-results/id/68c82675b4c7c0b6c443c862
Test logs URL: https://catalog.stage.redhat.com/api/containers/v1/projects/certification/artifacts/id/68c82672daafbc9a821cfbee

operator test-e2e-operator (0.2.604-1)
